# DO NOT EDIT — generated from packages/shared/contracts/projector-ownership-registry.json
# Run: python scripts/generate_platform_contracts.py
"""Generated Silver projector ownership (dispatcher order, activity owners, gaps)."""

from __future__ import annotations

PROJECTOR_OWNERSHIP_CONTRACT_VERSION = "1.0.0"

# Deterministic dispatcher order (ADR-C3) — must match _ALL_PROJECTORS.
PROJECTOR_ORDER: tuple[str, ...] = (
    "CommsProjector",
    "IdentityEvidenceProjector",
    "TouchpointProjector",
    "ExposureProjector",
    "OutcomeProjector",
    "RevenueProjector",
    "FrictionProjector",
    "AccountActivityProjector",
    "ServerOperationProjector",
    "AgentExecutionProjector",
    "AIInvocationProjector",
    "Web3TransactionProjector",
    "X402FlowProjector",
    "StablecoinProjector",
    "DerivativesProjector",
    "InteropProjector",
    "ConversionProjector",
    "CardLinkedProjector",
)

# Silver table each projector writes.
PROJECTOR_TABLES: dict[str, str] = {
    "CommsProjector": "silver_comms_facts",
    "IdentityEvidenceProjector": "silver_identity_evidence_facts",
    "TouchpointProjector": "silver_campaign_touchpoint_facts",
    "ExposureProjector": "silver_exposure_facts",
    "OutcomeProjector": "silver_outcome_facts",
    "RevenueProjector": "silver_revenue_facts",
    "FrictionProjector": "silver_friction_facts",
    "AccountActivityProjector": "silver_account_activity_facts",
    "ServerOperationProjector": "silver_server_operation_facts",
    "AgentExecutionProjector": "silver_agent_execution_facts",
    "AIInvocationProjector": "ai_execution_facts",
    "Web3TransactionProjector": "silver_web3_transaction_facts",
    "X402FlowProjector": "silver_x402_flow_facts",
    "StablecoinProjector": "silver_stablecoin_facts",
    "DerivativesProjector": "silver_derivatives_facts",
    "InteropProjector": "silver_interop_facts",
    "ConversionProjector": "canonical_conversions",
    "CardLinkedProjector": "card_linked_flow_facts",
}

# Canonical-activity role per projector (ADR-C4).
PROJECTOR_ACTIVITY_ROLES: dict[str, str] = {
    "CommsProjector": "comms_owner",
    "IdentityEvidenceProjector": "fact_emitter",
    "TouchpointProjector": "touchpoint_owner",
    "ExposureProjector": "fact_emitter",
    "OutcomeProjector": "fact_emitter",
    "RevenueProjector": "fact_emitter",
    "FrictionProjector": "no_activity",
    "AccountActivityProjector": "fact_emitter",
    "ServerOperationProjector": "no_activity",
    "AgentExecutionProjector": "fact_emitter",
    "AIInvocationProjector": "no_activity",
    "Web3TransactionProjector": "fact_emitter",
    "X402FlowProjector": "fact_emitter",
    "StablecoinProjector": "no_activity",
    "DerivativesProjector": "no_activity",
    "InteropProjector": "no_activity",
    "ConversionProjector": "fact_emitter",
    "CardLinkedProjector": "no_activity",
}

# Event-registry families each projector projects facts for.
PROJECTOR_EVENT_FAMILIES: dict[str, tuple[str, ...]] = {
    "CommsProjector": ("comms",),
    "IdentityEvidenceProjector": ("identity_lc",),
    "TouchpointProjector": ("comms", "core", "ecommerce", "exposure", "journey", "outcome"),
    "ExposureProjector": ("exposure",),
    "OutcomeProjector": ("outcome",),
    "RevenueProjector": ("commerce", "ecommerce"),
    "FrictionProjector": ("friction",),
    "AccountActivityProjector": ("b2b",),
    "ServerOperationProjector": ("server",),
    "AgentExecutionProjector": ("agent",),
    "AIInvocationProjector": ("agent",),
    "Web3TransactionProjector": ("wallet", "web3_lc"),
    "X402FlowProjector": (),
    "StablecoinProjector": ("stablecoin",),
    "DerivativesProjector": ("derivatives",),
    "InteropProjector": ("interop",),
    "ConversionProjector": ("ecommerce", "identity_lc"),
    "CardLinkedProjector": ("commerce", "reward", "wallet"),
}

# Exact dispatcher handles per projector.
PROJECTOR_EVENT_TYPES: dict[str, tuple[str, ...]] = {
    "CommsProjector": (
        "email_bounced",
        "email_clicked",
        "email_deferred",
        "email_delivered",
        "email_dropped",
        "email_opened",
        "email_processed",
        "email_queued",
        "email_replied",
        "email_sent",
        "email_spam_complaint",
        "email_suppressed",
        "message_received_observed",
        "message_replied_observed",
        "message_sent_observed",
        "notification_clicked",
        "notification_delivered",
        "notification_opened",
        "unsubscribe_observed",
    ),
    "IdentityEvidenceProjector": (
        "account_recovery_completed",
        "account_recovery_started",
        "alias_link_confirmed",
        "alias_link_requested",
        "alias_revoked",
        "device_registered",
        "device_revoked",
        "identity_verified",
        "login_failed",
        "login_succeeded",
        "logout_observed",
        "mfa_challenge_observed",
        "signup_completed",
        "signup_started",
        "sso_observed",
    ),
    "TouchpointProjector": (
        "ad_click",
        "ad_exposed",
        "app_install_attributed",
        "checkout_started",
        "click",
        "deep_link_opened",
        "deferred_attribution_resolved",
        "email_clicked",
        "email_delivered",
        "email_opened",
        "email_replied",
        "impression",
        "landing",
        "message_replied_observed",
        "notification_clicked",
        "notification_presented",
        "offer_exposed",
        "outcome_observed",
        "page",
        "page_view",
        "pageview",
        "product_viewed",
        "recommendation_exposed",
        "screen",
        "search_performed",
        "session_start",
        "session_started",
    ),
    "ExposureProjector": (
        "ad_exposed",
        "content_impression",
        "decision_observed",
        "feature_exposed",
        "notification_presented",
        "offer_exposed",
        "recommendation_exposed",
        "search_result_exposed",
    ),
    "OutcomeProjector": (
        "churn_observed",
        "feedback_submitted",
        "goal_achieved",
        "goal_failed",
        "human_override_observed",
        "outcome_observed",
        "recommendation_accepted",
        "recommendation_rejected",
        "retention_observed",
    ),
    "RevenueProjector": (
        "chargeback_observed",
        "invoice_failed",
        "invoice_issued",
        "invoice_paid",
        "order_cancelled",
        "order_completed",
        "order_refunded",
        "payment_failed",
        "payment_intent_created",
        "payment_succeeded",
        "subscription_cancelled",
        "subscription_downgrade_observed",
        "subscription_renewed",
        "subscription_started",
        "subscription_upgrade_observed",
        "trial_converted",
        "trial_started",
    ),
    "FrictionProjector": (
        "backtrack_observed",
        "dead_click_observed",
        "form_abandoned",
        "form_field_interaction",
        "form_started",
        "form_submitted",
        "form_validation_failed",
        "journey_stalled",
        "rage_click_observed",
        "retry_observed",
        "scroll_depth_observed",
        "search_reformulated",
    ),
    "AccountActivityProjector": (
        "api_key_created",
        "api_key_revoked",
        "integration_connected",
        "integration_disconnected",
        "member_invited",
        "member_joined",
        "member_removed",
        "organization_observed",
        "project_archived",
        "project_created",
        "role_changed",
        "seat_assigned",
        "seat_released",
        "service_account_created",
        "service_account_revoked",
        "workflow_completed",
        "workflow_failed",
        "workflow_started",
        "workspace_created",
        "workspace_updated",
    ),
    "ServerOperationProjector": (
        "api_request_observed",
        "connector_sync_completed",
        "connector_sync_failed",
        "connector_sync_started",
        "dependency_failure_observed",
        "export_completed",
        "job_completed",
        "job_failed",
        "job_started",
        "rate_limit_observed",
        "webhook_delivery_observed",
    ),
    "AgentExecutionProjector": (
        "agent_cost_observed",
        "agent_evaluation_observed",
        "agent_grounding_observed",
        "agent_guardrail_observed",
        "agent_handoff_observed",
        "agent_human_override_observed",
        "agent_step_observed",
        "agent_task_completed",
        "agent_task_failed",
        "agent_task_started",
        "agent_tool_call_observed",
        "agentic_session_abandoned",
        "agentic_session_completed",
        "agentic_session_started",
    ),
    "AIInvocationProjector": (
        "ai_invocation_observed",
    ),
    "Web3TransactionProjector": (
        "allowance_changed_observed",
        "bridge_transfer_observed",
        "contract_action",
        "settlement_finality_observed",
        "token_approval_observed",
        "transaction_confirmed",
        "transaction_confirmed_observed",
        "transaction_failed",
        "transaction_initiated",
        "transaction_pending_observed",
        "transaction_reorged_observed",
        "transaction_reverted_observed",
        "transaction_submitted",
        "wallet_connected",
        "wallet_disconnected",
    ),
    "X402FlowProjector": (
        "x402_payment_failed_observed",
        "x402_payment_initiated_observed",
        "x402_payment_required_observed",
        "x402_payment_verified_observed",
        "x402_resource_unlocked_observed",
        "x402_settlement_confirmed_observed",
    ),
    "StablecoinProjector": (
        "stablecoin_balance_snapshot_observed",
        "stablecoin_bridge_inbound_observed",
        "stablecoin_bridge_outbound_observed",
        "stablecoin_burn_observed",
        "stablecoin_depeg_detected",
        "stablecoin_depeg_resolved",
        "stablecoin_finality_confirmed",
        "stablecoin_holder_concentration_observed",
        "stablecoin_mint_observed",
        "stablecoin_observation_corrected",
        "stablecoin_payment_observed",
        "stablecoin_payout_observed",
        "stablecoin_reconciliation_run_completed",
        "stablecoin_reconciliation_variance_detected",
        "stablecoin_reconciliation_variance_resolved",
        "stablecoin_reorg_detected",
        "stablecoin_supply_snapshot_observed",
        "stablecoin_support_asserted",
        "stablecoin_support_revoked",
        "stablecoin_swap_observed",
        "stablecoin_transfer_observed",
        "stablecoin_treasury_movement_observed",
        "stablecoin_valuation_observed",
        "stablecoin_venue_deposit_observed",
        "stablecoin_venue_withdrawal_observed",
        "stablecoin_x402_settlement_observed",
    ),
    "DerivativesProjector": (
        "derivatives_account_link_revoked",
        "derivatives_account_linked",
        "derivatives_balance_snapshot_observed",
        "derivatives_collateral_change_observed",
        "derivatives_exposure_snapshot_materialized",
        "derivatives_fee_observed",
        "derivatives_fill_corrected",
        "derivatives_fill_observed",
        "derivatives_funding_payment_observed",
        "derivatives_margin_snapshot_observed",
        "derivatives_market_status_changed",
        "derivatives_order_cancelled_observed",
        "derivatives_order_expired_observed",
        "derivatives_order_observed",
        "derivatives_order_rejected_observed",
        "derivatives_order_updated_observed",
        "derivatives_pnl_snapshot_materialized",
        "derivatives_position_adl_observed",
        "derivatives_position_closed_observed",
        "derivatives_position_corrected",
        "derivatives_position_increased_observed",
        "derivatives_position_liquidated_observed",
        "derivatives_position_opened_observed",
        "derivatives_position_reduced_observed",
        "derivatives_position_settled_observed",
        "derivatives_price_observation_recorded",
        "derivatives_reconciliation_run_completed",
        "derivatives_reconciliation_variance_detected",
        "derivatives_reconciliation_variance_resolved",
        "derivatives_risk_policy_registered",
        "derivatives_risk_threshold_breached",
        "derivatives_strategy_registered",
        "derivatives_strategy_version_registered",
    ),
    "InteropProjector": (
        "interop_asset_leg_burned_observed",
        "interop_asset_leg_locked_observed",
        "interop_asset_leg_minted_observed",
        "interop_asset_leg_released_observed",
        "interop_fee_observed",
        "interop_intent_fulfilled_observed",
        "interop_intent_observed",
        "interop_message_cancelled",
        "interop_message_corrected",
        "interop_message_correlated",
        "interop_message_delivered",
        "interop_message_delivery_attempt_observed",
        "interop_message_discovered",
        "interop_message_executed_observed",
        "interop_message_expired",
        "interop_message_failed",
        "interop_message_recovered",
        "interop_message_refunded_observed",
        "interop_message_reorged",
        "interop_message_sent_observed",
        "interop_message_settled",
        "interop_message_source_confirmed",
        "interop_message_timeout",
        "interop_message_verification_observed",
        "interop_message_verified",
        "interop_reconciliation_run_completed",
        "interop_reconciliation_variance_detected",
        "interop_reconciliation_variance_resolved",
        "interop_security_policy_changed",
        "interop_security_policy_snapshot_recorded",
        "interop_verification_quorum_observed",
    ),
    "ConversionProjector": (
        "checkout_completed",
        "lead_created",
        "opportunity_closed_won",
        "order_completed",
        "payment_confirmed",
        "reward_redeemed",
        "signup_completed",
        "subscription_started",
        "trial_started",
        "x402_settled",
    ),
    "CardLinkedProjector": (
        "conversion",
        "payment_completed",
        "payment_failed",
        "payment_initiated",
        "reward_action_queued",
        "transaction",
    ),
}

# ADR-C4: the single canonical-activity owner per event type.
ACTIVITY_OWNER_BY_EVENT_TYPE: dict[str, str] = {
    "account_recovery_completed": "IdentityEvidenceProjector",
    "account_recovery_started": "IdentityEvidenceProjector",
    "ad_click": "TouchpointProjector",
    "ad_exposed": "TouchpointProjector",
    "agent_cost_observed": "AgentExecutionProjector",
    "agent_evaluation_observed": "AgentExecutionProjector",
    "agent_grounding_observed": "AgentExecutionProjector",
    "agent_guardrail_observed": "AgentExecutionProjector",
    "agent_handoff_observed": "AgentExecutionProjector",
    "agent_human_override_observed": "AgentExecutionProjector",
    "agent_step_observed": "AgentExecutionProjector",
    "agent_task_completed": "AgentExecutionProjector",
    "agent_task_failed": "AgentExecutionProjector",
    "agent_task_started": "AgentExecutionProjector",
    "agent_tool_call_observed": "AgentExecutionProjector",
    "agentic_session_abandoned": "AgentExecutionProjector",
    "agentic_session_completed": "AgentExecutionProjector",
    "agentic_session_started": "AgentExecutionProjector",
    "alias_link_confirmed": "IdentityEvidenceProjector",
    "alias_link_requested": "IdentityEvidenceProjector",
    "alias_revoked": "IdentityEvidenceProjector",
    "allowance_changed_observed": "Web3TransactionProjector",
    "api_key_created": "AccountActivityProjector",
    "api_key_revoked": "AccountActivityProjector",
    "app_install_attributed": "TouchpointProjector",
    "bridge_transfer_observed": "Web3TransactionProjector",
    "chargeback_observed": "RevenueProjector",
    "checkout_completed": "ConversionProjector",
    "checkout_started": "TouchpointProjector",
    "churn_observed": "OutcomeProjector",
    "click": "TouchpointProjector",
    "content_impression": "ExposureProjector",
    "contract_action": "Web3TransactionProjector",
    "decision_observed": "ExposureProjector",
    "deep_link_opened": "TouchpointProjector",
    "deferred_attribution_resolved": "TouchpointProjector",
    "device_registered": "IdentityEvidenceProjector",
    "device_revoked": "IdentityEvidenceProjector",
    "email_bounced": "CommsProjector",
    "email_clicked": "CommsProjector",
    "email_deferred": "CommsProjector",
    "email_delivered": "CommsProjector",
    "email_dropped": "CommsProjector",
    "email_opened": "CommsProjector",
    "email_processed": "CommsProjector",
    "email_queued": "CommsProjector",
    "email_replied": "CommsProjector",
    "email_sent": "CommsProjector",
    "email_spam_complaint": "CommsProjector",
    "email_suppressed": "CommsProjector",
    "feature_exposed": "ExposureProjector",
    "feedback_submitted": "OutcomeProjector",
    "goal_achieved": "OutcomeProjector",
    "goal_failed": "OutcomeProjector",
    "human_override_observed": "OutcomeProjector",
    "identity_verified": "IdentityEvidenceProjector",
    "impression": "TouchpointProjector",
    "integration_connected": "AccountActivityProjector",
    "integration_disconnected": "AccountActivityProjector",
    "invoice_failed": "RevenueProjector",
    "invoice_issued": "RevenueProjector",
    "invoice_paid": "RevenueProjector",
    "landing": "TouchpointProjector",
    "lead_created": "ConversionProjector",
    "login_failed": "IdentityEvidenceProjector",
    "login_succeeded": "IdentityEvidenceProjector",
    "logout_observed": "IdentityEvidenceProjector",
    "member_invited": "AccountActivityProjector",
    "member_joined": "AccountActivityProjector",
    "member_removed": "AccountActivityProjector",
    "message_received_observed": "CommsProjector",
    "message_replied_observed": "CommsProjector",
    "message_sent_observed": "CommsProjector",
    "mfa_challenge_observed": "IdentityEvidenceProjector",
    "notification_clicked": "CommsProjector",
    "notification_delivered": "CommsProjector",
    "notification_opened": "CommsProjector",
    "notification_presented": "TouchpointProjector",
    "offer_exposed": "TouchpointProjector",
    "opportunity_closed_won": "ConversionProjector",
    "order_cancelled": "RevenueProjector",
    "order_completed": "RevenueProjector",
    "order_refunded": "RevenueProjector",
    "organization_observed": "AccountActivityProjector",
    "outcome_observed": "TouchpointProjector",
    "page": "TouchpointProjector",
    "page_view": "TouchpointProjector",
    "pageview": "TouchpointProjector",
    "payment_confirmed": "ConversionProjector",
    "payment_failed": "RevenueProjector",
    "payment_intent_created": "RevenueProjector",
    "payment_succeeded": "RevenueProjector",
    "product_viewed": "TouchpointProjector",
    "project_archived": "AccountActivityProjector",
    "project_created": "AccountActivityProjector",
    "recommendation_accepted": "OutcomeProjector",
    "recommendation_exposed": "TouchpointProjector",
    "recommendation_rejected": "OutcomeProjector",
    "retention_observed": "OutcomeProjector",
    "reward_redeemed": "ConversionProjector",
    "role_changed": "AccountActivityProjector",
    "screen": "TouchpointProjector",
    "search_performed": "TouchpointProjector",
    "search_result_exposed": "ExposureProjector",
    "seat_assigned": "AccountActivityProjector",
    "seat_released": "AccountActivityProjector",
    "service_account_created": "AccountActivityProjector",
    "service_account_revoked": "AccountActivityProjector",
    "session_start": "TouchpointProjector",
    "session_started": "TouchpointProjector",
    "settlement_finality_observed": "Web3TransactionProjector",
    "signup_completed": "IdentityEvidenceProjector",
    "signup_started": "IdentityEvidenceProjector",
    "sso_observed": "IdentityEvidenceProjector",
    "subscription_cancelled": "RevenueProjector",
    "subscription_downgrade_observed": "RevenueProjector",
    "subscription_renewed": "RevenueProjector",
    "subscription_started": "RevenueProjector",
    "subscription_upgrade_observed": "RevenueProjector",
    "token_approval_observed": "Web3TransactionProjector",
    "transaction_confirmed": "Web3TransactionProjector",
    "transaction_confirmed_observed": "Web3TransactionProjector",
    "transaction_failed": "Web3TransactionProjector",
    "transaction_initiated": "Web3TransactionProjector",
    "transaction_pending_observed": "Web3TransactionProjector",
    "transaction_reorged_observed": "Web3TransactionProjector",
    "transaction_reverted_observed": "Web3TransactionProjector",
    "transaction_submitted": "Web3TransactionProjector",
    "trial_converted": "RevenueProjector",
    "trial_started": "RevenueProjector",
    "unsubscribe_observed": "CommsProjector",
    "wallet_connected": "Web3TransactionProjector",
    "wallet_disconnected": "Web3TransactionProjector",
    "workflow_completed": "AccountActivityProjector",
    "workflow_failed": "AccountActivityProjector",
    "workflow_started": "AccountActivityProjector",
    "workspace_created": "AccountActivityProjector",
    "workspace_updated": "AccountActivityProjector",
    "x402_payment_failed_observed": "X402FlowProjector",
    "x402_payment_initiated_observed": "X402FlowProjector",
    "x402_payment_required_observed": "X402FlowProjector",
    "x402_payment_verified_observed": "X402FlowProjector",
    "x402_resource_unlocked_observed": "X402FlowProjector",
    "x402_settled": "ConversionProjector",
    "x402_settlement_confirmed_observed": "X402FlowProjector",
}

# Later adapter-backed emitters converging on the owner's activity row.
CONVERGENT_ACTIVITY_EVENT_TYPES: dict[str, tuple[str, ...]] = {
    "ConversionProjector": ("order_completed", "signup_completed", "subscription_started", "trial_started"),
}

# Accepted event families with no dispatcher projector (family → status).
NO_PROJECTION_FAMILIES: dict[str, str] = {
    "consent": "no_projection",
    "credit": "pending",
    "identity": "pending",
    "interaction": "pending_pr2",
    "location": "pending",
    "x402": "pending",
}

# Dispatcher stages outside the fact-projector list.
OUT_OF_BAND_PROJECTORS: tuple[str, ...] = ("SilverGraphProjector",)

__all__ = [
    "PROJECTOR_OWNERSHIP_CONTRACT_VERSION",
    "PROJECTOR_ORDER",
    "PROJECTOR_TABLES",
    "PROJECTOR_ACTIVITY_ROLES",
    "PROJECTOR_EVENT_FAMILIES",
    "PROJECTOR_EVENT_TYPES",
    "ACTIVITY_OWNER_BY_EVENT_TYPE",
    "CONVERGENT_ACTIVITY_EVENT_TYPES",
    "NO_PROJECTION_FAMILIES",
    "OUT_OF_BAND_PROJECTORS",
]
