/** Governed decision/action contracts. These are evidence-bearing data types, not authority or readiness claims. */
import type { ApprovalLevel, RecommendationEvidence } from './decision-outcome-intelligence';
import type { GraphDecisionRecord, MutationRecord } from './graph-mutation';
import type { GraphObjectRef } from './graph-context-contract';
import type { EpistemicStatus } from './epistemic-status';
import type { PermissionAction, PermissionScope, PolicyDecision, SecurityAuditEvent } from './security-governance';
import type { AIInvocationObserved } from './ai-execution';
import type { EvidenceRef } from './operational-intelligence';
import type { ActorType } from './security-governance';

export type DecisionStatus = 'draft'|'pending_approval'|'approved'|'rejected'|'deferred'|'executed';
export type RuntimeDecisionStatus = DecisionStatus;
export type ExecutionStatus = 'planned'|'pending_approval'|'queued'|'running'|'partially_completed'|'completed'|'failed'|'cancelled'|'rolled_back';
export type ActionExecutionStatus = ExecutionStatus | 'rollback_pending' | 'rollback_failed';
export type ReversibilityCategory = 'reversible'|'recomputable'|'requires_compensating_mutation'|'irreversible';
export type CapabilityAvailability = 'not_entitled'|'unauthorized'|'not_ready'|'available';
export interface ActorRef { readonly id: string; readonly type: ActorType; readonly tenant_id?: string; }
export interface DecisionAlternative { readonly id: string; readonly label: string; readonly description?: string; readonly expected_outcome?: string; }
export interface ExecutionStep { readonly id: string; readonly action: string; readonly target_refs: readonly GraphObjectRef[]; readonly order: number; }
export interface ExecutionResult { readonly status: 'success'|'partial'|'failure'; readonly summary?: string; readonly output_refs?: readonly string[]; }
export interface EconomicValue { readonly amount: number; readonly currency: string; readonly basis: 'estimated'|'observed'|'billed'|'unknown'; }
export interface RuntimePermissionRequirement { readonly domain: string; readonly action: PermissionAction; readonly scope: PermissionScope; readonly approval_level: ApprovalLevel; readonly reason?: string; }
export interface ApprovalReference { readonly approval_id: string; readonly approver: ActorRef; readonly level: ApprovalLevel; readonly scope: PermissionScope; readonly tenant_id: string; readonly decision_id: string; readonly action_id?: string; readonly execution_id?: string; readonly approved_at: string; readonly expires_at?: string; }
export interface ActionEvidenceLink { readonly evidence_id: string; readonly kind: string; readonly ref: string; readonly epistemic_status: EpistemicStatus; readonly summary?: string; }
export interface ImpactPreview { readonly preview_id: string; readonly decision_id?: string; readonly execution_id?: string; readonly summary: string; readonly affected_entities: number; readonly affected_entity_refs?: readonly string[]; readonly graph_snapshot_id: string; readonly estimated_value?: EconomicValue; readonly risk_level: 'low'|'medium'|'high'|'unknown'; readonly reversibility: ReversibilityCategory; readonly generated_at: string; readonly limitations?: readonly string[]; }
export interface RollbackMetadata { readonly category: ReversibilityCategory; readonly supported: boolean; readonly plan_ref?: string; readonly compensation_ref?: string; readonly inverse_action_type?: string; readonly rollback_execution_id?: string; readonly inverse_applied?: boolean; readonly repair_required?: boolean; readonly limitation?: string; }
export interface ExternalExecutionConstraints { readonly external: boolean; readonly target_type?: string; readonly destination_ref?: string; readonly tenant_isolation_key: string; readonly consent_required: boolean; readonly consent_ref?: string; readonly idempotency_key: string; readonly environment: 'development'|'staging'|'production'|'unknown'; readonly readiness_evidence_refs?: readonly string[]; }
export interface ActionCapabilityEvaluation { readonly capability_key: string; readonly entitled: boolean; readonly permitted: boolean; readonly ready: boolean; readonly missing_requirements: readonly string[]; readonly evaluated_at: string; readonly evidence_refs?: readonly string[]; }
export interface CapabilityMatrix { readonly tenant_id: string; readonly action_key: string; readonly states: readonly ActionCapabilityEvaluation[]; readonly evaluated_at: string; }
export function resolveCapabilityState(value: Pick<ActionCapabilityEvaluation,'entitled'|'permitted'|'ready'|'evidence_refs'>): CapabilityAvailability { if (!value.entitled) return 'not_entitled'; if (!value.permitted) return 'unauthorized'; if (!value.ready || !value.evidence_refs?.length) return 'not_ready'; return 'available'; }

export interface Decision { readonly decision_id: string; readonly tenant_id: string; readonly status: DecisionStatus; readonly question: string; readonly investigation_id?: string; readonly decision_maker: ActorRef; readonly supporting_findings: readonly EvidenceRef[]; readonly evidence_refs: readonly EvidenceRef[]; readonly alternatives: readonly DecisionAlternative[]; readonly selected_alternative?: string; readonly confidence?: number; readonly rationale?: string; readonly policy_version?: string; readonly decidedAt?: string; readonly recommendation_id?: string; readonly required_permission: RuntimePermissionRequirement; readonly approval?: ApprovalReference; readonly impact_preview?: ImpactPreview; }
export type ActionRuntimeDecision = Decision;
export type ExecutionTrigger = { readonly kind: 'decision'; readonly decision_id: string } | { readonly kind: 'automation'; readonly automation_id: string };
export interface ActionExecutionLinks { readonly trigger: ExecutionTrigger; readonly evidence_refs: readonly EvidenceRef[]; readonly audit_event_refs: readonly string[]; readonly outcome_refs: readonly string[]; readonly mutation_refs?: readonly string[]; readonly ai_invocation_refs?: readonly string[]; readonly impact_preview_ref?: string; }
export interface Execution { readonly execution_id: string; readonly action_id: string; readonly tenant_id: string; readonly environment_id: string; readonly trigger: ExecutionTrigger; readonly status: ExecutionStatus| 'rollback_pending'|'rollback_failed'; readonly actor: ActorRef; readonly targets: readonly GraphObjectRef[]; readonly execution_type: string; readonly plan: readonly ExecutionStep[]; readonly permissions: readonly RuntimePermissionRequirement[]; readonly approvals: readonly ApprovalReference[]; readonly cost?: EconomicValue; readonly result?: ExecutionResult; readonly links: ActionExecutionLinks; readonly external_constraints: ExternalExecutionConstraints; readonly rollback: RollbackMetadata; readonly impact_preview?: ImpactPreview; }
export type ActionRuntimeExecution = Execution;

export type RuntimeTransitionErrorCode = 'unauthorized'|'approval_required'|'invalid_transition'|'tenant_mismatch'|'environment_mismatch'|'capability_denied'|'consent_or_policy_required'|'fake_rollback'|'missing_linkage'|'expired_approval'|'binding_mismatch'|'invalid_contract';
export class ActionRuntimeTransitionError extends Error { readonly code: RuntimeTransitionErrorCode; constructor(code: RuntimeTransitionErrorCode,message:string){super(message);this.name='ActionRuntimeTransitionError';this.code=code;} }
export interface ApprovalValidationInput { readonly approval?: ApprovalReference; readonly now: string; readonly tenant_id: string; readonly decision_id?: string; readonly action_id?: string; readonly execution_id?: string; readonly required_level?: ApprovalLevel; readonly required_scope?: PermissionScope; }
const level: Record<ApprovalLevel,number>={none:0,standard:1,elevated:2,critical:3};
export function validateApproval(input: ApprovalValidationInput): boolean { const a=input.approval; if(!a||a.tenant_id!==input.tenant_id|| (input.decision_id!==undefined&&a.decision_id!==input.decision_id)||(input.action_id!==undefined&&a.action_id!==input.action_id)||(input.execution_id!==undefined&&a.execution_id!==input.execution_id)||(input.required_level&&level[a.level]<level[input.required_level])||(input.required_scope&&a.scope!==input.required_scope)||(a.expires_at!==undefined&&a.expires_at<=input.now)) return false; return true; }
export interface TransitionContext { readonly tenant_id:string; readonly execution_tenant_id:string; readonly environment_id:string; readonly target_environment_ids?: readonly string[]; readonly permission_granted:boolean; readonly cancel_permission_granted?:boolean; readonly rollback_permission_granted?:boolean; readonly capability_ready:boolean; readonly consent_valid:boolean; readonly policy_allowed:boolean; readonly approval?:ApprovalReference; readonly now?:string; readonly required_approval_level?:ApprovalLevel; readonly action_id?:string; readonly execution_id?:string; readonly decision_id?:string; readonly rollback?:RollbackMetadata; readonly rollback_inverse_applied?:boolean; }
export interface DecisionTransitionContext { readonly tenant_id:string; readonly decision_tenant_id:string; readonly permission_granted:boolean; readonly approval_input?:ApprovalValidationInput; readonly approval_required?:boolean; }
const dnext:Record<DecisionStatus,readonly DecisionStatus[]>={draft:['pending_approval','approved','rejected','deferred'],pending_approval:['approved','rejected','deferred'],approved:['executed'],rejected:[],deferred:['pending_approval','rejected'],executed:[]};
const enext:Record<ActionExecutionStatus,readonly ActionExecutionStatus[]>={planned:['pending_approval','queued','cancelled'],pending_approval:['queued','cancelled'],queued:['running','cancelled'],running:['partially_completed','completed','failed','cancelled'],partially_completed:['running','completed','failed','cancelled','rollback_pending'],completed:['rollback_pending','rolled_back'],failed:['rollback_pending','rolled_back'],cancelled:[],rolled_back:[],rollback_pending:['rolled_back','rollback_failed'],rollback_failed:['rollback_pending']};
function fail(code:RuntimeTransitionErrorCode,msg:string):never{throw new ActionRuntimeTransitionError(code,msg);}
export function transitionDecision(current:DecisionStatus,next:DecisionStatus,c:DecisionTransitionContext):DecisionStatus { if(c.tenant_id!==c.decision_tenant_id)fail('tenant_mismatch','decision tenant does not match context');if(!c.permission_granted)fail('unauthorized','decision transition is unauthorized');if(next==='approved'&&c.approval_required&&!validateApproval(c.approval_input??{now:'',tenant_id:c.tenant_id}))fail('approval_required','valid approval is required');if(!dnext[current].includes(next))fail('invalid_transition',`cannot transition from ${current} to ${next}`);return next; }
export function transitionActionExecution(current:ActionExecutionStatus,next:ActionExecutionStatus,c:TransitionContext):ActionExecutionStatus { if(c.tenant_id!==c.execution_tenant_id)fail('tenant_mismatch','execution tenant does not match context');if(!enext[current].includes(next))fail('invalid_transition',`cannot transition from '+current+' to '+next+'`);if(next==='cancelled'){if(!enext[current].includes(next))fail('invalid_transition','invalid cancellation state');if(!c.cancel_permission_granted)fail('unauthorized','cancel authority is required');return next;}if(next==='rollback_pending'||next==='rolled_back'||next==='rollback_failed'){if(!c.rollback_permission_granted)fail('unauthorized','rollback authority is required');if(c.rollback?.category==='irreversible'||c.rollback?.supported!==true||(!c.rollback.plan_ref&&!c.rollback.compensation_ref&&!c.rollback.inverse_action_type))fail('fake_rollback','supported rollback plan and inverse are required');if(next==='rolled_back'&&!c.rollback_inverse_applied)fail('fake_rollback','inverse must be applied');if(!enext[current].includes(next))fail('invalid_transition',`cannot transition from ${current} to ${next}`);return next;}if(next==='queued'||next==='running'){if(!c.permission_granted)fail('unauthorized','fresh permission is required');if(!c.capability_ready)fail('capability_denied','capability is not ready');if(!c.consent_valid||!c.policy_allowed)fail('consent_or_policy_required','valid consent and policy are required');if(!validateApproval({approval:c.approval,now:c.now??'',tenant_id:c.tenant_id,decision_id:c.decision_id,action_id:c.action_id,execution_id:c.execution_id,required_level:c.required_approval_level}))fail('approval_required','fresh bound approval is required');if(c.environment_id!==undefined&&c.target_environment_ids?.some(e=>e!==c.environment_id))fail('environment_mismatch','target environment does not match execution');}if(!enext[current].includes(next))fail('invalid_transition',`cannot transition from ${current} to ${next}`);return next; }
export function validateDecision(d:Decision):string[]{const e:string[]=[];if(!d.decision_id)e.push('decision_id is required');if(!d.question)e.push('question is required');return e;}
export function validateExecution(x:Execution):string[]{const e:string[]=[];if(!x.trigger||!x.links?.trigger||JSON.stringify(x.trigger)!==JSON.stringify(x.links.trigger))e.push('canonical trigger linkage is required');if(!x.targets)e.push('targets are required');else for(const t of x.targets)if(t.tenant_id!==x.tenant_id||t.environment_id!==x.environment_id)e.push('target is out of execution scope');if(!x.external_constraints||x.external_constraints.tenant_isolation_key!==x.tenant_id)e.push('tenant isolation key mismatch');if(x.execution_type!=='plan'&&x.execution_type!=='dry_run'&& !x.impact_preview&&!x.links?.impact_preview_ref)e.push('material execution requires impact preview');if(['completed','failed','cancelled','rolled_back'].includes(x.status)&&(!x.links?.audit_event_refs?.length||!x.links?.outcome_refs?.length||!x.links?.evidence_refs?.length))e.push('terminal execution requires audit, outcome and evidence');return e;}
export function validateImpactPreview(p:ImpactPreview):string[]{const e:string[]=[];if(!p.preview_id||!p.graph_snapshot_id)e.push('preview and graph snapshot are required');if(!p.decision_id&&!p.execution_id)e.push('impact preview must link to decision or execution');return e;}
export function canMarkDecisionExecuted(d:Decision,x:Execution):boolean{return d.status==='approved'&&x.status==='completed'&&x.trigger?.kind==='decision'&&x.trigger.decision_id===d.decision_id&&Boolean(x.links?.audit_event_refs?.length&&x.links?.outcome_refs?.length&&x.links?.evidence_refs?.length);}
export type ActionRuntimeSourceLinks={decision?:Decision|GraphDecisionRecord;recommendation_evidence?:RecommendationEvidence;mutation?:MutationRecord;audit?:SecurityAuditEvent;policy?:PolicyDecision;ai_invocation?:AIInvocationObserved};
