/** Governed decision-to-action contracts. These describe authority and evidence; they never grant authority or infer readiness. */
import type { ApprovalLevel, RecommendationEvidence } from './decision-outcome-intelligence';
import type { GraphDecisionRecord, MutationRecord } from './graph-mutation';
import type { GraphObjectRef } from './graph-context-contract';
import type { EpistemicStatus } from './epistemic-status';
import type { PermissionAction, PermissionScope, PolicyDecision, SecurityAuditEvent } from './security-governance';
import type { AIInvocationObserved } from './ai-execution';

export type DecisionStatus = 'draft' | 'pending_approval' | 'approved' | 'rejected' | 'deferred' | 'executed';
export type RuntimeDecisionStatus = DecisionStatus;
export type ExecutionStatus = 'planned' | 'pending_approval' | 'queued' | 'running' | 'partially_completed' | 'completed' | 'failed' | 'cancelled' | 'rolled_back';
export type ActionExecutionStatus = ExecutionStatus;
export type ReversibilityCategory = 'reversible' | 'recomputable' | 'requires_compensating_mutation' | 'irreversible';
export interface RuntimePermissionRequirement { readonly domain: 'actions' | 'dispatches' | 'decisions' | 'governance' | string; readonly action: PermissionAction; readonly scope: PermissionScope; readonly approval_level: ApprovalLevel; readonly reason?: string; }
export interface ApprovalReference { readonly approval_id: string; readonly approver_id: string; readonly approval_level: ApprovalLevel; readonly approved_at: string; readonly decision_id: string; readonly expires_at?: string; }
export interface ActionEvidenceLink { readonly evidence_id: string; readonly kind: 'recommendation' | 'graph' | 'policy' | 'consent' | 'external' | 'audit' | 'other'; readonly ref: string; readonly epistemic_status: EpistemicStatus; readonly summary?: string; }
export interface ImpactPreview { readonly summary: string; readonly affected_entities: number; readonly affected_entity_refs?: readonly string[]; readonly estimated_value?: number; readonly currency?: string; readonly risk_level: 'low' | 'medium' | 'high' | 'unknown'; readonly reversibility: ReversibilityCategory; readonly generated_at: string; readonly graph_snapshot_id?: string; readonly limitations?: readonly string[]; }
export interface RollbackMetadata { readonly category: ReversibilityCategory; readonly supported: boolean; readonly plan_ref?: string; readonly inverse_action_type?: string; readonly rollback_execution_id?: string; readonly requested_at?: string; readonly completed_at?: string; readonly inverse_applied?: boolean; readonly repair_required?: boolean; readonly limitation?: string; }
export interface ExternalExecutionConstraints { readonly external: boolean; readonly target_type?: string; readonly destination_ref?: string; readonly tenant_isolation_key: string; readonly consent_required: boolean; readonly consent_ref?: string; readonly idempotency_key: string; readonly environment: 'development' | 'staging' | 'production' | 'unknown'; readonly readiness_evidence_refs?: readonly string[]; }
export interface ActionCapabilityEvaluation { readonly capability_key: string; readonly entitled: boolean; readonly permitted: boolean; readonly ready: boolean; readonly missing_requirements: readonly string[]; readonly evaluated_at: string; readonly evidence_refs?: readonly string[]; }
export interface CapabilityMatrix { readonly tenant_id: string; readonly action_key: string; readonly states: readonly ActionCapabilityEvaluation[]; readonly evaluated_at: string; }
export interface Decision { readonly decision_id: string; readonly tenant_id: string; readonly status: DecisionStatus; readonly question: string; readonly investigation?: string | GraphObjectRef; readonly decision_maker: string; readonly supporting_findings: readonly string[]; readonly evidence_refs: readonly string[]; readonly alternatives: readonly string[]; readonly selected_alternative?: string; readonly confidence: number; readonly rationale: string; readonly policy_version: string; readonly decidedAt?: string; readonly recommendation_id?: string; readonly required_permission: RuntimePermissionRequirement; readonly approval?: ApprovalReference; }
export type ActionRuntimeDecision = Decision;
export interface ActionExecutionLinks { readonly decision_id: string; readonly recommendation_id?: string; readonly evidence_refs: readonly string[]; readonly audit_event_refs: readonly string[]; readonly outcome_refs: readonly string[]; readonly mutation_refs?: readonly string[]; readonly ai_invocation_refs?: readonly string[]; }
export interface Execution { readonly execution_id: string; readonly action_id: string; readonly tenant_id: string; readonly decision_id: string; readonly status: ExecutionStatus; readonly actor: string; readonly targets: readonly GraphObjectRef[]; readonly execution_type: string; readonly plan: string; readonly permissions: readonly RuntimePermissionRequirement[]; readonly approvals: readonly ApprovalReference[]; readonly cost?: { readonly amount?: number; readonly currency?: string; readonly basis?: string }; readonly result?: Record<string, unknown>; readonly evidence_refs: readonly string[]; readonly audit_id: string; readonly outcome_refs: readonly string[]; readonly links: ActionExecutionLinks; readonly external_constraints: ExternalExecutionConstraints; readonly rollback: RollbackMetadata; readonly started_at?: string; readonly completed_at?: string; readonly error_code?: string; }
export type ActionRuntimeExecution = Execution;
export type RuntimeTransitionErrorCode = 'unauthorized' | 'approval_required' | 'invalid_transition' | 'tenant_mismatch' | 'capability_denied' | 'consent_or_policy_required' | 'fake_rollback' | 'missing_linkage';
export class ActionRuntimeTransitionError extends Error { readonly code: RuntimeTransitionErrorCode; constructor(code: RuntimeTransitionErrorCode, message: string) { super(message); this.name = 'ActionRuntimeTransitionError'; this.code = code; } }
export interface TransitionContext { readonly tenant_id: string; readonly execution_tenant_id: string; readonly permission_granted: boolean; readonly capability_ready: boolean; readonly consent_valid: boolean; readonly policy_allowed: boolean; readonly approval_required?: boolean; readonly approval_present?: boolean; readonly rollback_supported?: boolean; readonly rollback_inverse_applied?: boolean; }
export interface DecisionTransitionContext { readonly tenant_id: string; readonly decision_tenant_id: string; readonly permission_granted: boolean; readonly approval_required?: boolean; readonly approval_present?: boolean; }
const executionTransitions: Readonly<Record<ExecutionStatus, readonly ExecutionStatus[]>> = { planned: ['pending_approval', 'queued', 'cancelled'], pending_approval: ['queued', 'cancelled'], queued: ['running', 'cancelled'], running: ['partially_completed', 'completed', 'failed', 'cancelled'], partially_completed: ['running', 'completed', 'failed', 'cancelled'], completed: ['rolled_back'], failed: ['rolled_back'], cancelled: [], rolled_back: [] };
const decisionTransitions: Readonly<Record<DecisionStatus, readonly DecisionStatus[]>> = { draft: ['pending_approval', 'approved', 'rejected', 'deferred'], pending_approval: ['approved', 'rejected', 'deferred'], approved: ['executed'], rejected: [], deferred: ['pending_approval', 'rejected'], executed: [] };
function fail(code: RuntimeTransitionErrorCode, message: string): never { throw new ActionRuntimeTransitionError(code, message); }
export function transitionDecision(current: DecisionStatus, next: DecisionStatus, context: DecisionTransitionContext): DecisionStatus { if (context.tenant_id !== context.decision_tenant_id) fail('tenant_mismatch', 'decision tenant does not match context'); if (!context.permission_granted) fail('unauthorized', 'decision transition is unauthorized'); if (next === 'approved' && context.approval_required && !context.approval_present) fail('approval_required', 'approval is required before decision approval'); if (!decisionTransitions[current].includes(next)) fail('invalid_transition', `cannot transition from ${current} to ${next}`); return next; }
export function transitionActionExecution(current: ExecutionStatus, next: ExecutionStatus, context: TransitionContext): ExecutionStatus { if (context.tenant_id !== context.execution_tenant_id) fail('tenant_mismatch', 'execution tenant does not match context'); if (!context.permission_granted) fail('unauthorized', 'execution transition is unauthorized'); if (!context.capability_ready) fail('capability_denied', 'capability is not ready'); if (!context.consent_valid || !context.policy_allowed) fail('consent_or_policy_required', 'valid consent and allowed policy are required'); if (context.approval_required && !context.approval_present && (next === 'queued' || next === 'running')) fail('approval_required', 'approval is required before execution'); if (!executionTransitions[current].includes(next)) fail('invalid_transition', `cannot transition from ${current} to ${next}`); if (next === 'rolled_back' && context.rollback_inverse_applied !== true) fail('fake_rollback', 'rollback cannot be marked complete without applying the inverse'); return next; }
export type ActionRuntimeSourceLinks = { decision?: Decision | GraphDecisionRecord; recommendation_evidence?: RecommendationEvidence; mutation?: MutationRecord; audit?: SecurityAuditEvent; policy?: PolicyDecision; ai_invocation?: AIInvocationObserved };
