/**
 * Aether — Connector Taxonomy (TypeScript)
 *
 * Two sections, two sources:
 *
 *   1. DESCRIPTOR TAXONOMY (below the header) — a stable compatibility mirror
 *      of the connector-descriptor enums in
 *        Backend Architecture/aether-backend/services/integrations/connectors/base.py
 *      (ConnectorClass, ConnectorRole, ImplementationStatus, ...) plus the
 *      provider-corpus intelligence-source coverage shape. Consumed via the
 *      @aether/shared barrel; reproduced verbatim by the generator.
 *
 *   2. PROVIDER / CATEGORY MIRROR (generated) — a pure TypeScript mirror of the
 *      unified integration catalog derived from
 *        Backend Architecture/aether-backend/shared/integration_contracts/catalog.py
 *      (ALL_MANIFESTS four-group union: connectors / ad-platforms /
 *      payment-rails / deferred-credit-bureaus) and
 *        Backend Architecture/aether-backend/shared/integration_contracts/experience.py
 *      (customer-facing experience categories). Keep it in step by running the
 *      generator — never by hand-editing this file.
 *
 * DO NOT EDIT — generated by python scripts/generate_connector_taxonomy.py
 * Regenerate from the repository root (shared environment):
 *   python scripts/generate_connector_taxonomy.py
 */

// ── Connector class ────────────────────────────────────────────────────────────

export type ConnectorClass =
  | "olympus_provider"
  | "tenant_byod_data"
  | "byok_gateway"
  | "action_notifier"
  | "dual_role";

export const ConnectorClass = {
  OLYMPUS_PROVIDER: "olympus_provider" as const,
  TENANT_BYOD_DATA: "tenant_byod_data" as const,
  BYOK_GATEWAY: "byok_gateway" as const,
  ACTION_NOTIFIER: "action_notifier" as const,
  DUAL_ROLE: "dual_role" as const,
} satisfies Record<string, ConnectorClass>;

// ── Connector role ─────────────────────────────────────────────────────────────

export type ConnectorRole =
  | "data_ingestion"
  | "action_delivery"
  | "credential_gateway"
  | "enrichment_provider"
  | "webhook_receiver"
  | "sync_source"
  | "realtime_stream"
  | "batch_backfill"
  | "query_execution"
  | "warehouse_datashare"
  | "dual_role";

export const ConnectorRole = {
  DATA_INGESTION: "data_ingestion" as const,
  ACTION_DELIVERY: "action_delivery" as const,
  CREDENTIAL_GATEWAY: "credential_gateway" as const,
  ENRICHMENT_PROVIDER: "enrichment_provider" as const,
  WEBHOOK_RECEIVER: "webhook_receiver" as const,
  SYNC_SOURCE: "sync_source" as const,
  REALTIME_STREAM: "realtime_stream" as const,
  BATCH_BACKFILL: "batch_backfill" as const,
  QUERY_EXECUTION: "query_execution" as const,
  WAREHOUSE_DATASHARE: "warehouse_datashare" as const,
  DUAL_ROLE: "dual_role" as const,
} satisfies Record<string, ConnectorRole>;

// ── Data flow direction ────────────────────────────────────────────────────────

export type DataFlowDirection = "inbound" | "outbound" | "bidirectional" | "none";

export const DataFlowDirection = {
  INBOUND: "inbound" as const,
  OUTBOUND: "outbound" as const,
  BIDIRECTIONAL: "bidirectional" as const,
  NONE: "none" as const,
} satisfies Record<string, DataFlowDirection>;

// ── Lake write policy ──────────────────────────────────────────────────────────

export type LakeWritePolicy =
  | "never"
  | "tenant_only"
  | "olympus_baseline_eligible"
  | "olympus_baseline_allowed"
  | "quarantine_only";

export const LakeWritePolicy = {
  NEVER: "never" as const,
  TENANT_ONLY: "tenant_only" as const,
  OLYMPUS_BASELINE_ELIGIBLE: "olympus_baseline_eligible" as const,
  OLYMPUS_BASELINE_ALLOWED: "olympus_baseline_allowed" as const,
  QUARANTINE_ONLY: "quarantine_only" as const,
} satisfies Record<string, LakeWritePolicy>;

// ── Graph write policy ─────────────────────────────────────────────────────────

export type GraphWritePolicy =
  | "none"
  | "tenant_graph_only"
  | "tenant_graph_and_aggregate_eligible"
  | "olympus_graph_allowed"
  | "quarantine_only";

export const GraphWritePolicy = {
  NONE: "none" as const,
  TENANT_GRAPH_ONLY: "tenant_graph_only" as const,
  TENANT_GRAPH_AND_AGGREGATE_ELIGIBLE: "tenant_graph_and_aggregate_eligible" as const,
  OLYMPUS_GRAPH_ALLOWED: "olympus_graph_allowed" as const,
  QUARANTINE_ONLY: "quarantine_only" as const,
} satisfies Record<string, GraphWritePolicy>;

// ── Model training eligibility ─────────────────────────────────────────────────

export type ModelTrainingEligibility =
  | "never"
  | "tenant_only"
  | "aggregate_only"
  | "olympus_allowed"
  | "compliance_review_required";

export const ModelTrainingEligibility = {
  NEVER: "never" as const,
  TENANT_ONLY: "tenant_only" as const,
  AGGREGATE_ONLY: "aggregate_only" as const,
  OLYMPUS_ALLOWED: "olympus_allowed" as const,
  COMPLIANCE_REVIEW_REQUIRED: "compliance_review_required" as const,
} satisfies Record<string, ModelTrainingEligibility>;

// ── Implementation status ──────────────────────────────────────────────────────

export type ImplementationStatus =
  | "mocked_local"
  | "scaffolded"
  | "production_shaped"
  | "credential_gated"
  | "provider_live"
  | "warehouse_datashare_ready"
  | "staging_validation_required"
  | "disabled_compliance_review"
  | "deprecated";

export const ImplementationStatus = {
  MOCKED_LOCAL: "mocked_local" as const,
  SCAFFOLDED: "scaffolded" as const,
  PRODUCTION_SHAPED: "production_shaped" as const,
  CREDENTIAL_GATED: "credential_gated" as const,
  PROVIDER_LIVE: "provider_live" as const,
  WAREHOUSE_DATASHARE_READY: "warehouse_datashare_ready" as const,
  STAGING_VALIDATION_REQUIRED: "staging_validation_required" as const,
  DISABLED_COMPLIANCE_REVIEW: "disabled_compliance_review" as const,
  DEPRECATED: "deprecated" as const,
} satisfies Record<string, ImplementationStatus>;

// ── Priority phase ─────────────────────────────────────────────────────────────

export type PriorityPhase =
  | "phase_1_foundation"
  | "phase_2_enrichment"
  | "phase_3_depth"
  | "not_scheduled";

export const PriorityPhase = {
  PHASE_1_FOUNDATION: "phase_1_foundation" as const,
  PHASE_2_ENRICHMENT: "phase_2_enrichment" as const,
  PHASE_3_DEPTH: "phase_3_depth" as const,
  NOT_SCHEDULED: "not_scheduled" as const,
} satisfies Record<string, PriorityPhase>;

// ── Risk tier ──────────────────────────────────────────────────────────────────

export type RiskTier = "low" | "medium" | "high" | "restricted";

export const RiskTier = {
  LOW: "low" as const,
  MEDIUM: "medium" as const,
  HIGH: "high" as const,
  RESTRICTED: "restricted" as const,
} satisfies Record<string, RiskTier>;

// ── Intelligence source coverage ───────────────────────────────────────────────

export type IntelligenceSourceMode =
  | "baseline_only"
  | "baseline_plus_tenant_connector"
  | "baseline_plus_sdk_live"
  | "baseline_plus_tenant_connector_plus_sdk_live";

export interface IntelligenceSourceCoverage {
  source_mode: IntelligenceSourceMode;
  baseline_coverage: number;
  connector_coverage: number;
  sdk_live_coverage: number;
  identity_confidence: number;
  data_freshness_score: number;
  model_confidence: number;
  last_refreshed_at: string | null;
}


// ════════════════════════════════════════════════════════════════════
// Provider / category mirror — GENERATED from the Python catalog
// Source of truth: shared/integration_contracts/catalog.py (ALL_MANIFESTS
// four-group union) + shared/integration_contracts/experience.py.
// Regenerate: python scripts/generate_connector_taxonomy.py
// ════════════════════════════════════════════════════════════════════

export type CatalogGroupId =
  | 'connectors' | 'ad_platforms' | 'payment_rails' | 'deferred_credit_bureaus';

export const CATALOG_GROUP_ORDER = [
  'connectors',
  'ad_platforms',
  'payment_rails',
  'deferred_credit_bureaus',
] as const;

// Families in the connectors group (catalog order, 21).
export const CONNECTOR_FAMILIES = [
  'slack' as const,
  'webhook' as const,
  'shopify' as const,
  'stripe' as const,
  'hubspot' as const,
  'salesforce' as const,
  'klaviyo' as const,
  'segment' as const,
  'posthog' as const,
  'ga4' as const,
  'jira' as const,
  'linear' as const,
  'zendesk' as const,
  'intercom' as const,
  'dune' as const,
  'sendgrid' as const,
  'customerio' as const,
  'mailchimp' as const,
  'postmark' as const,
  'iterable' as const,
  'braze' as const,
] as const;

export type ConnectorFamily = (typeof CONNECTOR_FAMILIES)[number];

export const CONNECTOR_FAMILIES_COUNT = 21 as const;

// Families in the ad_platforms group (catalog order, 7).
export const AD_PLATFORM_FAMILIES = [
  'google_ads' as const,
  'meta_ads' as const,
  'tiktok_ads' as const,
  'linkedin_ads' as const,
  'x_ads' as const,
  'reddit_ads' as const,
  'microsoft_ads' as const,
] as const;

export type AdPlatformFamily = (typeof AD_PLATFORM_FAMILIES)[number];

export const AD_PLATFORM_FAMILIES_COUNT = 7 as const;

// Families in the payment_rails group (catalog order, 5).
export const PAYMENT_RAIL_FAMILIES = [
  'privy' as const,
  'stripe' as const,
  'coinbase' as const,
  'moonpay' as const,
  'bridge' as const,
] as const;

export type PaymentRailFamily = (typeof PAYMENT_RAIL_FAMILIES)[number];

export const PAYMENT_RAIL_FAMILIES_COUNT = 5 as const;

// Families in the deferred_credit_bureaus group (catalog order, 3).
export const DEFERRED_CREDIT_BUREAU_FAMILIES = [
  'experian' as const,
  'equifax' as const,
  'transunion' as const,
] as const;

export type DeferredCreditBureauFamily = (typeof DEFERRED_CREDIT_BUREAU_FAMILIES)[number];

export const DEFERRED_CREDIT_BUREAU_FAMILIES_COUNT = 3 as const;

export const ALL_CATALOG_FAMILIES = [
  'slack' as const,
  'webhook' as const,
  'shopify' as const,
  'stripe' as const,
  'hubspot' as const,
  'salesforce' as const,
  'klaviyo' as const,
  'segment' as const,
  'posthog' as const,
  'ga4' as const,
  'jira' as const,
  'linear' as const,
  'zendesk' as const,
  'intercom' as const,
  'dune' as const,
  'sendgrid' as const,
  'customerio' as const,
  'mailchimp' as const,
  'postmark' as const,
  'iterable' as const,
  'braze' as const,
  'google_ads' as const,
  'meta_ads' as const,
  'tiktok_ads' as const,
  'linkedin_ads' as const,
  'x_ads' as const,
  'reddit_ads' as const,
  'microsoft_ads' as const,
  'privy' as const,
  'stripe' as const,
  'coinbase' as const,
  'moonpay' as const,
  'bridge' as const,
  'experian' as const,
  'equifax' as const,
  'transunion' as const,
] as const;

export const ALL_CATALOG_FAMILIES_COUNT = 36 as const;

export const CATALOG_GROUPS = [
  {
    id: 'connectors',
    product: 'ingestion',
    capability: 'connector',
    familyConst: 'CONNECTOR_FAMILIES',
    count: 21,
    families: ['slack', 'webhook', 'shopify', 'stripe', 'hubspot', 'salesforce', 'klaviyo', 'segment', 'posthog', 'ga4', 'jira', 'linear', 'zendesk', 'intercom', 'dune', 'sendgrid', 'customerio', 'mailchimp', 'postmark', 'iterable', 'braze'],
    categories: ['billing', 'commerce', 'crm', 'marketing', 'messaging', 'product_analytics', 'project', 'support', 'webhook'],
  },
  {
    id: 'ad_platforms',
    product: 'ads',
    capability: 'metrics',
    familyConst: 'AD_PLATFORM_FAMILIES',
    count: 7,
    families: ['google_ads', 'meta_ads', 'tiktok_ads', 'linkedin_ads', 'x_ads', 'reddit_ads', 'microsoft_ads'],
    categories: ['ad_platform'],
  },
  {
    id: 'payment_rails',
    product: 'payment_rails',
    capability: 'observe',
    familyConst: 'PAYMENT_RAIL_FAMILIES',
    count: 5,
    families: ['privy', 'stripe', 'coinbase', 'moonpay', 'bridge'],
    categories: ['payments'],
  },
  {
    id: 'deferred_credit_bureaus',
    product: 'credit',
    capability: 'report',
    familyConst: 'DEFERRED_CREDIT_BUREAU_FAMILIES',
    count: 3,
    families: ['experian', 'equifax', 'transunion'],
    categories: ['credit_bureau'],
  },
] as const;

export type CatalogProviderFamily = (typeof CONNECTOR_FAMILIES)[number] | (typeof AD_PLATFORM_FAMILIES)[number] | (typeof PAYMENT_RAIL_FAMILIES)[number] | (typeof DEFERRED_CREDIT_BUREAU_FAMILIES)[number];

export const CATALOG_CATEGORIES = [
  'ad_platform',
  'billing',
  'commerce',
  'credit_bureau',
  'crm',
  'marketing',
  'messaging',
  'payments',
  'product_analytics',
  'project',
  'support',
  'webhook',
] as const;

export type CatalogCategory = (typeof CATALOG_CATEGORIES)[number];

// CredentialReadiness ladder states actually present across ALL_MANIFESTS (honest mirror, never a parallel ladder).
export const CATALOG_READINESS_STATES_PRESENT = [
  'credential_waiting' as const,
  'scaffolded' as const,
] as const;

export const CATALOG_ENTRIES = [
  {
    key: 'slack.ingestion.connector',
    family: 'slack',
    product: 'ingestion',
    capability: 'connector',
    display_name: 'Slack',
    category: 'messaging',
    experience_category: 'work_operations',
    readiness_state: 'credential_waiting',
    readiness_level: 3,
    tenant_self_service: true,
    environments: ['local', 'integration'],
    authentication: 'webhook_only',
    accounts_discovery: false,
    accounts_selection_required: false,
    webhooks_supported: true,
    sync_incremental: false,
    sync_initial_backfill: false,
  },
  {
    key: 'webhook.ingestion.connector',
    family: 'webhook',
    product: 'ingestion',
    capability: 'connector',
    display_name: 'Generic Signed Webhook',
    category: 'webhook',
    experience_category: 'analytics_behavior',
    readiness_state: 'credential_waiting',
    readiness_level: 3,
    tenant_self_service: true,
    environments: ['local', 'integration'],
    authentication: 'webhook_only',
    accounts_discovery: false,
    accounts_selection_required: false,
    webhooks_supported: true,
    sync_incremental: false,
    sync_initial_backfill: false,
  },
  {
    key: 'shopify.ingestion.connector',
    family: 'shopify',
    product: 'ingestion',
    capability: 'connector',
    display_name: 'Shopify',
    category: 'commerce',
    experience_category: 'commerce_revenue',
    readiness_state: 'credential_waiting',
    readiness_level: 3,
    tenant_self_service: true,
    environments: ['local', 'integration'],
    authentication: 'api_key',
    accounts_discovery: false,
    accounts_selection_required: false,
    webhooks_supported: true,
    sync_incremental: true,
    sync_initial_backfill: false,
  },
  {
    key: 'stripe.ingestion.connector',
    family: 'stripe',
    product: 'ingestion',
    capability: 'connector',
    display_name: 'Stripe (ingestion)',
    category: 'billing',
    experience_category: 'commerce_revenue',
    readiness_state: 'credential_waiting',
    readiness_level: 3,
    tenant_self_service: true,
    environments: ['local', 'integration'],
    authentication: 'webhook_only',
    accounts_discovery: false,
    accounts_selection_required: false,
    webhooks_supported: true,
    sync_incremental: false,
    sync_initial_backfill: false,
  },
  {
    key: 'hubspot.ingestion.connector',
    family: 'hubspot',
    product: 'ingestion',
    capability: 'connector',
    display_name: 'HubSpot',
    category: 'crm',
    experience_category: 'crm_customer',
    readiness_state: 'credential_waiting',
    readiness_level: 3,
    tenant_self_service: true,
    environments: ['local', 'integration'],
    authentication: 'api_key',
    accounts_discovery: false,
    accounts_selection_required: false,
    webhooks_supported: true,
    sync_incremental: true,
    sync_initial_backfill: false,
  },
  {
    key: 'salesforce.ingestion.connector',
    family: 'salesforce',
    product: 'ingestion',
    capability: 'connector',
    display_name: 'Salesforce',
    category: 'crm',
    experience_category: 'crm_customer',
    readiness_state: 'credential_waiting',
    readiness_level: 3,
    tenant_self_service: true,
    environments: ['local', 'integration'],
    authentication: 'api_key',
    accounts_discovery: false,
    accounts_selection_required: false,
    webhooks_supported: false,
    sync_incremental: true,
    sync_initial_backfill: false,
  },
  {
    key: 'klaviyo.ingestion.connector',
    family: 'klaviyo',
    product: 'ingestion',
    capability: 'connector',
    display_name: 'Klaviyo',
    category: 'marketing',
    experience_category: 'communications_lifecycle',
    readiness_state: 'credential_waiting',
    readiness_level: 3,
    tenant_self_service: true,
    environments: ['local', 'integration'],
    authentication: 'api_key',
    accounts_discovery: true,
    accounts_selection_required: false,
    webhooks_supported: true,
    sync_incremental: true,
    sync_initial_backfill: true,
  },
  {
    key: 'segment.ingestion.connector',
    family: 'segment',
    product: 'ingestion',
    capability: 'connector',
    display_name: 'Segment',
    category: 'product_analytics',
    experience_category: 'analytics_behavior',
    readiness_state: 'credential_waiting',
    readiness_level: 3,
    tenant_self_service: true,
    environments: ['local', 'integration'],
    authentication: 'webhook_only',
    accounts_discovery: false,
    accounts_selection_required: false,
    webhooks_supported: true,
    sync_incremental: false,
    sync_initial_backfill: false,
  },
  {
    key: 'posthog.ingestion.connector',
    family: 'posthog',
    product: 'ingestion',
    capability: 'connector',
    display_name: 'PostHog',
    category: 'product_analytics',
    experience_category: 'analytics_behavior',
    readiness_state: 'credential_waiting',
    readiness_level: 3,
    tenant_self_service: true,
    environments: ['local', 'integration'],
    authentication: 'api_key',
    accounts_discovery: false,
    accounts_selection_required: false,
    webhooks_supported: true,
    sync_incremental: true,
    sync_initial_backfill: false,
  },
  {
    key: 'ga4.ingestion.connector',
    family: 'ga4',
    product: 'ingestion',
    capability: 'connector',
    display_name: 'Google Analytics 4',
    category: 'product_analytics',
    experience_category: 'analytics_behavior',
    readiness_state: 'credential_waiting',
    readiness_level: 3,
    tenant_self_service: true,
    environments: ['local', 'integration'],
    authentication: 'api_key',
    accounts_discovery: false,
    accounts_selection_required: false,
    webhooks_supported: false,
    sync_incremental: true,
    sync_initial_backfill: false,
  },
  {
    key: 'jira.ingestion.connector',
    family: 'jira',
    product: 'ingestion',
    capability: 'connector',
    display_name: 'Jira',
    category: 'project',
    experience_category: 'work_operations',
    readiness_state: 'credential_waiting',
    readiness_level: 3,
    tenant_self_service: true,
    environments: ['local', 'integration'],
    authentication: 'api_key',
    accounts_discovery: false,
    accounts_selection_required: false,
    webhooks_supported: true,
    sync_incremental: true,
    sync_initial_backfill: false,
  },
  {
    key: 'linear.ingestion.connector',
    family: 'linear',
    product: 'ingestion',
    capability: 'connector',
    display_name: 'Linear',
    category: 'project',
    experience_category: 'work_operations',
    readiness_state: 'credential_waiting',
    readiness_level: 3,
    tenant_self_service: true,
    environments: ['local', 'integration'],
    authentication: 'webhook_only',
    accounts_discovery: false,
    accounts_selection_required: false,
    webhooks_supported: true,
    sync_incremental: false,
    sync_initial_backfill: false,
  },
  {
    key: 'zendesk.ingestion.connector',
    family: 'zendesk',
    product: 'ingestion',
    capability: 'connector',
    display_name: 'Zendesk',
    category: 'support',
    experience_category: 'customer_support',
    readiness_state: 'credential_waiting',
    readiness_level: 3,
    tenant_self_service: true,
    environments: ['local', 'integration'],
    authentication: 'api_key',
    accounts_discovery: false,
    accounts_selection_required: false,
    webhooks_supported: true,
    sync_incremental: true,
    sync_initial_backfill: false,
  },
  {
    key: 'intercom.ingestion.connector',
    family: 'intercom',
    product: 'ingestion',
    capability: 'connector',
    display_name: 'Intercom',
    category: 'support',
    experience_category: 'customer_support',
    readiness_state: 'credential_waiting',
    readiness_level: 3,
    tenant_self_service: true,
    environments: ['local', 'integration'],
    authentication: 'api_key',
    accounts_discovery: false,
    accounts_selection_required: false,
    webhooks_supported: true,
    sync_incremental: true,
    sync_initial_backfill: false,
  },
  {
    key: 'dune.ingestion.connector',
    family: 'dune',
    product: 'ingestion',
    capability: 'connector',
    display_name: 'Dune Analytics',
    category: 'product_analytics',
    experience_category: 'analytics_behavior',
    readiness_state: 'credential_waiting',
    readiness_level: 3,
    tenant_self_service: true,
    environments: ['local', 'integration'],
    authentication: 'api_key',
    accounts_discovery: false,
    accounts_selection_required: false,
    webhooks_supported: false,
    sync_incremental: true,
    sync_initial_backfill: false,
  },
  {
    key: 'sendgrid.ingestion.connector',
    family: 'sendgrid',
    product: 'ingestion',
    capability: 'connector',
    display_name: 'SendGrid',
    category: 'marketing',
    experience_category: 'communications_lifecycle',
    readiness_state: 'credential_waiting',
    readiness_level: 3,
    tenant_self_service: true,
    environments: ['local', 'integration'],
    authentication: 'webhook_only',
    accounts_discovery: false,
    accounts_selection_required: false,
    webhooks_supported: true,
    sync_incremental: false,
    sync_initial_backfill: false,
  },
  {
    key: 'customerio.ingestion.connector',
    family: 'customerio',
    product: 'ingestion',
    capability: 'connector',
    display_name: 'Customer.io',
    category: 'marketing',
    experience_category: 'communications_lifecycle',
    readiness_state: 'credential_waiting',
    readiness_level: 3,
    tenant_self_service: true,
    environments: ['local', 'integration'],
    authentication: 'webhook_only',
    accounts_discovery: false,
    accounts_selection_required: false,
    webhooks_supported: true,
    sync_incremental: false,
    sync_initial_backfill: false,
  },
  {
    key: 'mailchimp.ingestion.connector',
    family: 'mailchimp',
    product: 'ingestion',
    capability: 'connector',
    display_name: 'Mailchimp',
    category: 'marketing',
    experience_category: 'communications_lifecycle',
    readiness_state: 'credential_waiting',
    readiness_level: 3,
    tenant_self_service: true,
    environments: ['local', 'integration'],
    authentication: 'webhook_only',
    accounts_discovery: false,
    accounts_selection_required: false,
    webhooks_supported: true,
    sync_incremental: false,
    sync_initial_backfill: false,
  },
  {
    key: 'postmark.ingestion.connector',
    family: 'postmark',
    product: 'ingestion',
    capability: 'connector',
    display_name: 'Postmark',
    category: 'marketing',
    experience_category: 'communications_lifecycle',
    readiness_state: 'credential_waiting',
    readiness_level: 3,
    tenant_self_service: true,
    environments: ['local', 'integration'],
    authentication: 'webhook_only',
    accounts_discovery: false,
    accounts_selection_required: false,
    webhooks_supported: true,
    sync_incremental: false,
    sync_initial_backfill: false,
  },
  {
    key: 'iterable.ingestion.connector',
    family: 'iterable',
    product: 'ingestion',
    capability: 'connector',
    display_name: 'Iterable',
    category: 'marketing',
    experience_category: 'communications_lifecycle',
    readiness_state: 'credential_waiting',
    readiness_level: 3,
    tenant_self_service: true,
    environments: ['local', 'integration'],
    authentication: 'api_key',
    accounts_discovery: false,
    accounts_selection_required: false,
    webhooks_supported: true,
    sync_incremental: true,
    sync_initial_backfill: true,
  },
  {
    key: 'braze.ingestion.connector',
    family: 'braze',
    product: 'ingestion',
    capability: 'connector',
    display_name: 'Braze',
    category: 'marketing',
    experience_category: 'communications_lifecycle',
    readiness_state: 'credential_waiting',
    readiness_level: 3,
    tenant_self_service: true,
    environments: ['local', 'integration'],
    authentication: 'api_key',
    accounts_discovery: false,
    accounts_selection_required: false,
    webhooks_supported: true,
    sync_incremental: true,
    sync_initial_backfill: true,
  },
  {
    key: 'google_ads.ads.metrics',
    family: 'google_ads',
    product: 'ads',
    capability: 'metrics',
    display_name: 'Google Ads',
    category: 'ad_platform',
    experience_category: 'advertising_campaigns',
    readiness_state: 'credential_waiting',
    readiness_level: 3,
    tenant_self_service: true,
    environments: ['local', 'integration'],
    authentication: 'api_key',
    accounts_discovery: false,
    accounts_selection_required: false,
    webhooks_supported: false,
    sync_incremental: true,
    sync_initial_backfill: true,
  },
  {
    key: 'meta_ads.ads.metrics',
    family: 'meta_ads',
    product: 'ads',
    capability: 'metrics',
    display_name: 'Meta Ads',
    category: 'ad_platform',
    experience_category: 'advertising_campaigns',
    readiness_state: 'credential_waiting',
    readiness_level: 3,
    tenant_self_service: true,
    environments: ['local', 'integration'],
    authentication: 'api_key',
    accounts_discovery: false,
    accounts_selection_required: false,
    webhooks_supported: false,
    sync_incremental: true,
    sync_initial_backfill: true,
  },
  {
    key: 'tiktok_ads.ads.metrics',
    family: 'tiktok_ads',
    product: 'ads',
    capability: 'metrics',
    display_name: 'TikTok Ads',
    category: 'ad_platform',
    experience_category: 'advertising_campaigns',
    readiness_state: 'credential_waiting',
    readiness_level: 3,
    tenant_self_service: true,
    environments: ['local', 'integration'],
    authentication: 'api_key',
    accounts_discovery: false,
    accounts_selection_required: false,
    webhooks_supported: false,
    sync_incremental: true,
    sync_initial_backfill: true,
  },
  {
    key: 'linkedin_ads.ads.metrics',
    family: 'linkedin_ads',
    product: 'ads',
    capability: 'metrics',
    display_name: 'LinkedIn Ads',
    category: 'ad_platform',
    experience_category: 'advertising_campaigns',
    readiness_state: 'credential_waiting',
    readiness_level: 3,
    tenant_self_service: true,
    environments: ['local', 'integration'],
    authentication: 'api_key',
    accounts_discovery: false,
    accounts_selection_required: false,
    webhooks_supported: false,
    sync_incremental: true,
    sync_initial_backfill: true,
  },
  {
    key: 'x_ads.ads.metrics',
    family: 'x_ads',
    product: 'ads',
    capability: 'metrics',
    display_name: 'X (Twitter) Ads',
    category: 'ad_platform',
    experience_category: 'advertising_campaigns',
    readiness_state: 'credential_waiting',
    readiness_level: 3,
    tenant_self_service: true,
    environments: ['local', 'integration'],
    authentication: 'api_key',
    accounts_discovery: false,
    accounts_selection_required: false,
    webhooks_supported: false,
    sync_incremental: true,
    sync_initial_backfill: true,
  },
  {
    key: 'reddit_ads.ads.metrics',
    family: 'reddit_ads',
    product: 'ads',
    capability: 'metrics',
    display_name: 'Reddit Ads',
    category: 'ad_platform',
    experience_category: 'advertising_campaigns',
    readiness_state: 'credential_waiting',
    readiness_level: 3,
    tenant_self_service: true,
    environments: ['local', 'integration'],
    authentication: 'api_key',
    accounts_discovery: false,
    accounts_selection_required: false,
    webhooks_supported: false,
    sync_incremental: true,
    sync_initial_backfill: true,
  },
  {
    key: 'microsoft_ads.ads.metrics',
    family: 'microsoft_ads',
    product: 'ads',
    capability: 'metrics',
    display_name: 'Microsoft Advertising',
    category: 'ad_platform',
    experience_category: 'advertising_campaigns',
    readiness_state: 'credential_waiting',
    readiness_level: 3,
    tenant_self_service: true,
    environments: ['local', 'integration'],
    authentication: 'api_key',
    accounts_discovery: false,
    accounts_selection_required: false,
    webhooks_supported: false,
    sync_incremental: true,
    sync_initial_backfill: true,
  },
  {
    key: 'privy.payment_rails.observe',
    family: 'privy',
    product: 'payment_rails',
    capability: 'observe',
    display_name: 'Privy',
    category: 'payments',
    experience_category: 'commerce_revenue',
    readiness_state: 'credential_waiting',
    readiness_level: 3,
    tenant_self_service: true,
    environments: ['local', 'integration'],
    authentication: 'webhook_only',
    accounts_discovery: false,
    accounts_selection_required: false,
    webhooks_supported: true,
    sync_incremental: false,
    sync_initial_backfill: false,
  },
  {
    key: 'stripe.payment_rails.observe',
    family: 'stripe',
    product: 'payment_rails',
    capability: 'observe',
    display_name: 'Stripe crypto onramp',
    category: 'payments',
    experience_category: 'commerce_revenue',
    readiness_state: 'credential_waiting',
    readiness_level: 3,
    tenant_self_service: true,
    environments: ['local', 'integration'],
    authentication: 'webhook_only',
    accounts_discovery: false,
    accounts_selection_required: false,
    webhooks_supported: true,
    sync_incremental: false,
    sync_initial_backfill: false,
  },
  {
    key: 'coinbase.payment_rails.observe',
    family: 'coinbase',
    product: 'payment_rails',
    capability: 'observe',
    display_name: 'Coinbase onramp/offramp',
    category: 'payments',
    experience_category: 'commerce_revenue',
    readiness_state: 'credential_waiting',
    readiness_level: 3,
    tenant_self_service: true,
    environments: ['local', 'integration'],
    authentication: 'api_key',
    accounts_discovery: false,
    accounts_selection_required: false,
    webhooks_supported: true,
    sync_incremental: true,
    sync_initial_backfill: false,
  },
  {
    key: 'moonpay.payment_rails.observe',
    family: 'moonpay',
    product: 'payment_rails',
    capability: 'observe',
    display_name: 'MoonPay',
    category: 'payments',
    experience_category: 'commerce_revenue',
    readiness_state: 'credential_waiting',
    readiness_level: 3,
    tenant_self_service: true,
    environments: ['local', 'integration'],
    authentication: 'api_key',
    accounts_discovery: false,
    accounts_selection_required: false,
    webhooks_supported: true,
    sync_incremental: true,
    sync_initial_backfill: false,
  },
  {
    key: 'bridge.payment_rails.observe',
    family: 'bridge',
    product: 'payment_rails',
    capability: 'observe',
    display_name: 'Bridge',
    category: 'payments',
    experience_category: 'commerce_revenue',
    readiness_state: 'credential_waiting',
    readiness_level: 3,
    tenant_self_service: true,
    environments: ['local', 'integration'],
    authentication: 'api_key',
    accounts_discovery: false,
    accounts_selection_required: false,
    webhooks_supported: true,
    sync_incremental: true,
    sync_initial_backfill: false,
  },
  {
    key: 'experian.credit.report',
    family: 'experian',
    product: 'credit',
    capability: 'report',
    display_name: 'Experian',
    category: 'credit_bureau',
    experience_category: null,
    readiness_state: 'scaffolded',
    readiness_level: 1,
    tenant_self_service: false,
    environments: [],
    authentication: 'composite',
    accounts_discovery: false,
    accounts_selection_required: false,
    webhooks_supported: false,
    sync_incremental: false,
    sync_initial_backfill: false,
  },
  {
    key: 'equifax.credit.report',
    family: 'equifax',
    product: 'credit',
    capability: 'report',
    display_name: 'Equifax',
    category: 'credit_bureau',
    experience_category: null,
    readiness_state: 'scaffolded',
    readiness_level: 1,
    tenant_self_service: false,
    environments: [],
    authentication: 'composite',
    accounts_discovery: false,
    accounts_selection_required: false,
    webhooks_supported: false,
    sync_incremental: false,
    sync_initial_backfill: false,
  },
  {
    key: 'transunion.credit.report',
    family: 'transunion',
    product: 'credit',
    capability: 'report',
    display_name: 'TransUnion',
    category: 'credit_bureau',
    experience_category: null,
    readiness_state: 'scaffolded',
    readiness_level: 1,
    tenant_self_service: false,
    environments: [],
    authentication: 'composite',
    accounts_discovery: false,
    accounts_selection_required: false,
    webhooks_supported: false,
    sync_incremental: false,
    sync_initial_backfill: false,
  },
] as const;

export const CATALOG_ENTRIES_COUNT = 36 as const;

// Customer-facing experience categories (ADR-0010), presentation order.
export const EXPERIENCE_CATEGORY_ORDER = [
  'advertising_campaigns' as const,
  'commerce_revenue' as const,
  'crm_customer' as const,
  'communications_lifecycle' as const,
  'analytics_behavior' as const,
  'social_community' as const,
  'customer_support' as const,
  'work_operations' as const,
] as const;

export type ExperienceCategory = (typeof EXPERIENCE_CATEGORY_ORDER)[number];

// Derived experience → provider-family grouping over ALL_MANIFESTS. The 'None' bucket holds families that derive to no customer-facing experience.
export const EXPERIENCE_CATEGORY_FAMILIES = {
  'advertising_campaigns': ['google_ads', 'meta_ads', 'tiktok_ads', 'linkedin_ads', 'x_ads', 'reddit_ads', 'microsoft_ads'],
  'analytics_behavior': ['webhook', 'segment', 'posthog', 'ga4', 'dune'],
  'commerce_revenue': ['shopify', 'stripe', 'privy', 'stripe', 'coinbase', 'moonpay', 'bridge'],
  'communications_lifecycle': ['klaviyo', 'sendgrid', 'customerio', 'mailchimp', 'postmark', 'iterable', 'braze'],
  'crm_customer': ['hubspot', 'salesforce'],
  'customer_support': ['zendesk', 'intercom'],
  'work_operations': ['slack', 'jira', 'linear'],
  null: ['experian', 'equifax', 'transunion'],
} as const;

export interface CatalogEntryRow {
  key: string;
  family: string;
  product: string;
  capability: string;
  display_name: string;
  category: string;
  experience_category: string | null;
  readiness_state: string;
  readiness_level: number;
  tenant_self_service: boolean;
  environments: readonly string[];
  authentication: string;
  accounts_discovery: boolean;
  accounts_selection_required: boolean;
  webhooks_supported: boolean;
  sync_incremental: boolean;
  sync_initial_backfill: boolean;
}

export interface CatalogGroupMeta {
  id: CatalogGroupId;
  product: string;
  capability: string;
  familyConst: string;
  count: number;
  families: readonly string[];
  categories: readonly string[];
}

