/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: {
          base: 'var(--color-surface-base)',
          raised: 'var(--color-surface-raised)',
          overlay: 'var(--color-surface-overlay)',
          sunken: 'var(--color-surface-sunken)',
        },
        border: {
          default: 'var(--color-border-default)',
          subtle: 'var(--color-border-subtle)',
          focus: 'var(--color-border-focus)',
        },
        text: {
          primary: 'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          muted: 'var(--color-text-muted)',
          inverse: 'var(--color-text-inverse)',
        },
        accent: {
          DEFAULT: 'var(--color-accent)',
          hover: 'var(--color-accent-hover)',
        },
        success: 'var(--color-success)',
        warning: 'var(--color-warning)',
        danger: 'var(--color-danger)',
        info: 'var(--color-info)',
        ctrl: {
          governance: 'var(--color-ctrl-governance)',
          char: 'var(--color-ctrl-char)',
          intake: 'var(--color-ctrl-intake)',
          gouf: 'var(--color-ctrl-gouf)',
          zeong: 'var(--color-ctrl-zeong)',
          triage: 'var(--color-ctrl-triage)',
          verification: 'var(--color-ctrl-verification)',
          commit: 'var(--color-ctrl-commit)',
          recovery: 'var(--color-ctrl-recovery)',
          chronicle: 'var(--color-ctrl-chronicle)',
          trigger: 'var(--color-ctrl-trigger)',
          relay: 'var(--color-ctrl-relay)',
        },
        chart: {
          1: 'var(--color-chart-1)',
          2: 'var(--color-chart-2)',
          3: 'var(--color-chart-3)',
          4: 'var(--color-chart-4)',
          5: 'var(--color-chart-5)',
          6: 'var(--color-chart-6)',
          7: 'var(--color-chart-7)',
          8: 'var(--color-chart-8)',
        },
        graph: {
          'trust-high': 'var(--color-graph-trust-high)',
          'trust-medium': 'var(--color-graph-trust-medium)',
          'trust-low': 'var(--color-graph-trust-low)',
          'risk-high': 'var(--color-graph-risk-high)',
          'risk-medium': 'var(--color-graph-risk-medium)',
          'risk-low': 'var(--color-graph-risk-low)',
          anomaly: 'var(--color-graph-anomaly)',
          selected: 'var(--color-graph-selected)',
          path: 'var(--color-graph-path)',
        },
      },
      fontFamily: {
        mono: ['JetBrains Mono', 'Fira Code', 'SF Mono', 'Consolas', 'ui-monospace', 'monospace'],
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
