"""
Aether — Olympus Provider Source Catalog

Canonical registry of all 30+ external provider sources in the Olympus corpus.
This is NOT tenant BYOD — it is Olympus Labs' controlled provider inventory.

Priority phases:
  PHASE_1_FOUNDATION  — Dune + public Web3 data + public CEX + prediction markets
  PHASE_2_ENRICHMENT  — Identity, social Web3, protocol, governance, developer
  PHASE_3_DEPTH       — Redundancy, historical depth, compliance-review sources

High-risk providers (Twitter/X, Reddit, Telegram, Discord) are set to
DISABLED_COMPLIANCE_REVIEW until legal/compliance gates exist.
"""
from __future__ import annotations

from typing import Dict, List

from services.integrations.connectors.base import (
    ConnectorClass,
    ConnectorRole,
    DataFlowDirection,
    LakeWritePolicy,
    GraphWritePolicy,
    ModelTrainingEligibility,
    ImplementationStatus,
    PriorityPhase,
    RiskTier,
)
from services.provider_catalog.models import (
    CostProfile,
    ChainExtractionPlan,
    DuneAccessMode,
    ExtractionProduct,
    ProviderSourceEntry,
    RateLimitProfile,
    SourceManifest,
)


# ═══════════════════════════════════════════════════════════════════════════
# COST PROFILES
# ═══════════════════════════════════════════════════════════════════════════

COST_PROFILES: Dict[str, CostProfile] = {
    "dune_api": CostProfile(
        cost_profile_id="dune_api",
        free_tier_available=True,
        free_tier_description="Community plan: limited executions/month",
        paid_tier_required_for_full_coverage=True,
        estimated_monthly_cost_low="$0",
        estimated_monthly_cost_high="$1000+",
        cost_driver="per_query_execution",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "dune_datashare": CostProfile(
        cost_profile_id="dune_datashare",
        free_tier_available=False,
        paid_tier_required_for_full_coverage=True,
        estimated_monthly_cost_low="$5000",
        estimated_monthly_cost_high="$50000+",
        cost_driver="enterprise_contract",
        requires_enterprise_contract=True,
        requires_commercial_use_review=True,
    ),
    "dune_sim": CostProfile(
        cost_profile_id="dune_sim",
        free_tier_available=False,
        paid_tier_required_for_full_coverage=True,
        estimated_monthly_cost_low="$500",
        estimated_monthly_cost_high="$5000+",
        cost_driver="per_request",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "defi_llama": CostProfile(
        cost_profile_id="defi_llama",
        free_tier_available=True,
        free_tier_description="Public API, no key required for most endpoints",
        paid_tier_required_for_full_coverage=False,
        estimated_monthly_cost_low="$0",
        estimated_monthly_cost_high="$0",
        cost_driver="free",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "coingecko": CostProfile(
        cost_profile_id="coingecko",
        free_tier_available=True,
        free_tier_description="50 calls/min free, Pro for higher limits",
        paid_tier_required_for_full_coverage=True,
        estimated_monthly_cost_low="$0",
        estimated_monthly_cost_high="$499",
        cost_driver="per_request",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "coinmarketcap": CostProfile(
        cost_profile_id="coinmarketcap",
        free_tier_available=True,
        free_tier_description="Basic free tier, limited endpoints",
        paid_tier_required_for_full_coverage=True,
        estimated_monthly_cost_low="$0",
        estimated_monthly_cost_high="$799",
        cost_driver="per_request",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "polymarket_gamma": CostProfile(
        cost_profile_id="polymarket_gamma",
        free_tier_available=True,
        free_tier_description="Public REST API, no auth required",
        paid_tier_required_for_full_coverage=False,
        estimated_monthly_cost_low="$0",
        estimated_monthly_cost_high="$0",
        cost_driver="free",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "polymarket_clob": CostProfile(
        cost_profile_id="polymarket_clob",
        free_tier_available=True,
        free_tier_description="API key required for CLOB access",
        paid_tier_required_for_full_coverage=False,
        estimated_monthly_cost_low="$0",
        estimated_monthly_cost_high="$0",
        cost_driver="free",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "kalshi": CostProfile(
        cost_profile_id="kalshi",
        free_tier_available=True,
        free_tier_description="Public endpoints available; account required for full access",
        paid_tier_required_for_full_coverage=True,
        estimated_monthly_cost_low="$0",
        estimated_monthly_cost_high="$100",
        cost_driver="per_request",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "metaculus": CostProfile(
        cost_profile_id="metaculus",
        free_tier_available=True,
        free_tier_description="Public API",
        paid_tier_required_for_full_coverage=False,
        estimated_monthly_cost_low="$0",
        estimated_monthly_cost_high="$0",
        cost_driver="free",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "manifold_markets": CostProfile(
        cost_profile_id="manifold_markets",
        free_tier_available=True,
        free_tier_description="Public API",
        paid_tier_required_for_full_coverage=False,
        estimated_monthly_cost_low="$0",
        estimated_monthly_cost_high="$0",
        cost_driver="free",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "binance_public": CostProfile(
        cost_profile_id="binance_public",
        free_tier_available=True,
        free_tier_description="Public endpoints: price, depth, klines, trades",
        paid_tier_required_for_full_coverage=False,
        estimated_monthly_cost_low="$0",
        estimated_monthly_cost_high="$0",
        cost_driver="free",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "coinbase_exchange": CostProfile(
        cost_profile_id="coinbase_exchange",
        free_tier_available=True,
        free_tier_description="Public market data endpoints",
        paid_tier_required_for_full_coverage=False,
        estimated_monthly_cost_low="$0",
        estimated_monthly_cost_high="$0",
        cost_driver="free",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "kraken": CostProfile(
        cost_profile_id="kraken",
        free_tier_available=True,
        free_tier_description="Public REST API for market data",
        paid_tier_required_for_full_coverage=False,
        estimated_monthly_cost_low="$0",
        estimated_monthly_cost_high="$0",
        cost_driver="free",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "okx": CostProfile(
        cost_profile_id="okx",
        free_tier_available=True,
        free_tier_description="Public market data API",
        paid_tier_required_for_full_coverage=False,
        estimated_monthly_cost_low="$0",
        estimated_monthly_cost_high="$0",
        cost_driver="free",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "bybit": CostProfile(
        cost_profile_id="bybit",
        free_tier_available=True,
        free_tier_description="Public REST API for market data",
        paid_tier_required_for_full_coverage=False,
        estimated_monthly_cost_low="$0",
        estimated_monthly_cost_high="$0",
        cost_driver="free",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "ccxt": CostProfile(
        cost_profile_id="ccxt",
        free_tier_available=True,
        free_tier_description="Open source library, exchange costs vary",
        paid_tier_required_for_full_coverage=False,
        estimated_monthly_cost_low="$0",
        estimated_monthly_cost_high="$500",
        cost_driver="per_exchange",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "etherscan": CostProfile(
        cost_profile_id="etherscan",
        free_tier_available=True,
        free_tier_description="5 calls/sec free, Pro for higher limits",
        paid_tier_required_for_full_coverage=True,
        estimated_monthly_cost_low="$0",
        estimated_monthly_cost_high="$299",
        cost_driver="per_request",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "the_graph": CostProfile(
        cost_profile_id="the_graph",
        free_tier_available=True,
        free_tier_description="Hosted service free for limited queries",
        paid_tier_required_for_full_coverage=True,
        estimated_monthly_cost_low="$0",
        estimated_monthly_cost_high="$500",
        cost_driver="per_query",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "flipside_crypto": CostProfile(
        cost_profile_id="flipside_crypto",
        free_tier_available=True,
        free_tier_description="Community free tier",
        paid_tier_required_for_full_coverage=True,
        estimated_monthly_cost_low="$0",
        estimated_monthly_cost_high="$2000",
        cost_driver="per_query",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "covalent_goldrush": CostProfile(
        cost_profile_id="covalent_goldrush",
        free_tier_available=True,
        free_tier_description="100 calls/day free",
        paid_tier_required_for_full_coverage=True,
        estimated_monthly_cost_low="$0",
        estimated_monthly_cost_high="$499",
        cost_driver="per_request",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "alchemy": CostProfile(
        cost_profile_id="alchemy",
        free_tier_available=True,
        free_tier_description="Free tier with compute units",
        paid_tier_required_for_full_coverage=True,
        estimated_monthly_cost_low="$0",
        estimated_monthly_cost_high="$999",
        cost_driver="per_compute_unit",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "moralis": CostProfile(
        cost_profile_id="moralis",
        free_tier_available=True,
        free_tier_description="Limited free tier",
        paid_tier_required_for_full_coverage=True,
        estimated_monthly_cost_low="$0",
        estimated_monthly_cost_high="$499",
        cost_driver="per_request",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "transpose": CostProfile(
        cost_profile_id="transpose",
        free_tier_available=True,
        free_tier_description="Limited free queries",
        paid_tier_required_for_full_coverage=True,
        estimated_monthly_cost_low="$0",
        estimated_monthly_cost_high="$500",
        cost_driver="per_query",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "solscan": CostProfile(
        cost_profile_id="solscan",
        free_tier_available=True,
        free_tier_description="Public API with rate limits",
        paid_tier_required_for_full_coverage=True,
        estimated_monthly_cost_low="$0",
        estimated_monthly_cost_high="$299",
        cost_driver="per_request",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "farcaster_neynar": CostProfile(
        cost_profile_id="farcaster_neynar",
        free_tier_available=True,
        free_tier_description="Neynar API free tier",
        paid_tier_required_for_full_coverage=True,
        estimated_monthly_cost_low="$0",
        estimated_monthly_cost_high="$499",
        cost_driver="per_request",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "lens_protocol": CostProfile(
        cost_profile_id="lens_protocol",
        free_tier_available=True,
        free_tier_description="Public GraphQL API",
        paid_tier_required_for_full_coverage=False,
        estimated_monthly_cost_low="$0",
        estimated_monthly_cost_high="$0",
        cost_driver="free",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "ens_public": CostProfile(
        cost_profile_id="ens_public",
        free_tier_available=True,
        free_tier_description="ENS public resolver + The Graph subgraph",
        paid_tier_required_for_full_coverage=False,
        estimated_monthly_cost_low="$0",
        estimated_monthly_cost_high="$50",
        cost_driver="free",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "snapshot": CostProfile(
        cost_profile_id="snapshot",
        free_tier_available=True,
        free_tier_description="Public GraphQL API",
        paid_tier_required_for_full_coverage=False,
        estimated_monthly_cost_low="$0",
        estimated_monthly_cost_high="$0",
        cost_driver="free",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "github_api": CostProfile(
        cost_profile_id="github_api",
        free_tier_available=True,
        free_tier_description="60 req/hr unauthenticated, 5000/hr with token",
        paid_tier_required_for_full_coverage=False,
        estimated_monthly_cost_low="$0",
        estimated_monthly_cost_high="$0",
        cost_driver="free",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "twitter_x": CostProfile(
        cost_profile_id="twitter_x",
        free_tier_available=False,
        paid_tier_required_for_full_coverage=True,
        estimated_monthly_cost_low="$100",
        estimated_monthly_cost_high="$5000+",
        cost_driver="per_request",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "reddit": CostProfile(
        cost_profile_id="reddit",
        free_tier_available=True,
        free_tier_description="OAuth app: 100 req/min",
        paid_tier_required_for_full_coverage=False,
        estimated_monthly_cost_low="$0",
        estimated_monthly_cost_high="$0",
        cost_driver="free",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "telegram_bot": CostProfile(
        cost_profile_id="telegram_bot",
        free_tier_available=True,
        free_tier_description="Bot API is free",
        paid_tier_required_for_full_coverage=False,
        estimated_monthly_cost_low="$0",
        estimated_monthly_cost_high="$0",
        cost_driver="free",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "discord_bot": CostProfile(
        cost_profile_id="discord_bot",
        free_tier_available=True,
        free_tier_description="Bot API is free",
        paid_tier_required_for_full_coverage=False,
        estimated_monthly_cost_low="$0",
        estimated_monthly_cost_high="$0",
        cost_driver="free",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "uniswap_subgraph": CostProfile(
        cost_profile_id="uniswap_subgraph",
        free_tier_available=True,
        free_tier_description="The Graph hosted service",
        paid_tier_required_for_full_coverage=True,
        estimated_monthly_cost_low="$0",
        estimated_monthly_cost_high="$500",
        cost_driver="per_query",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "aave_subgraph": CostProfile(
        cost_profile_id="aave_subgraph",
        free_tier_available=True,
        free_tier_description="The Graph hosted service",
        paid_tier_required_for_full_coverage=True,
        estimated_monthly_cost_low="$0",
        estimated_monthly_cost_high="$500",
        cost_driver="per_query",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "chainlink_price_feeds": CostProfile(
        cost_profile_id="chainlink_price_feeds",
        free_tier_available=True,
        free_tier_description="On-chain reads are free (gas cost only)",
        paid_tier_required_for_full_coverage=False,
        estimated_monthly_cost_low="$0",
        estimated_monthly_cost_high="$100",
        cost_driver="gas_cost",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "opensea": CostProfile(
        cost_profile_id="opensea",
        free_tier_available=True,
        free_tier_description="Limited free tier with API key",
        paid_tier_required_for_full_coverage=True,
        estimated_monthly_cost_low="$0",
        estimated_monthly_cost_high="$999",
        cost_driver="per_request",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "reservoir": CostProfile(
        cost_profile_id="reservoir",
        free_tier_available=True,
        free_tier_description="Public API with rate limits",
        paid_tier_required_for_full_coverage=True,
        estimated_monthly_cost_low="$0",
        estimated_monthly_cost_high="$499",
        cost_driver="per_request",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
    "token_terminal": CostProfile(
        cost_profile_id="token_terminal",
        free_tier_available=True,
        free_tier_description="Limited public data",
        paid_tier_required_for_full_coverage=True,
        estimated_monthly_cost_low="$0",
        estimated_monthly_cost_high="$999",
        cost_driver="per_request",
        requires_enterprise_contract=False,
        requires_commercial_use_review=True,
    ),
}


# ═══════════════════════════════════════════════════════════════════════════
# RATE LIMIT PROFILES
# ═══════════════════════════════════════════════════════════════════════════

RATE_LIMIT_PROFILES: Dict[str, RateLimitProfile] = {
    "dune_api": RateLimitProfile(
        rate_limit_profile_id="dune_api",
        free_rate_limit="5 concurrent executions",
        paid_rate_limit="20+ concurrent executions",
        burst_limit="per plan tier",
        requires_key=True,
        requires_oauth=False,
    ),
    "dune_datashare": RateLimitProfile(
        rate_limit_profile_id="dune_datashare",
        paid_rate_limit="warehouse-throughput based",
        warehouse_cost_driver="Snowflake/BigQuery compute credits",
        requires_key=False,
        requires_oauth=False,
    ),
    "dune_sim": RateLimitProfile(
        rate_limit_profile_id="dune_sim",
        paid_rate_limit="100-1000 req/min depending on plan",
        requires_key=True,
        requires_oauth=False,
    ),
    "defi_llama": RateLimitProfile(
        rate_limit_profile_id="defi_llama",
        free_rate_limit="~300 req/min",
        requires_key=False,
        requires_oauth=False,
    ),
    "coingecko": RateLimitProfile(
        rate_limit_profile_id="coingecko",
        free_rate_limit="50 req/min",
        paid_rate_limit="500 req/min (Pro)",
        requires_key=True,
        requires_oauth=False,
    ),
    "binance_public": RateLimitProfile(
        rate_limit_profile_id="binance_public",
        free_rate_limit="1200 req/min weight",
        daily_limit="unlimited",
        requires_key=False,
        requires_oauth=False,
    ),
    "etherscan": RateLimitProfile(
        rate_limit_profile_id="etherscan",
        free_rate_limit="5 req/sec",
        paid_rate_limit="10+ req/sec (Pro)",
        daily_limit="100k requests/day (free)",
        requires_key=True,
        requires_oauth=False,
    ),
    "the_graph": RateLimitProfile(
        rate_limit_profile_id="the_graph",
        free_rate_limit="limited monthly queries",
        paid_rate_limit="GRT-based indexer fees",
        requires_key=True,
        requires_oauth=False,
    ),
    "polymarket_gamma": RateLimitProfile(
        rate_limit_profile_id="polymarket_gamma",
        free_rate_limit="100 req/min",
        requires_key=False,
        requires_oauth=False,
    ),
    "kalshi": RateLimitProfile(
        rate_limit_profile_id="kalshi",
        free_rate_limit="10 req/sec",
        requires_key=True,
        requires_oauth=False,
    ),
    "github_api": RateLimitProfile(
        rate_limit_profile_id="github_api",
        free_rate_limit="5000 req/hr (authenticated)",
        requires_key=True,
        requires_oauth=True,
    ),
    "twitter_x": RateLimitProfile(
        rate_limit_profile_id="twitter_x",
        paid_rate_limit="tier-based",
        requires_key=True,
        requires_oauth=True,
    ),
    "default_public_api": RateLimitProfile(
        rate_limit_profile_id="default_public_api",
        free_rate_limit="varies by provider",
        requires_key=False,
        requires_oauth=False,
    ),
}


# ═══════════════════════════════════════════════════════════════════════════
# DUNE ACCESS MODES
# ═══════════════════════════════════════════════════════════════════════════

DUNE_ACCESS_MODES: List[DuneAccessMode] = [
    DuneAccessMode(
        mode_id="dune_api",
        display_name="Dune Analytics API",
        purpose="Prototyping, parameterized SQL queries, supplemental extraction, smaller workloads",
        connector_role=ConnectorRole.QUERY_EXECUTION,
        supports_query_execution=True,
        supports_historical_backfill=True,
        max_result_size_metadata="8GB/query (approx)",
        pagination_supported=True,
        implementation_status=ImplementationStatus.CREDENTIAL_GATED,
        staging_blocker="Requires DUNE_API_KEY credential",
        rate_limit_profile_id="dune_api",
        cost_profile_id="dune_api",
    ),
    DuneAccessMode(
        mode_id="dune_datashare",
        display_name="Dune Datashare (Warehouse)",
        purpose="Full historical lake bootstrap through Snowflake/BigQuery/Databricks direct warehouse replication",
        connector_role=ConnectorRole.WAREHOUSE_DATASHARE,
        supports_warehouse_datashare=True,
        supports_historical_backfill=True,
        read_only_source=True,
        implementation_status=ImplementationStatus.CREDENTIAL_GATED,
        staging_blocker="Requires Dune Enterprise contract + warehouse provisioning (Snowflake/BigQuery/Databricks)",
        rate_limit_profile_id="dune_datashare",
        cost_profile_id="dune_datashare",
        warehouse_provider="snowflake",
        refresh_cadence="24h",
    ),
    DuneAccessMode(
        mode_id="dune_sim",
        display_name="Dune Sim / Echo (Real-time Enrichment)",
        purpose="Real-time wallet balances, token holdings, transaction enrichment across supported chains. Best for live SDK enrichment, not bulk historical extraction.",
        connector_role=ConnectorRole.REALTIME_STREAM,
        supports_realtime_stream=True,
        implementation_status=ImplementationStatus.CREDENTIAL_GATED,
        staging_blocker="Requires Dune Enterprise access",
        rate_limit_profile_id="dune_sim",
        cost_profile_id="dune_sim",
        refresh_cadence="realtime",
    ),
]


# ═══════════════════════════════════════════════════════════════════════════
# CHAIN EXTRACTION PLANS
# ═══════════════════════════════════════════════════════════════════════════

CHAIN_EXTRACTION_PLANS: List[ChainExtractionPlan] = [
    # P0 CRITICAL
    ChainExtractionPlan(
        chain_id="ethereum",
        chain_name="Ethereum",
        priority="P0_CRITICAL",
        estimated_size_low="10TB",
        estimated_size_high="50TB",
        decoded_size_estimate="15TB",
        timeframe="ongoing",
        dune_table_names=["ethereum.transactions", "ethereum.traces", "ethereum.logs", "ethereum.blocks"],
        bronze_target="bronze_onchain",
        silver_target="silver_onchain",
        gold_feature_targets=["wallet_interaction_graph", "defi_behavior", "contract_risk"],
        neptune_graph_targets=["wallet_wallet_edge", "wallet_contract_edge"],
        model_consumers=["intent_prediction", "bot_detection", "fraud_detection", "anomaly_detection"],
        status="planned",
    ),
    ChainExtractionPlan(
        chain_id="solana",
        chain_name="Solana",
        priority="P0_CRITICAL",
        estimated_size_low="5TB",
        estimated_size_high="30TB",
        decoded_size_estimate="8TB",
        timeframe="ongoing",
        dune_table_names=["solana.transactions", "solana.account_activity"],
        bronze_target="bronze_onchain",
        silver_target="silver_onchain",
        gold_feature_targets=["cross_chain_wallet_profile", "defi_behavior"],
        neptune_graph_targets=["wallet_wallet_edge"],
        model_consumers=["bot_detection", "fraud_detection"],
        status="planned",
    ),
    ChainExtractionPlan(
        chain_id="bnb",
        chain_name="BNB Chain",
        priority="P0_CRITICAL",
        estimated_size_low="5TB",
        estimated_size_high="25TB",
        decoded_size_estimate="7TB",
        timeframe="ongoing",
        dune_table_names=["bnb.transactions", "bnb.logs"],
        bronze_target="bronze_onchain",
        silver_target="silver_onchain",
        gold_feature_targets=["defi_behavior", "token_flow_network"],
        neptune_graph_targets=["wallet_wallet_edge"],
        model_consumers=["intent_prediction", "fraud_detection"],
        status="planned",
    ),
    ChainExtractionPlan(
        chain_id="polygon",
        chain_name="Polygon",
        priority="P0_CRITICAL",
        estimated_size_low="3TB",
        estimated_size_high="15TB",
        decoded_size_estimate="5TB",
        timeframe="ongoing",
        dune_table_names=["polygon.transactions", "polygon.logs"],
        bronze_target="bronze_onchain",
        silver_target="silver_onchain",
        gold_feature_targets=["defi_behavior", "bridge_transactions"],
        neptune_graph_targets=["wallet_wallet_edge"],
        model_consumers=["intent_prediction", "bot_detection"],
        status="planned",
    ),
    ChainExtractionPlan(
        chain_id="arbitrum",
        chain_name="Arbitrum",
        priority="P0_CRITICAL",
        estimated_size_low="2TB",
        estimated_size_high="10TB",
        decoded_size_estimate="3TB",
        timeframe="ongoing",
        dune_table_names=["arbitrum.transactions", "arbitrum.logs"],
        bronze_target="bronze_onchain",
        silver_target="silver_onchain",
        gold_feature_targets=["defi_behavior", "bridge_transactions"],
        neptune_graph_targets=["wallet_wallet_edge"],
        model_consumers=["intent_prediction", "fraud_detection"],
        status="planned",
    ),
    ChainExtractionPlan(
        chain_id="base",
        chain_name="Base",
        priority="P0_CRITICAL",
        estimated_size_low="1TB",
        estimated_size_high="8TB",
        decoded_size_estimate="2TB",
        timeframe="ongoing",
        dune_table_names=["base.transactions", "base.logs"],
        bronze_target="bronze_onchain",
        silver_target="silver_onchain",
        gold_feature_targets=["defi_behavior", "bridge_transactions"],
        neptune_graph_targets=["wallet_wallet_edge"],
        model_consumers=["intent_prediction", "bot_detection"],
        status="planned",
    ),
    # P1 HIGH
    ChainExtractionPlan(
        chain_id="optimism",
        chain_name="Optimism",
        priority="P1_HIGH",
        estimated_size_low="1TB",
        estimated_size_high="5TB",
        decoded_size_estimate="2TB",
        timeframe="Q3 2026",
        dune_table_names=["optimism.transactions", "optimism.logs"],
        bronze_target="bronze_onchain",
        silver_target="silver_onchain",
        gold_feature_targets=["defi_behavior"],
        neptune_graph_targets=["wallet_wallet_edge"],
        model_consumers=["intent_prediction"],
        status="planned",
    ),
    ChainExtractionPlan(
        chain_id="avalanche",
        chain_name="Avalanche",
        priority="P1_HIGH",
        estimated_size_low="1TB",
        estimated_size_high="5TB",
        decoded_size_estimate="2TB",
        timeframe="Q3 2026",
        dune_table_names=["avalanche_c.transactions", "avalanche_c.logs"],
        bronze_target="bronze_onchain",
        silver_target="silver_onchain",
        gold_feature_targets=["defi_behavior"],
        neptune_graph_targets=["wallet_wallet_edge"],
        model_consumers=["intent_prediction", "fraud_detection"],
        status="planned",
    ),
    ChainExtractionPlan(
        chain_id="tron",
        chain_name="TRON",
        priority="P1_HIGH",
        estimated_size_low="2TB",
        estimated_size_high="10TB",
        decoded_size_estimate="3TB",
        timeframe="Q4 2026",
        dune_table_names=["tron.transactions"],
        bronze_target="bronze_onchain",
        silver_target="silver_onchain",
        gold_feature_targets=["token_flow_network"],
        neptune_graph_targets=["wallet_wallet_edge"],
        model_consumers=["fraud_detection"],
        status="planned",
    ),
    ChainExtractionPlan(
        chain_id="bitcoin",
        chain_name="Bitcoin",
        priority="P1_HIGH",
        estimated_size_low="500GB",
        estimated_size_high="2TB",
        decoded_size_estimate="600GB",
        timeframe="Q4 2026",
        dune_table_names=["bitcoin.inputs", "bitcoin.outputs", "bitcoin.transactions"],
        bronze_target="bronze_onchain",
        silver_target="silver_onchain",
        gold_feature_targets=["wallet_balance_snapshot", "token_flow_network"],
        neptune_graph_targets=["wallet_wallet_edge"],
        model_consumers=["anomaly_detection", "fraud_detection"],
        status="planned",
    ),
    ChainExtractionPlan(
        chain_id="near",
        chain_name="NEAR",
        priority="P1_HIGH",
        estimated_size_low="500GB",
        estimated_size_high="2TB",
        decoded_size_estimate="700GB",
        timeframe="Q4 2026",
        dune_table_names=["near.transactions", "near.logs"],
        bronze_target="bronze_onchain",
        silver_target="silver_onchain",
        gold_feature_targets=["defi_behavior"],
        neptune_graph_targets=["wallet_wallet_edge"],
        model_consumers=["intent_prediction"],
        status="planned",
    ),
    ChainExtractionPlan(
        chain_id="sui",
        chain_name="Sui",
        priority="P1_HIGH",
        estimated_size_low="500GB",
        estimated_size_high="2TB",
        decoded_size_estimate="700GB",
        timeframe="Q4 2026",
        dune_table_names=["sui.transactions", "sui.events"],
        bronze_target="bronze_onchain",
        silver_target="silver_onchain",
        gold_feature_targets=["defi_behavior"],
        neptune_graph_targets=["wallet_wallet_edge"],
        model_consumers=["intent_prediction"],
        status="planned",
    ),
]


# ═══════════════════════════════════════════════════════════════════════════
# EXTRACTION PRODUCTS
# ═══════════════════════════════════════════════════════════════════════════

EXTRACTION_PRODUCTS: List[ExtractionProduct] = [
    ExtractionProduct(
        product_id="wallet_interaction_graphs",
        product_name="Wallet Interaction Graphs",
        source_tables=["ethereum.transactions", "ethereum.traces"],
        dedupe_key="tx_hash",
        lineage_fields=["from_address", "to_address", "block_number", "tx_hash"],
        model_consumers=["intent_prediction", "fraud_detection", "bot_detection"],
        graph_consumers=["neptune_wallet_edge"],
        profile360_consumers=["wallet_risk", "network_centrality"],
        quality_checks=["no_null_from_address", "valid_tx_hash", "positive_value"],
        freshness_checks=["block_number_increasing", "timestamp_within_24h"],
    ),
    ExtractionProduct(
        product_id="defi_protocol_interaction_sequences",
        product_name="DeFi Protocol Interaction Sequences",
        source_tables=["ethereum.logs", "uniswap_v3_ethereum.trades"],
        dedupe_key="log_id",
        lineage_fields=["contract_address", "topic0", "tx_hash", "block_number"],
        model_consumers=["intent_prediction", "session_scoring"],
        graph_consumers=["neptune_wallet_protocol_edge"],
        profile360_consumers=["defi_activity", "protocol_interaction_depth"],
        quality_checks=["valid_contract_address", "valid_event_signature"],
        freshness_checks=["block_timestamp_within_6h"],
    ),
    ExtractionProduct(
        product_id="token_flow_networks",
        product_name="Token Flow Networks",
        source_tables=["ethereum.transactions", "ethereum.logs"],
        dedupe_key="tx_hash_token_index",
        lineage_fields=["from_address", "to_address", "token_address", "amount"],
        model_consumers=["fraud_detection", "anomaly_detection", "attribution"],
        graph_consumers=["neptune_token_flow_edge"],
        profile360_consumers=["token_portfolio", "flow_centrality"],
        quality_checks=["positive_amount", "valid_token_address"],
        freshness_checks=["block_timestamp_within_6h"],
    ),
    ExtractionProduct(
        product_id="contract_interaction_fingerprints",
        product_name="Contract Interaction Fingerprints",
        source_tables=["ethereum.traces", "ethereum.logs"],
        dedupe_key="wallet_contract_pair",
        lineage_fields=["from_address", "to_address", "input_calldata_prefix"],
        model_consumers=["bot_detection", "fraud_detection"],
        graph_consumers=["neptune_contract_edge"],
        profile360_consumers=["contract_risk", "behavioral_fingerprint"],
        quality_checks=["valid_calldata", "non_empty_trace"],
        freshness_checks=["block_timestamp_within_24h"],
    ),
    ExtractionProduct(
        product_id="lending_borrowing_sequences",
        product_name="Lending/Borrowing Sequences",
        source_tables=["aave_v3_ethereum.borrows", "aave_v3_ethereum.repays", "aave_v3_ethereum.liquidations"],
        dedupe_key="event_id",
        lineage_fields=["user", "asset", "amount", "block_number"],
        model_consumers=["intent_prediction", "session_scoring"],
        graph_consumers=["neptune_lending_edge"],
        profile360_consumers=["credit_risk", "liquidation_history"],
        quality_checks=["positive_amount", "valid_asset_address"],
        freshness_checks=["block_timestamp_within_6h"],
    ),
    ExtractionProduct(
        product_id="nft_activity_features",
        product_name="NFT Activity Features",
        source_tables=["nft_ethereum.trades", "nft_ethereum.mints"],
        dedupe_key="trade_id",
        lineage_fields=["seller", "buyer", "nft_contract_address", "token_id", "price"],
        model_consumers=["fraud_detection", "intent_prediction"],
        graph_consumers=["neptune_nft_edge"],
        profile360_consumers=["nft_portfolio", "wash_trade_score"],
        quality_checks=["valid_nft_contract", "positive_price"],
        freshness_checks=["block_timestamp_within_24h"],
    ),
    ExtractionProduct(
        product_id="bridge_transaction_features",
        product_name="Bridge Transaction Features",
        source_tables=["ethereum.logs"],
        dedupe_key="bridge_tx_hash",
        lineage_fields=["from_chain", "to_chain", "from_address", "to_address", "amount", "token"],
        model_consumers=["attribution", "fraud_detection"],
        graph_consumers=["neptune_cross_chain_edge"],
        profile360_consumers=["cross_chain_activity"],
        quality_checks=["valid_bridge_contract", "positive_amount"],
        freshness_checks=["block_timestamp_within_6h"],
    ),
    ExtractionProduct(
        product_id="wallet_balance_snapshots",
        product_name="Wallet Balance Snapshots",
        source_tables=["tokens_ethereum.balances"],
        dedupe_key="wallet_token_block",
        lineage_fields=["address", "token_address", "balance", "block_number"],
        model_consumers=["anomaly_detection", "intent_prediction", "session_scoring"],
        graph_consumers=["neptune_asset_node"],
        profile360_consumers=["portfolio_composition", "wealth_tier"],
        quality_checks=["non_negative_balance", "valid_address"],
        freshness_checks=["block_timestamp_within_1h"],
    ),
    ExtractionProduct(
        product_id="gas_fee_mev_features",
        product_name="Gas Fee & MEV Features",
        source_tables=["ethereum.transactions", "ethereum.traces"],
        dedupe_key="tx_hash",
        lineage_fields=["from_address", "gas_used", "gas_price", "priority_fee", "block_number"],
        model_consumers=["bot_detection", "anomaly_detection"],
        graph_consumers=[],
        profile360_consumers=["mev_exposure", "gas_efficiency"],
        quality_checks=["positive_gas", "valid_tx"],
        freshness_checks=["block_timestamp_within_1h"],
    ),
    ExtractionProduct(
        product_id="contract_metadata_features",
        product_name="Contract Metadata Features",
        source_tables=["ethereum.creation_traces"],
        dedupe_key="contract_address",
        lineage_fields=["contract_address", "deployer", "block_number", "bytecode_hash"],
        model_consumers=["fraud_detection", "bot_detection"],
        graph_consumers=["neptune_contract_node"],
        profile360_consumers=["contract_risk", "deployer_history"],
        quality_checks=["valid_bytecode_hash", "valid_deployer"],
        freshness_checks=["block_timestamp_within_24h"],
    ),
]


# ═══════════════════════════════════════════════════════════════════════════
# OLYMPUS PROVIDER SOURCE CATALOG — 30+ Providers
# ═══════════════════════════════════════════════════════════════════════════

PROVIDER_CATALOG: List[ProviderSourceEntry] = [

    # ── Web3 On-Chain: Dune (3 access modes modeled separately) ─────────────
    ProviderSourceEntry(
        provider_id="dune_api",
        provider_name="Dune Analytics API",
        provider_category="onchain",
        source_category="sql_query_execution",
        data_coverage_summary="Parameterized SQL over decoded on-chain data across 30+ chains",
        access_method="api",
        connector_role=ConnectorRole.QUERY_EXECUTION,
        lake_write_policy=LakeWritePolicy.OLYMPUS_BASELINE_ELIGIBLE,
        priority_phase=PriorityPhase.PHASE_1_FOUNDATION,
        cost_profile_id="dune_api",
        rate_limit_profile_id="dune_api",
        source_manifest_id="manifest_dune_api",
        license_status="terms_review_required",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.PRODUCTION_SHAPED,
        risk_tier=RiskTier.MEDIUM,
        ml_value_tags=["on_chain_behavior", "wallet_interaction", "defi_protocol"],
        lake_layer_tags=["onchain_core"],
    ),
    ProviderSourceEntry(
        provider_id="dune_datashare",
        provider_name="Dune Datashare (Warehouse)",
        provider_category="onchain",
        source_category="warehouse_replication",
        data_coverage_summary="Full historical Dune data via Snowflake/BigQuery/Databricks datashare",
        access_method="warehouse_datashare",
        connector_role=ConnectorRole.WAREHOUSE_DATASHARE,
        lake_write_policy=LakeWritePolicy.OLYMPUS_BASELINE_ELIGIBLE,
        priority_phase=PriorityPhase.PHASE_1_FOUNDATION,
        cost_profile_id="dune_datashare",
        rate_limit_profile_id="dune_datashare",
        source_manifest_id="manifest_dune_datashare",
        license_status="enterprise_contract",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.CREDENTIAL_GATED,
        risk_tier=RiskTier.MEDIUM,
        ml_value_tags=["on_chain_history", "wallet_history", "defi_protocol"],
        lake_layer_tags=["onchain_core"],
        notes="Requires Dune Enterprise contract + warehouse provisioning",
    ),
    ProviderSourceEntry(
        provider_id="dune_sim",
        provider_name="Dune Sim / Echo",
        provider_category="onchain",
        source_category="realtime_wallet_enrichment",
        data_coverage_summary="Real-time wallet balances, token holdings, transaction enrichment",
        access_method="api",
        connector_role=ConnectorRole.REALTIME_STREAM,
        lake_write_policy=LakeWritePolicy.OLYMPUS_BASELINE_ELIGIBLE,
        priority_phase=PriorityPhase.PHASE_1_FOUNDATION,
        cost_profile_id="dune_sim",
        rate_limit_profile_id="dune_sim",
        source_manifest_id="manifest_dune_sim",
        license_status="terms_review_required",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.CREDENTIAL_GATED,
        risk_tier=RiskTier.MEDIUM,
        ml_value_tags=["real_time_enrichment", "wallet_balance", "token_holdings"],
        lake_layer_tags=["onchain_core"],
        notes="Not used for bulk historical extraction; use datashare for that",
    ),

    # ── Web3 On-Chain: Data Aggregators ─────────────────────────────────────
    ProviderSourceEntry(
        provider_id="defi_llama",
        provider_name="DeFi Llama",
        provider_category="onchain",
        source_category="defi_protocol_analytics",
        data_coverage_summary="TVL, protocol revenue, DEX volumes, yield rates across 2000+ protocols",
        access_method="api",
        priority_phase=PriorityPhase.PHASE_1_FOUNDATION,
        cost_profile_id="defi_llama",
        rate_limit_profile_id="default_public_api",
        source_manifest_id="manifest_defi_llama",
        license_status="public_api",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.SCAFFOLDED,
        risk_tier=RiskTier.LOW,
        ml_value_tags=["protocol_health", "tvl_signal", "defi_classification"],
        lake_layer_tags=["defi_protocol"],
    ),
    ProviderSourceEntry(
        provider_id="coingecko",
        provider_name="CoinGecko",
        provider_category="onchain",
        source_category="price_reference",
        data_coverage_summary="Price feeds, market cap, volume, OHLCV for 10,000+ tokens",
        access_method="api",
        priority_phase=PriorityPhase.PHASE_1_FOUNDATION,
        cost_profile_id="coingecko",
        rate_limit_profile_id="coingecko",
        source_manifest_id="manifest_coingecko",
        license_status="terms_review_required",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.SCAFFOLDED,
        risk_tier=RiskTier.LOW,
        ml_value_tags=["price_context", "market_data", "token_classification"],
        lake_layer_tags=["price_reference"],
    ),
    ProviderSourceEntry(
        provider_id="coinmarketcap",
        provider_name="CoinMarketCap",
        provider_category="onchain",
        source_category="price_reference",
        data_coverage_summary="Price, market cap, volume, rankings for 10,000+ cryptocurrencies",
        access_method="api",
        priority_phase=PriorityPhase.PHASE_3_DEPTH,
        cost_profile_id="coinmarketcap",
        rate_limit_profile_id="default_public_api",
        source_manifest_id="manifest_coinmarketcap",
        license_status="terms_review_required",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.SCAFFOLDED,
        risk_tier=RiskTier.LOW,
        ml_value_tags=["price_context", "market_data"],
        lake_layer_tags=["price_reference"],
    ),
    ProviderSourceEntry(
        provider_id="etherscan",
        provider_name="Etherscan",
        provider_category="onchain",
        source_category="block_explorer",
        data_coverage_summary="Ethereum transactions, contract verification, address labels, token transfers",
        access_method="api",
        priority_phase=PriorityPhase.PHASE_2_ENRICHMENT,
        cost_profile_id="etherscan",
        rate_limit_profile_id="etherscan",
        source_manifest_id="manifest_etherscan",
        license_status="terms_review_required",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.CREDENTIAL_GATED,
        risk_tier=RiskTier.LOW,
        ml_value_tags=["identity_enrichment", "contract_risk", "address_labeling"],
        lake_layer_tags=["onchain_core"],
    ),
    ProviderSourceEntry(
        provider_id="the_graph",
        provider_name="The Graph",
        provider_category="onchain",
        source_category="subgraph_query",
        data_coverage_summary="Protocol-specific indexed data via GraphQL subgraphs across major DeFi protocols",
        access_method="api",
        priority_phase=PriorityPhase.PHASE_2_ENRICHMENT,
        cost_profile_id="the_graph",
        rate_limit_profile_id="the_graph",
        source_manifest_id="manifest_the_graph",
        license_status="public_api",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.SCAFFOLDED,
        risk_tier=RiskTier.LOW,
        ml_value_tags=["protocol_analytics", "defi_behavior", "governance"],
        lake_layer_tags=["defi_protocol"],
    ),
    ProviderSourceEntry(
        provider_id="flipside_crypto",
        provider_name="Flipside Crypto",
        provider_category="onchain",
        source_category="sql_analytics",
        data_coverage_summary="Multi-chain SQL analytics, curated DeFi/NFT/social datasets",
        access_method="api",
        priority_phase=PriorityPhase.PHASE_3_DEPTH,
        cost_profile_id="flipside_crypto",
        rate_limit_profile_id="default_public_api",
        source_manifest_id="manifest_flipside",
        license_status="terms_review_required",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.SCAFFOLDED,
        risk_tier=RiskTier.MEDIUM,
        ml_value_tags=["wallet_analytics", "defi_behavior"],
        lake_layer_tags=["onchain_core"],
    ),
    ProviderSourceEntry(
        provider_id="covalent_goldrush",
        provider_name="Covalent / GoldRush",
        provider_category="onchain",
        source_category="multichain_data",
        data_coverage_summary="Wallet balances, transactions, NFT metadata across 200+ chains",
        access_method="api",
        priority_phase=PriorityPhase.PHASE_3_DEPTH,
        cost_profile_id="covalent_goldrush",
        rate_limit_profile_id="default_public_api",
        source_manifest_id="manifest_covalent",
        license_status="terms_review_required",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.CREDENTIAL_GATED,
        risk_tier=RiskTier.LOW,
        ml_value_tags=["cross_chain_wallet", "nft_activity"],
        lake_layer_tags=["onchain_core"],
    ),
    ProviderSourceEntry(
        provider_id="alchemy",
        provider_name="Alchemy",
        provider_category="onchain",
        source_category="rpc_enrichment",
        data_coverage_summary="Enhanced APIs: NFT metadata, token balances, transaction history, webhooks",
        access_method="api",
        priority_phase=PriorityPhase.PHASE_2_ENRICHMENT,
        cost_profile_id="alchemy",
        rate_limit_profile_id="default_public_api",
        source_manifest_id="manifest_alchemy",
        license_status="terms_review_required",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.CREDENTIAL_GATED,
        risk_tier=RiskTier.LOW,
        ml_value_tags=["wallet_enrichment", "nft_identity"],
        lake_layer_tags=["onchain_core"],
    ),
    ProviderSourceEntry(
        provider_id="moralis",
        provider_name="Moralis",
        provider_category="onchain",
        source_category="multichain_enrichment",
        data_coverage_summary="NFT metadata, DeFi positions, wallet history across EVM + Solana",
        access_method="api",
        priority_phase=PriorityPhase.PHASE_2_ENRICHMENT,
        cost_profile_id="moralis",
        rate_limit_profile_id="default_public_api",
        source_manifest_id="manifest_moralis",
        license_status="terms_review_required",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.CREDENTIAL_GATED,
        risk_tier=RiskTier.LOW,
        ml_value_tags=["wallet_enrichment", "nft_identity", "defi_positions"],
        lake_layer_tags=["onchain_core"],
    ),
    ProviderSourceEntry(
        provider_id="transpose",
        provider_name="Transpose",
        provider_category="onchain",
        source_category="historical_analytics",
        data_coverage_summary="SQL queries over historical EVM data: transactions, NFTs, tokens",
        access_method="api",
        priority_phase=PriorityPhase.PHASE_3_DEPTH,
        cost_profile_id="transpose",
        rate_limit_profile_id="default_public_api",
        source_manifest_id="manifest_transpose",
        license_status="terms_review_required",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.CREDENTIAL_GATED,
        risk_tier=RiskTier.LOW,
        ml_value_tags=["historical_analytics", "wallet_history"],
        lake_layer_tags=["onchain_core"],
    ),
    ProviderSourceEntry(
        provider_id="solscan",
        provider_name="Solscan API",
        provider_category="onchain",
        source_category="solana_explorer",
        data_coverage_summary="Solana transactions, token accounts, NFTs, DeFi protocols",
        access_method="api",
        priority_phase=PriorityPhase.PHASE_2_ENRICHMENT,
        cost_profile_id="solscan",
        rate_limit_profile_id="default_public_api",
        source_manifest_id="manifest_solscan",
        license_status="terms_review_required",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.CREDENTIAL_GATED,
        risk_tier=RiskTier.LOW,
        ml_value_tags=["solana_analytics", "wallet_history"],
        lake_layer_tags=["onchain_core"],
    ),

    # ── CEX Market Data ──────────────────────────────────────────────────────
    ProviderSourceEntry(
        provider_id="binance_public",
        provider_name="Binance (Public Endpoints)",
        provider_category="cex",
        source_category="cex_market_data",
        data_coverage_summary="Price feeds, order books, klines, funding rates, liquidations (public)",
        access_method="api",
        priority_phase=PriorityPhase.PHASE_1_FOUNDATION,
        cost_profile_id="binance_public",
        rate_limit_profile_id="binance_public",
        source_manifest_id="manifest_binance",
        license_status="public_api",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.SCAFFOLDED,
        risk_tier=RiskTier.LOW,
        ml_value_tags=["funding_rates", "liquidation_risk", "market_microstructure"],
        lake_layer_tags=["cex_market_data"],
    ),
    ProviderSourceEntry(
        provider_id="coinbase_exchange",
        provider_name="Coinbase Exchange",
        provider_category="cex",
        source_category="cex_market_data",
        data_coverage_summary="Price feeds, order books, trades, candles (public REST + WebSocket)",
        access_method="api",
        priority_phase=PriorityPhase.PHASE_1_FOUNDATION,
        cost_profile_id="coinbase_exchange",
        rate_limit_profile_id="default_public_api",
        source_manifest_id="manifest_coinbase",
        license_status="public_api",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.SCAFFOLDED,
        risk_tier=RiskTier.LOW,
        ml_value_tags=["price_reference", "market_microstructure"],
        lake_layer_tags=["cex_market_data"],
    ),
    ProviderSourceEntry(
        provider_id="kraken",
        provider_name="Kraken",
        provider_category="cex",
        source_category="cex_market_data",
        data_coverage_summary="Price feeds, OHLCV, order books, funding rates",
        access_method="api",
        priority_phase=PriorityPhase.PHASE_3_DEPTH,
        cost_profile_id="kraken",
        rate_limit_profile_id="default_public_api",
        source_manifest_id="manifest_kraken",
        license_status="public_api",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.SCAFFOLDED,
        risk_tier=RiskTier.LOW,
        ml_value_tags=["price_reference", "funding_rates"],
        lake_layer_tags=["cex_market_data"],
    ),
    ProviderSourceEntry(
        provider_id="okx",
        provider_name="OKX",
        provider_category="cex",
        source_category="cex_market_data",
        data_coverage_summary="Price feeds, funding rates, order books, liquidations",
        access_method="api",
        priority_phase=PriorityPhase.PHASE_3_DEPTH,
        cost_profile_id="okx",
        rate_limit_profile_id="default_public_api",
        source_manifest_id="manifest_okx",
        license_status="public_api",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.SCAFFOLDED,
        risk_tier=RiskTier.LOW,
        ml_value_tags=["funding_rates", "liquidation_risk"],
        lake_layer_tags=["cex_market_data"],
    ),
    ProviderSourceEntry(
        provider_id="bybit",
        provider_name="Bybit",
        provider_category="cex",
        source_category="cex_market_data",
        data_coverage_summary="Perpetual funding rates, order books, liquidations",
        access_method="api",
        priority_phase=PriorityPhase.PHASE_3_DEPTH,
        cost_profile_id="bybit",
        rate_limit_profile_id="default_public_api",
        source_manifest_id="manifest_bybit",
        license_status="public_api",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.SCAFFOLDED,
        risk_tier=RiskTier.LOW,
        ml_value_tags=["funding_rates", "liquidation_risk"],
        lake_layer_tags=["cex_market_data"],
    ),
    ProviderSourceEntry(
        provider_id="ccxt",
        provider_name="CCXT (Multi-Exchange Library)",
        provider_category="cex",
        source_category="cex_market_data",
        data_coverage_summary="Unified interface to 100+ exchanges for OHLCV, tickers, order books",
        access_method="api",
        priority_phase=PriorityPhase.PHASE_3_DEPTH,
        cost_profile_id="ccxt",
        rate_limit_profile_id="default_public_api",
        source_manifest_id="manifest_ccxt",
        license_status="open_license",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.SCAFFOLDED,
        risk_tier=RiskTier.LOW,
        ml_value_tags=["arbitrage_signals", "market_microstructure"],
        lake_layer_tags=["cex_market_data"],
    ),

    # ── Prediction Markets ───────────────────────────────────────────────────
    ProviderSourceEntry(
        provider_id="polymarket_gamma",
        provider_name="Polymarket Gamma",
        provider_category="prediction_market",
        source_category="prediction_market_data",
        data_coverage_summary="Market metadata, probabilities, resolution, trading activity (REST)",
        access_method="api",
        priority_phase=PriorityPhase.PHASE_1_FOUNDATION,
        cost_profile_id="polymarket_gamma",
        rate_limit_profile_id="polymarket_gamma",
        source_manifest_id="manifest_polymarket_gamma",
        license_status="public_api",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.SCAFFOLDED,
        risk_tier=RiskTier.LOW,
        ml_value_tags=["crowd_probability", "macro_event_signals", "intent_prediction"],
        lake_layer_tags=["prediction_markets"],
    ),
    ProviderSourceEntry(
        provider_id="polymarket_clob",
        provider_name="Polymarket CLOB",
        provider_category="prediction_market",
        source_category="prediction_market_orderbook",
        data_coverage_summary="Real-time order book snapshots and trade history",
        access_method="api",
        priority_phase=PriorityPhase.PHASE_3_DEPTH,
        cost_profile_id="polymarket_clob",
        rate_limit_profile_id="default_public_api",
        source_manifest_id="manifest_polymarket_clob",
        license_status="public_api",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.CREDENTIAL_GATED,
        risk_tier=RiskTier.LOW,
        ml_value_tags=["order_book_signals", "market_microstructure"],
        lake_layer_tags=["prediction_markets"],
    ),
    ProviderSourceEntry(
        provider_id="kalshi",
        provider_name="Kalshi",
        provider_category="prediction_market",
        source_category="prediction_market_data",
        data_coverage_summary="US-regulated prediction market events: economic, political, sports",
        access_method="api",
        priority_phase=PriorityPhase.PHASE_1_FOUNDATION,
        cost_profile_id="kalshi",
        rate_limit_profile_id="kalshi",
        source_manifest_id="manifest_kalshi",
        license_status="terms_review_required",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.CREDENTIAL_GATED,
        risk_tier=RiskTier.MEDIUM,
        ml_value_tags=["macro_event_signals", "crowd_probability"],
        lake_layer_tags=["prediction_markets"],
    ),
    ProviderSourceEntry(
        provider_id="metaculus",
        provider_name="Metaculus",
        provider_category="prediction_market",
        source_category="forecasting_data",
        data_coverage_summary="Community forecasts: science, politics, technology, economics",
        access_method="api",
        priority_phase=PriorityPhase.PHASE_3_DEPTH,
        cost_profile_id="metaculus",
        rate_limit_profile_id="default_public_api",
        source_manifest_id="manifest_metaculus",
        license_status="public_api",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.SCAFFOLDED,
        risk_tier=RiskTier.LOW,
        ml_value_tags=["forecast_accuracy", "macro_event_signals"],
        lake_layer_tags=["prediction_markets"],
    ),
    ProviderSourceEntry(
        provider_id="manifold_markets",
        provider_name="Manifold Markets",
        provider_category="prediction_market",
        source_category="forecasting_data",
        data_coverage_summary="Play-money prediction markets across broad topics",
        access_method="api",
        priority_phase=PriorityPhase.PHASE_3_DEPTH,
        cost_profile_id="manifold_markets",
        rate_limit_profile_id="default_public_api",
        source_manifest_id="manifest_manifold",
        license_status="public_api",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.SCAFFOLDED,
        risk_tier=RiskTier.LOW,
        ml_value_tags=["forecast_accuracy", "community_signals"],
        lake_layer_tags=["prediction_markets"],
    ),

    # ── Web3 Social ──────────────────────────────────────────────────────────
    ProviderSourceEntry(
        provider_id="farcaster_neynar",
        provider_name="Farcaster / Neynar",
        provider_category="social_web3",
        source_category="decentralized_social",
        data_coverage_summary="Casts, follows, reactions, channel memberships — wallet-linked social identity",
        access_method="api",
        priority_phase=PriorityPhase.PHASE_2_ENRICHMENT,
        cost_profile_id="farcaster_neynar",
        rate_limit_profile_id="default_public_api",
        source_manifest_id="manifest_farcaster",
        license_status="terms_review_required",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.CREDENTIAL_GATED,
        risk_tier=RiskTier.MEDIUM,
        ml_value_tags=["social_identity", "wallet_linked_identity", "community_health"],
        lake_layer_tags=["social_web3_native"],
    ),
    ProviderSourceEntry(
        provider_id="lens_protocol",
        provider_name="Lens Protocol",
        provider_category="social_web3",
        source_category="decentralized_social",
        data_coverage_summary="Lens profiles, publications, follows, mirrors — on-chain social graph",
        access_method="api",
        priority_phase=PriorityPhase.PHASE_2_ENRICHMENT,
        cost_profile_id="lens_protocol",
        rate_limit_profile_id="default_public_api",
        source_manifest_id="manifest_lens",
        license_status="public_api",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.SCAFFOLDED,
        risk_tier=RiskTier.LOW,
        ml_value_tags=["social_identity", "wallet_linked_identity"],
        lake_layer_tags=["social_web3_native"],
    ),
    ProviderSourceEntry(
        provider_id="ens_public",
        provider_name="ENS (Ethereum Name Service)",
        provider_category="social_web3",
        source_category="identity_resolution",
        data_coverage_summary="ENS name → wallet address resolution, reverse lookup, avatar metadata",
        access_method="api",
        priority_phase=PriorityPhase.PHASE_2_ENRICHMENT,
        cost_profile_id="ens_public",
        rate_limit_profile_id="default_public_api",
        source_manifest_id="manifest_ens",
        license_status="public_api",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.SCAFFOLDED,
        risk_tier=RiskTier.LOW,
        ml_value_tags=["identity_enrichment", "wallet_social_edge"],
        lake_layer_tags=["nft_identity"],
    ),
    ProviderSourceEntry(
        provider_id="snapshot",
        provider_name="Snapshot",
        provider_category="social_web3",
        source_category="dao_governance",
        data_coverage_summary="DAO proposals, votes, voter wallets across 10,000+ DAOs",
        access_method="api",
        priority_phase=PriorityPhase.PHASE_2_ENRICHMENT,
        cost_profile_id="snapshot",
        rate_limit_profile_id="default_public_api",
        source_manifest_id="manifest_snapshot",
        license_status="public_api",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.SCAFFOLDED,
        risk_tier=RiskTier.LOW,
        ml_value_tags=["governance_participation", "identity_enrichment"],
        lake_layer_tags=["nft_identity"],
    ),
    ProviderSourceEntry(
        provider_id="github_api",
        provider_name="GitHub API",
        provider_category="social_web2",
        source_category="developer_activity",
        data_coverage_summary="Repo commits, issues, PRs, contributors — protocol development health signals",
        access_method="api",
        priority_phase=PriorityPhase.PHASE_2_ENRICHMENT,
        cost_profile_id="github_api",
        rate_limit_profile_id="github_api",
        source_manifest_id="manifest_github",
        license_status="terms_review_required",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.CREDENTIAL_GATED,
        risk_tier=RiskTier.MEDIUM,
        ml_value_tags=["developer_activity", "protocol_health", "rug_pull_detection"],
        lake_layer_tags=["social_web2"],
    ),

    # ── Social Web2 (compliance-gated) ──────────────────────────────────────
    ProviderSourceEntry(
        provider_id="twitter_x",
        provider_name="Twitter / X API",
        provider_category="social_web2",
        source_category="social_sentiment",
        data_coverage_summary="Tweets, trends, user activity — sentiment signals, influencer mapping",
        access_method="api",
        priority_phase=PriorityPhase.PHASE_3_DEPTH,
        cost_profile_id="twitter_x",
        rate_limit_profile_id="twitter_x",
        source_manifest_id="manifest_twitter_x",
        license_status="terms_review_required",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.DISABLED_COMPLIANCE_REVIEW,
        risk_tier=RiskTier.HIGH,
        ml_value_tags=["sentiment", "narrative_classification", "whale_coordination"],
        lake_layer_tags=["social_twitter"],
        notes="DISABLED: requires compliance review for commercial use and model training",
    ),
    ProviderSourceEntry(
        provider_id="reddit",
        provider_name="Reddit API",
        provider_category="social_web2",
        source_category="social_discussion",
        data_coverage_summary="Subreddit posts, comments, karma — community discussion signals",
        access_method="api",
        priority_phase=PriorityPhase.PHASE_3_DEPTH,
        cost_profile_id="reddit",
        rate_limit_profile_id="default_public_api",
        source_manifest_id="manifest_reddit",
        license_status="terms_review_required",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.DISABLED_COMPLIANCE_REVIEW,
        risk_tier=RiskTier.HIGH,
        ml_value_tags=["sentiment", "community_health", "pump_dump_detection"],
        lake_layer_tags=["social_web2"],
        notes="DISABLED: requires compliance review for commercial use and model training",
    ),
    ProviderSourceEntry(
        provider_id="telegram_bot",
        provider_name="Telegram Bot API",
        provider_category="social_web2",
        source_category="messaging_monitoring",
        data_coverage_summary="Group messages via bot subscription — community coordination signals",
        access_method="api",
        priority_phase=PriorityPhase.PHASE_3_DEPTH,
        cost_profile_id="telegram_bot",
        rate_limit_profile_id="default_public_api",
        source_manifest_id="manifest_telegram",
        license_status="terms_review_required",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.DISABLED_COMPLIANCE_REVIEW,
        risk_tier=RiskTier.HIGH,
        ml_value_tags=["sentiment", "whale_coordination", "rug_pull_detection"],
        lake_layer_tags=["social_web2"],
        notes="DISABLED: requires compliance review; surveillance-sensitive data",
    ),
    ProviderSourceEntry(
        provider_id="discord_bot",
        provider_name="Discord Bot API",
        provider_category="social_web2",
        source_category="messaging_monitoring",
        data_coverage_summary="Server messages via bot — NFT/DeFi community activity",
        access_method="api",
        priority_phase=PriorityPhase.PHASE_3_DEPTH,
        cost_profile_id="discord_bot",
        rate_limit_profile_id="default_public_api",
        source_manifest_id="manifest_discord",
        license_status="terms_review_required",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.DISABLED_COMPLIANCE_REVIEW,
        risk_tier=RiskTier.HIGH,
        ml_value_tags=["sentiment", "community_health"],
        lake_layer_tags=["social_web2"],
        notes="DISABLED: requires compliance review; surveillance-sensitive data",
    ),

    # ── Protocol-Specific ───────────────────────────────────────────────────
    ProviderSourceEntry(
        provider_id="uniswap_subgraph",
        provider_name="Uniswap Subgraph",
        provider_category="protocol_specific",
        source_category="dex_analytics",
        data_coverage_summary="Uniswap V2/V3 swaps, liquidity positions, pools, TVL",
        access_method="api",
        priority_phase=PriorityPhase.PHASE_3_DEPTH,
        cost_profile_id="uniswap_subgraph",
        rate_limit_profile_id="the_graph",
        source_manifest_id="manifest_uniswap",
        license_status="open_license",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.SCAFFOLDED,
        risk_tier=RiskTier.LOW,
        ml_value_tags=["dex_behavior", "lp_strategy", "defi_behavior"],
        lake_layer_tags=["defi_protocol"],
    ),
    ProviderSourceEntry(
        provider_id="aave_subgraph",
        provider_name="Aave Subgraph",
        provider_category="protocol_specific",
        source_category="lending_analytics",
        data_coverage_summary="Aave V2/V3 borrows, repays, liquidations, collateral positions",
        access_method="api",
        priority_phase=PriorityPhase.PHASE_3_DEPTH,
        cost_profile_id="aave_subgraph",
        rate_limit_profile_id="the_graph",
        source_manifest_id="manifest_aave",
        license_status="open_license",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.SCAFFOLDED,
        risk_tier=RiskTier.LOW,
        ml_value_tags=["lending_behavior", "liquidation_risk", "credit_risk"],
        lake_layer_tags=["defi_protocol"],
    ),
    ProviderSourceEntry(
        provider_id="chainlink_price_feeds",
        provider_name="Chainlink Price Feeds",
        provider_category="protocol_specific",
        source_category="oracle_data",
        data_coverage_summary="Decentralized oracle price feeds for 500+ asset pairs across chains",
        access_method="api",
        priority_phase=PriorityPhase.PHASE_3_DEPTH,
        cost_profile_id="chainlink_price_feeds",
        rate_limit_profile_id="default_public_api",
        source_manifest_id="manifest_chainlink",
        license_status="public_api",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.SCAFFOLDED,
        risk_tier=RiskTier.LOW,
        ml_value_tags=["oracle_validation", "price_context", "manipulation_detection"],
        lake_layer_tags=["price_reference"],
    ),
    ProviderSourceEntry(
        provider_id="opensea",
        provider_name="OpenSea API",
        provider_category="protocol_specific",
        source_category="nft_marketplace",
        data_coverage_summary="NFT listings, sales, offers, collection metadata",
        access_method="api",
        priority_phase=PriorityPhase.PHASE_3_DEPTH,
        cost_profile_id="opensea",
        rate_limit_profile_id="default_public_api",
        source_manifest_id="manifest_opensea",
        license_status="terms_review_required",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.CREDENTIAL_GATED,
        risk_tier=RiskTier.MEDIUM,
        ml_value_tags=["nft_activity", "wash_trade_detection", "fraud_detection"],
        lake_layer_tags=["nft_identity"],
    ),
    ProviderSourceEntry(
        provider_id="reservoir",
        provider_name="Reservoir",
        provider_category="protocol_specific",
        source_category="nft_aggregator",
        data_coverage_summary="Multi-marketplace NFT sales, listings, rarity, royalties",
        access_method="api",
        priority_phase=PriorityPhase.PHASE_3_DEPTH,
        cost_profile_id="reservoir",
        rate_limit_profile_id="default_public_api",
        source_manifest_id="manifest_reservoir",
        license_status="terms_review_required",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.CREDENTIAL_GATED,
        risk_tier=RiskTier.MEDIUM,
        ml_value_tags=["nft_activity", "wash_trade_detection"],
        lake_layer_tags=["nft_identity"],
    ),
    ProviderSourceEntry(
        provider_id="token_terminal",
        provider_name="Token Terminal",
        provider_category="protocol_specific",
        source_category="protocol_fundamentals",
        data_coverage_summary="Protocol fundamentals: revenue, fees, DAU, TVL, P/E ratios for 100+ protocols",
        access_method="api",
        priority_phase=PriorityPhase.PHASE_3_DEPTH,
        cost_profile_id="token_terminal",
        rate_limit_profile_id="default_public_api",
        source_manifest_id="manifest_token_terminal",
        license_status="terms_review_required",
        terms_status="pending_review",
        commercial_use_status="pending_review",
        model_training_status="pending_review",
        implementation_status=ImplementationStatus.CREDENTIAL_GATED,
        risk_tier=RiskTier.MEDIUM,
        ml_value_tags=["protocol_health", "protocol_abandonment_risk"],
        lake_layer_tags=["defi_protocol"],
    ),
]


# ═══════════════════════════════════════════════════════════════════════════
# CATALOG ACCESSORS
# ═══════════════════════════════════════════════════════════════════════════

def get_provider(provider_id: str) -> ProviderSourceEntry | None:
    return next((p for p in PROVIDER_CATALOG if p.provider_id == provider_id), None)


def get_providers_by_phase(phase: PriorityPhase) -> List[ProviderSourceEntry]:
    return [p for p in PROVIDER_CATALOG if p.priority_phase == phase]


def get_providers_by_category(category: str) -> List[ProviderSourceEntry]:
    return [p for p in PROVIDER_CATALOG if p.provider_category == category]


def get_enabled_providers() -> List[ProviderSourceEntry]:
    return [
        p for p in PROVIDER_CATALOG
        if p.implementation_status != ImplementationStatus.DISABLED_COMPLIANCE_REVIEW
        and p.implementation_status != ImplementationStatus.DEPRECATED
    ]


def get_cost_profile(cost_profile_id: str) -> CostProfile | None:
    return COST_PROFILES.get(cost_profile_id)


def get_rate_limit_profile(rate_limit_profile_id: str) -> RateLimitProfile | None:
    return RATE_LIMIT_PROFILES.get(rate_limit_profile_id)
