"""
CC-3.1 — Information Security Policy
Formal written security policy satisfying SOC 2 CC3.1 / ISO 27001 A.5.1.

Evidence artifact: generated policy document with version, owner, review schedule,
and staff acknowledgment workflow. Aligns with the 10-section policy generated by
policies/policy_generator.py and adds the governance lifecycle required for audit.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone


@dataclass
class SecurityPolicyVersion:
    """A versioned security policy document record."""
    version: str
    effective_date: str
    approved_by: str
    reviewed_by: list
    next_review: str
    sections: list
    acknowledgment_required: bool = True
    staff_ack_count: int = 0

    @property
    def is_current(self) -> bool:
        today = datetime.now(timezone.utc).date().isoformat()
        return self.effective_date <= today <= self.next_review


SECTIONS = [
    {
        "id": "1",
        "title": "Purpose and Scope",
        "content": (
            "This policy defines Aether's information security framework covering all systems, "
            "personnel, and third-party relationships. Applies to all employees, contractors, "
            "and sub-processors handling Aether systems or customer data."
        ),
    },
    {
        "id": "2",
        "title": "Roles and Responsibilities",
        "content": (
            "CISO: policy ownership, risk management, incident command. "
            "Engineering: secure-by-design implementation, vulnerability remediation. "
            "All staff: policy compliance, incident reporting, annual training completion."
        ),
    },
    {
        "id": "3",
        "title": "Access Management",
        "content": (
            "Principle of least privilege enforced via RBAC (4 roles: admin/editor/viewer/service). "
            "MFA required for all human console access. API keys rotate every 90 days. "
            "JWT tokens expire after 1 hour. Privileged access requires approval workflow."
        ),
    },
    {
        "id": "4",
        "title": "Network Security",
        "content": (
            "VPC isolation per environment. Private subnets for all data stores. "
            "AWS WAF: DDoS protection, rate limiting (1000 req/min per IP), bot control. "
            "TLS 1.3 enforced on all endpoints. No direct public internet access to data tiers."
        ),
    },
    {
        "id": "5",
        "title": "Data Protection",
        "content": (
            "Encryption: TLS 1.3 in transit, AES-256 via KMS at rest for all stores. "
            "PII pseudonymized (SHA-256 + per-tenant salt). IP addresses anonymized before storage. "
            "Data minimization: SDK collects only explicitly enabled categories."
        ),
    },
    {
        "id": "6",
        "title": "Vulnerability Management",
        "content": (
            "CI pipeline: Snyk (OSS dependencies), CodeQL (SAST), Trivy (containers), "
            "GitLeaks (secrets). Remediation SLAs: Critical 24h, High 72h, Medium 30d, Low 90d. "
            "Annual third-party penetration test. No known Critical/High findings in production."
        ),
    },
    {
        "id": "7",
        "title": "Incident Response",
        "content": (
            "PagerDuty immediate escalation. 8-step pipeline: detect → assess → contain → "
            "escalate → evidence → DPA notify (72h per Art. 33) → subject notify → remediate. "
            "Internal escalation within 30 minutes. Quarterly tabletop exercises."
        ),
    },
    {
        "id": "8",
        "title": "Change Management",
        "content": (
            "All changes via Git PRs with mandatory code review. CI/CD pipeline with automated "
            "security gates. Blue-green deployments with automatic rollback on health check failure. "
            "Production changes require approval from two engineers."
        ),
    },
    {
        "id": "9",
        "title": "Business Continuity",
        "content": (
            "Multi-AZ deployment (3 AZs). RDS 35-day automated backups. "
            "DR plan: RPO 1h, RTO 4h. Cross-region S3 replication. "
            "Infrastructure-as-code (Terraform) enables full rebuild within 2 hours."
        ),
    },
    {
        "id": "10",
        "title": "Compliance and Review",
        "content": (
            "Annual security policy review by CISO + Legal. Quarterly access reviews. "
            "SOC 2 Type II annual audit. GDPR compliance continuous monitoring. "
            "All staff complete security awareness training annually."
        ),
    },
]

# Current live policy version
CURRENT_POLICY = SecurityPolicyVersion(
    version="2.0",
    effective_date="2025-01-01",
    approved_by="CISO",
    reviewed_by=["Legal", "Engineering Lead", "CTO"],
    next_review="2026-01-01",
    sections=SECTIONS,
    acknowledgment_required=True,
    staff_ack_count=0,  # Updated when staff sign off
)


class SecurityPolicyManager:
    """Manages the information security policy lifecycle."""

    def __init__(self):
        self.versions: list[SecurityPolicyVersion] = [CURRENT_POLICY]

    def current_version(self) -> SecurityPolicyVersion:
        return next((v for v in self.versions if v.is_current), self.versions[-1])

    def generate_evidence(self) -> dict:
        pol = self.current_version()
        return {
            "control": "CC-3.1",
            "artifact": "Information Security Policy",
            "version": pol.version,
            "effective_date": pol.effective_date,
            "approved_by": pol.approved_by,
            "reviewed_by": pol.reviewed_by,
            "next_review": pol.next_review,
            "section_count": len(pol.sections),
            "acknowledgment_required": pol.acknowledgment_required,
            "status": "IMPLEMENTED",
            "evidence_type": "policy_document",
        }

    def print_policy(self) -> None:
        pol = self.current_version()
        print(f"\n  Information Security Policy v{pol.version}")
        print(f"  Effective: {pol.effective_date}  |  Next review: {pol.next_review}")
        print(f"  Approved by: {pol.approved_by}  |  Reviewed by: {', '.join(pol.reviewed_by)}\n")
        for s in pol.sections:
            print(f"  {s['id']}. {s['title']}")
            print(f"     {s['content'][:100]}...")
