import { CATALOG_ENTRIES, EXPERIENCE_CATEGORY_ORDER } from "@aether/shared";

/**
 * Public /integrations directory — DERIVED VIEW of the canonical catalog.
 *
 * THIS MODULE IS NOT A SECOND TAXONOMY.
 *
 * The canonical source of truth for Aether's connectable integrations is the
 * generated TypeScript mirror `packages/shared/connector-taxonomy.ts`
 * (WS-6 tail, generated by scripts/generate_connector_taxonomy.py — never
 * hand-edited), which mirrors the backend one-customer catalog
 *
 *   Backend Architecture/aether-backend/shared/integration_contracts/
 *     catalog.py      (ProviderManifest catalog ALL_MANIFESTS four-group union)
 *     experience.py   (ExperienceCategory + category→experience projection)
 *
 * The directory rows below are PROJECTED at module load from that mirror's
 * CATALOG_ENTRIES, not transcribed: this file selects the two catalog groups
 * Aether's public surfaces advertise as connectable and maps each selected
 * entry onto a ConnectorRecord. Family ids, display names, engineering
 * categories, the customer-facing experience_category projection, readiness
 * state, authentication and webhook support all come from the shared entry —
 * there is no hand-copied vocabulary left in this file to drift.
 *
 * SCOPE OF THE PUBLIC SUBSET — the two catalog groups Aether's public surfaces
 * advertise as connectable, every entry at the availability state the runtime
 * records (all `credential_waiting`, never shown as live):
 *
 *   1. the 21 inbound connector-registry families (BYOD ingestion, `product:
 *      'ingestion', capability: 'connector'`, in registry insertion order), and
 *   2. the 7 measurement ad-platform families (`product: 'ads', capability:
 *      'metrics'`, in catalog AD_FAMILIES order), exposed by the catalog as
 *      product "ads" / capability "metrics".
 *
 * Deliberately NOT listed here:
 *   - payment rails (observe-only financial rails; several share a family name
 *     with an ingestion connector, e.g. stripe, so listing both would read as a
 *     duplicate to a public visitor), and
 *   - deferred credit bureaus (SCAFFOLDED, tenant-invisible, enabled in no
 *     environment — catalog.py §26). Neither group has a public connect story
 *     yet, and the directory never fabricates capability behind a name.
 *
 * READINESS POSTURE — same bar as the R1/R2 snapshot: every projected entry is
 * credential-gated (catalog readiness_state maps to CredentialReadiness
 * "credential_waiting" → level 3 in the catalog, visible in local/integration,
 * never staging/production). None is replay/sandbox/partner-validated today, so
 * none is rendered as live.
 *
 * MARKETING OVERLAY — the catalog carries no public marketing voice. Two fields
 * are therefore provided locally, keyed by canonical family id in PUBLIC_COPY:
 * the directory's description copy and its `pull` posture (the catalog mirrors
 * webhook support and incremental sync but not the descriptor's supports_pull).
 * A catalog family that enters either public group without a copy entry fails
 * loudly at module load rather than shipping a descriptionless row, and
 * connectors.test.ts pins the subset snapshot so it cannot silently grow.
 *
 * Experience labels, readiness labels and the boundary alias map (aliases.py,
 * ADR-0009) are also marketing/compatibility voice pinned below; the alias map
 * still resolves legacy names to canonical catalog families and never invents a
 * row of its own.
 */

export type ConnectorAuth = "api_key" | "webhook_only" | "none";

/** Real readiness tokens (marketing subset of shared/certification/readiness.py
 * CredentialReadiness). The full backend vocabulary also carries
 * credential_supplied / connection_validated / suspended / revoked, but no
 * catalog family is in those states today, so they are not in this union. */
export type ConnectorReadiness =
  | "scaffolded"
  | "disabled"
  | "degraded"
  | "credential_waiting"
  | "replay_validated"
  | "sandbox_validated"
  | "partner_live";

/**
 * Customer-facing experience categories — re-exported verbatim from the
 * generated mirror (shared/integration_contracts/experience.py
 * ExperienceCategory order, ADR-0010). Wire tokens are stable and are the
 * vocabulary the tenant Settings→Integrations surface groups by; the public
 * directory derives one experience per connector from the catalog entry's own
 * experience_category projection, never a local rule table.
 */
export type ExperienceToken = (typeof EXPERIENCE_CATEGORY_ORDER)[number];

/** Canonical experience categories in experience.py's stable presentation order
 * (EXPERIENCE_CATEGORY_ORDER). Only tokens actually present in the subset
 * surface as facets, but the full canonical set is exported so a label lookup
 * or a handoff never invents a token. */
export const EXPERIENCE_CATEGORIES: readonly ExperienceToken[] =
  EXPERIENCE_CATEGORY_ORDER;

/** Public marketing voice for each experience token (UX copy invariants §6:
 * Integrations, Connect, Manage, Advertising, Commerce & Revenue, Customer &
 * CRM, Communications, Analytics & Behavior…). Engineering category tokens stay
 * internal; this label map is what surfaces publicly. */
export const EXPERIENCE_LABELS: Readonly<Record<ExperienceToken, string>> = {
  advertising_campaigns: "Advertising",
  commerce_revenue: "Commerce & Revenue",
  crm_customer: "Customer & CRM",
  communications_lifecycle: "Communications",
  analytics_behavior: "Analytics & Behavior",
  social_community: "Social",
  customer_support: "Customer support",
  work_operations: "Work & operations",
};

export interface ConnectorRecord {
  /** Canonical catalog family id (connector_type / ad family), e.g. 'stripe',
   * 'google_ads' — read from the shared catalog entry. The unified catalog keys
   * on these ids — never a legacy alias (twitter_ads resolves to x_ads,
   * google_analytics to ga4, …). */
  readonly id: string;
  /** Public display label — the catalog's display_name (descriptor label /
   * catalog AD_DISPLAY_NAMES). */
  readonly name: string;
  /** Canonical engineering category token the catalog entry carries
   * (ConnectorCategory literal or "ad_platform"), kept as the catalog's token,
   * never surfaced as the primary public grouping. */
  readonly category: string;
  /** Public marketing copy (PUBLIC_COPY overlay — the catalog carries no
   * description voice). The observe-only comms sentence ("Aether never sends
   * through this connector.") is part of the honest copy and is preserved. */
  readonly description: string;
  /** Authentication token projected by the catalog entry's `authentication`
   * field (webhook_and_not-pull → 'webhook_only'; requires_secret → 'api_key';
   * else 'none'). Ad platforms are token-paste 'api_key' (no Aether-driven
   * OAuth yet). */
  readonly auth: ConnectorAuth;
  /** supports_pull — the descriptor does not project onto a catalog field, so
   * this posture is part of the marketing overlay (see module docstring). */
  readonly pull: boolean;
  /** supports_webhook — projected from the catalog entry's
   * `webhooks_supported`. */
  readonly webhook: boolean;
  /** Readiness token mapped from the catalog entry's `readiness_state` (see
   * module docstring). */
  readonly status: ConnectorReadiness;
  /** Every listed family is read-inbound: Aether reads provider activity in and
   * never pushes outbound today. */
  readonly dataDirection: "inbound";
  /** Customer-facing experience projected by the catalog entry's
   * `experience_category` (never hand-assigned per record). */
  readonly experience: ExperienceToken;
}

/** Marketing voice the catalog does not carry, keyed by canonical family id.
 * `pull` mirrors the descriptor's supports_pull posture for the family; the
 * catalog mirrors webhook support and incremental sync but not supports_pull.
 * Every public-subset family must have an entry here or module load throws. */
type PublicCopy = {
  readonly description: string;
  readonly pull: boolean;
};

const PUBLIC_COPY: Readonly<Record<string, PublicCopy>> = {
  slack: {
    description:
      "Ingest Slack messages, reactions, and channel activity as graph signals.",
    pull: false,
  },
  webhook: {
    description: "Ingest events from any system via an HMAC-signed webhook.",
    pull: false,
  },
  shopify: {
    description: "Ingest Shopify orders, customers, and checkout events.",
    pull: true,
  },
  stripe: {
    description:
      "Ingest Stripe payment, invoice, and subscription events as graph signals.",
    pull: false,
  },
  hubspot: {
    description:
      "Ingest HubSpot contacts, companies, and deals, and observe HubSpot Marketing Hub email engagement. Aether never sends through this connector (ADR-C1).",
    pull: true,
  },
  salesforce: {
    description: "Ingest Salesforce leads, accounts, and opportunities.",
    pull: true,
  },
  klaviyo: {
    description:
      "Observe Klaviyo email campaigns, flows, messages, and engagement events. Aether never sends through this connector.",
    pull: true,
  },
  segment: {
    description: "Ingest Segment track/identify/page events.",
    pull: false,
  },
  posthog: {
    description: "Ingest PostHog product-usage events and persons.",
    pull: true,
  },
  ga4: {
    description: "Ingest GA4 events via the Data API (pull).",
    pull: true,
  },
  jira: {
    description: "Ingest Jira issue and workflow events.",
    pull: true,
  },
  linear: {
    description: "Ingest Linear issues and comments.",
    pull: false,
  },
  zendesk: {
    description: "Ingest Zendesk ticket and support events.",
    pull: true,
  },
  intercom: {
    description: "Ingest Intercom conversations and contacts.",
    pull: true,
  },
  dune: {
    description:
      "Read-only on-chain analytics provider. Pulls query results into Bronze for governed promotion to Silver.",
    pull: true,
  },
  sendgrid: {
    description:
      "Observe Twilio SendGrid email delivery and engagement events via the Event Webhook (ECDSA-verified). Aether never sends through this connector.",
    pull: false,
  },
  customerio: {
    description:
      "Observe Customer.io email delivery and engagement events via reporting webhooks (HMAC-verified). Aether never sends through this connector.",
    pull: false,
  },
  mailchimp: {
    description:
      "Observe Mailchimp list lifecycle events via Marketing webhooks. Aether never sends through this connector.",
    pull: false,
  },
  postmark: {
    description:
      "Observe Postmark transactional email delivery and engagement events via webhooks. Aether never sends through this connector.",
    pull: false,
  },
  iterable: {
    description:
      "Observe Iterable email delivery and engagement events via signed webhooks and the REST event export API. Aether never sends through this connector.",
    pull: true,
  },
  braze: {
    description:
      "Observe Braze email delivery and engagement via REST pull (hard bounces, unsubscribes) and pushed message events. Aether never sends through this connector.",
    pull: true,
  },
  // ── Measurement ad-platform families (catalog product "ads") ─────────────
  // Each pulls normalized campaign spend into the canonical measurement spend
  // store. Readiness credential_waiting → level 3 (code complete, offline-safe,
  // awaiting tenant credentials) — never >=4. Token-paste api_key
  // authentication (no Aether-driven OAuth yet); incremental daily spend pull
  // on a last_sync_date cursor; no webhooks. These are measurement/monitoring
  // connectors: Aether reads ad spend in, never posts or edits campaigns
  // through them.
  google_ads: {
    description:
      "Pull normalized Google Ads campaign spend into Aether campaign measurement. Credential-gated: no live sync runs until you add Google Ads account credentials. Aether never posts or edits campaigns through this connector.",
    pull: true,
  },
  meta_ads: {
    description:
      "Pull normalized Meta Ads campaign spend into Aether campaign measurement. Credential-gated: no live sync runs until you add a Meta Ads access token. Aether never posts or edits campaigns through this connector.",
    pull: true,
  },
  tiktok_ads: {
    description:
      "Pull normalized TikTok Ads campaign spend into Aether campaign measurement. Credential-gated: no live sync runs until you add a TikTok Ads access token. Aether never posts or edits campaigns through this connector.",
    pull: true,
  },
  linkedin_ads: {
    description:
      "Pull normalized LinkedIn Ads campaign spend into Aether campaign measurement. Credential-gated: no live sync runs until you add a LinkedIn Ads access token. Aether never posts or edits campaigns through this connector.",
    pull: true,
  },
  x_ads: {
    description:
      "Pull normalized X (Twitter) Ads campaign spend into Aether campaign measurement. Credential-gated: no live sync runs until you add an X Ads access token. Aether never posts or edits campaigns through this connector.",
    pull: true,
  },
  reddit_ads: {
    description:
      "Pull normalized Reddit Ads campaign spend into Aether campaign measurement. Credential-gated: no live sync runs until you add a Reddit Ads access token. Aether never posts or edits campaigns through this connector.",
    pull: true,
  },
  microsoft_ads: {
    description:
      "Pull normalized Microsoft Advertising campaign spend into Aether campaign measurement. Credential-gated: no live sync runs until you add Microsoft Advertising credentials. Aether never posts or edits campaigns through this connector.",
    pull: true,
  },
};

type CatalogEntry = (typeof CATALOG_ENTRIES)[number];

function isExperienceToken(value: string | null): value is ExperienceToken {
  return (
    value !== null &&
    (EXPERIENCE_CATEGORY_ORDER as readonly string[]).includes(value)
  );
}

const READINESS_TOKENS: readonly ConnectorReadiness[] = [
  "scaffolded",
  "disabled",
  "degraded",
  "credential_waiting",
  "replay_validated",
  "sandbox_validated",
  "partner_live",
];

function assertReadiness(value: string): ConnectorReadiness {
  if (!(READINESS_TOKENS as readonly string[]).includes(value)) {
    throw new Error(
      `connectors.ts: catalog readiness_state "${value}" has no ConnectorReadiness token. ` +
        "Extend the readiness vocabulary in shared/certification/readiness.py and mirror it here.",
    );
  }
  return value as ConnectorReadiness;
}

function assertAuth(value: string): ConnectorAuth {
  if (value === "api_key" || value === "webhook_only" || value === "none") {
    return value;
  }
  throw new Error(
    `connectors.ts: catalog authentication "${value}" is not a public ConnectorAuth token.`,
  );
}

/** The two catalog groups the public directory advertises as connectable:
 * ingestion connectors (`product: 'ingestion', capability: 'connector'`) and
 * measurement ad platforms (`product: 'ads', capability: 'metrics'`). */
function isPublicDirectoryEntry(entry: CatalogEntry): boolean {
  if (entry.capability === "connector" && entry.product === "ingestion") {
    return true;
  }
  if (entry.product === "ads" && entry.capability === "metrics") {
    return true;
  }
  return false;
}

const PUBLIC_SUBSET_COUNT = 28; // 21 registry families + 7 measurement ad platforms

/** Project one catalog entry onto a public ConnectorRecord. Every structural
 * field is read from the shared entry; only description/pull come from the
 * marketing overlay. */
function project(entry: CatalogEntry): ConnectorRecord {
  const copy = PUBLIC_COPY[entry.family];
  if (copy === undefined) {
    throw new Error(
      `connectors.ts: catalog family "${entry.family}" entered the public directory ` +
        "subset but has no marketing PUBLIC_COPY entry. Add its description copy before it ships.",
    );
  }
  const experience = entry.experience_category;
  if (!isExperienceToken(experience)) {
    throw new Error(
      `connectors.ts: catalog family "${entry.family}" carries no public experience_category ` +
        `("${String(experience)}"). Only catalog groups with a customer-facing experience project here.`,
    );
  }
  return {
    id: entry.family,
    name: entry.display_name,
    category: entry.category,
    description: copy.description,
    auth: assertAuth(entry.authentication),
    pull: copy.pull,
    webhook: entry.webhooks_supported,
    status: assertReadiness(entry.readiness_state),
    dataDirection: "inbound",
    experience,
  };
}

const publicEntries = CATALOG_ENTRIES.filter(isPublicDirectoryEntry);
if (publicEntries.length !== PUBLIC_SUBSET_COUNT) {
  throw new Error(
    `connectors.ts: expected ${PUBLIC_SUBSET_COUNT} public connectable families in the ` +
      `catalog mirror, found ${publicEntries.length}. Update PUBLIC_SUBSET_COUNT and the ` +
      "PUBLIC_COPY overlay (and connectors.test.ts) together when the catalog grows a public group.",
  );
}

/**
 * The public connectable subset, in the mirror's stable order: the 21
 * connector-registry families in registry insertion order, then the 7
 * measurement ad-platform families in catalog.py's AD_FAMILIES order.
 */
export const CONNECTORS: readonly ConnectorRecord[] = publicEntries.map(
  (entry) => project(entry),
);

/** Canonical family ids present in the public subset — the whitelist a public
 * page may hand off with (a connect deep-link never names a fabricated family). */
export const DIRECTORY_FAMILY_IDS: readonly string[] = CONNECTORS.map(
  (connector) => connector.id,
);

/** Sorted unique engineering categories present in the subset (catalog
 * category tokens). Kept for the directory's technical "Filter by category"
 * facet. */
export const CONNECTOR_CATEGORIES: readonly string[] = [
  ...new Set(CONNECTORS.map((connector) => connector.category)),
].sort();

/** Experience tokens actually present in the subset, in canonical
 * EXPERIENCE_CATEGORIES order (facets are built from real tokens, never an
 * imagined list). */
export const PRESENT_EXPERIENCES: readonly ExperienceToken[] =
  EXPERIENCE_CATEGORIES.filter((experience) =>
    CONNECTORS.some((connector) => connector.experience === experience),
  );

/** Short public label per real readiness token. credential_waiting — the state
 * every listed family is in today — reads as "Credentials required". */
export const CONNECTOR_STATUS_LABELS: Readonly<
  Record<ConnectorReadiness, string>
> = {
  scaffolded: "Scaffolded",
  disabled: "Disabled",
  degraded: "Degraded",
  credential_waiting: "Credentials required",
  replay_validated: "Replay validated",
  sandbox_validated: "Sandbox validated",
  partner_live: "Partner live",
};

/**
 * Boundary family aliases (shared/integration_contracts/aliases.py FAMILY_ALIASES,
 * ADR-0009) → canonical catalog family. The directory keys on canonical families
 * only; this mirror lets public copy/docs resolve a legacy name without
 * fabricating a row for it.
 */
export const FAMILY_ALIASES: Readonly<Record<string, string>> = {
  // shared/providers/categories.py AD_PLATFORM + recommendations emit
  // twitter_ads; the measurement runtime and catalog family is x_ads.
  twitter_ads: "x_ads",
  // Legacy naming for the Google Analytics 4 inbound connector (registry keys
  // it ga4).
  google_analytics: "ga4",
  // shared/providers marketing alias; the measurement runtime is meta_ads.
  facebook_ads: "meta_ads",
  // Campaign normalization maps bing/bing_ads → microsoft_ads; catalog family is
  // microsoft_ads.
  bing_ads: "microsoft_ads",
};

/** Public ad-platform family names with NO backed runtime (aliases.py
 * ALIAS_ONLY_FAMILIES): naming them is fine, claiming capability behind them is
 * not. None appears as a directory row — asserting that is a drift test. */
export const ALIAS_ONLY_FAMILIES: readonly string[] = [
  "snapchat_ads",
  "pinterest_ads",
];

/** Resolve a boundary family id to its canonical catalog family (mirror of
 * aliases.py canonical_family_id). */
export function canonicalFamilyId(id: string): string {
  const token = (id ?? "").trim().toLowerCase();
  if (token === "") return token;
  return FAMILY_ALIASES[token] ?? token;
}

/** Look up one connectable family by its canonical family id. */
export function findConnector(id: string): ConnectorRecord | undefined {
  return CONNECTORS.find((connector) => connector.id === id);
}
