import { Link } from 'react-router-dom';

interface Artifact {
  slug: string;
  title: string;
  description: string;
  source: string;
}

const ARTIFACTS: Artifact[] = [
  {
    slug: 'events',
    title: 'Event Registry',
    description: 'All trackable events grouped by family, with consent-purpose mapping.',
    source: 'packages/shared/events.ts',
  },
  {
    slug: 'env',
    title: 'Environment Variables',
    description: 'Categorized env vars with defaults and production-required flags.',
    source: '.env.example',
  },
  {
    slug: 'plans',
    title: 'Plans & Pricing',
    description: 'Subscription plans, quotas, overage rates, and billing cadences.',
    source: 'Backend Architecture/aether-backend/shared/plans/catalog.py',
  },
  {
    slug: 'providers',
    title: 'Provider Matrix',
    description: 'External data providers organized by integration category.',
    source: 'Backend Architecture/aether-backend/shared/providers/categories.py',
  },
];

export default function ArtifactsIndex() {
  return (
    <div style={{ maxWidth: 860, margin: '2rem auto', padding: '0 1.5rem', fontFamily: 'system-ui, sans-serif' }}>
      <header style={{ marginBottom: '2rem', borderBottom: '1px solid #e5e7eb', paddingBottom: '1rem' }}>
        <h1 style={{ margin: 0, fontSize: '1.75rem', fontWeight: 700 }}>Generated Reference</h1>
        <p style={{ color: '#6b7280', marginTop: '0.5rem', marginBottom: 0 }}>
          These tables are extracted directly from repo source and regenerated by{' '}
          <code style={{ fontFamily: 'monospace', fontSize: '0.85em' }}>scripts/docs_extract/run_all.py</code> on every build. They never drift from the code.
        </p>
      </header>

      <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'grid', gap: '0.75rem' }}>
        {ARTIFACTS.map((a) => (
          <li
            key={a.slug}
            style={{
              border: '1px solid #e5e7eb',
              borderRadius: 8,
              padding: '1rem',
              background: '#fff',
            }}
          >
            <Link
              to={`/artifacts/${a.slug}`}
              style={{ color: '#1d4ed8', textDecoration: 'none', fontWeight: 600, fontSize: '1rem' }}
            >
              {a.title}
            </Link>
            <p style={{ color: '#374151', margin: '0.35rem 0 0.5rem 0', fontSize: '0.875rem' }}>
              {a.description}
            </p>
            <div style={{ fontFamily: 'monospace', fontSize: '0.72rem', color: '#9ca3af' }}>
              source: {a.source}
            </div>
          </li>
        ))}
      </ul>
    </div>
  );
}
