"""GENERATED — do not edit. Source: shared/computation/registry.py.

Regenerate with ``python scripts/generate_computation_registry.py``.
Parity is asserted by tests/computation/test_registry_parity.py and
scripts/validate_computation_substrate.py.
"""

from __future__ import annotations

import json

REGISTRY_DIGEST = "65fec24e24cec837e91c1416973106e0fb1983345102dca967b3580c5838bda6"

_DEFINITIONS_JSON = """
[
  {
    "aggregation_type": "non_aggregatable",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "deterministic_metric",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "operational",
    "default_grain": null,
    "definition_id": "behavioral.source_freshness",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Whether a source is stale vs a dynamic freshness SLA (unknown when timestamp absent).",
    "display_name": "Source Freshness",
    "domain": "behavioral",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "tristate",
    "owner": "behavioral@aether",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/computation/test_behavioral_staleness.py"
    ],
    "timezone_policy": "context",
    "unit": "tristate",
    "valid_range_high": null,
    "valid_range_low": null,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "sum",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "observed_fact",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "financial",
    "default_grain": null,
    "definition_id": "billing.metered_usage",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Billable metered quantity over a period; bounded reads disclose truncation.",
    "display_name": "Metered Usage",
    "domain": "billing",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "quantity",
    "owner": "billing@aether",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/computation/test_billing_usage.py"
    ],
    "timezone_policy": "context",
    "unit": "unit",
    "valid_range_high": null,
    "valid_range_low": null,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "ratio_of_sums",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "deterministic_metric",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "financial",
    "default_grain": null,
    "definition_id": "campaign.aov",
    "definition_version": "1",
    "dependency_definitions": [
      "campaign.attributed_gross_revenue",
      "campaign.attributed_conversions"
    ],
    "description": "attributed_gross_purchase_revenue / attributed_purchase_conversions",
    "display_name": "AOV",
    "domain": "campaign",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "rate",
    "owner": "growth-analytics",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/computation/test_campaign_definitions.py"
    ],
    "timezone_policy": "context",
    "unit": "currency",
    "valid_range_high": null,
    "valid_range_low": null,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "sum",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "observed_fact",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "financial",
    "default_grain": null,
    "definition_id": "campaign.attributed_contribution_revenue",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Contribution revenue credited to the campaign.",
    "display_name": "Attributed Contribution Revenue",
    "domain": "campaign",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "money",
    "owner": "growth-analytics",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/computation/test_campaign_definitions.py"
    ],
    "timezone_policy": "context",
    "unit": "currency",
    "valid_range_high": null,
    "valid_range_low": null,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "sum",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "allocated_value",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "customer_facing",
    "default_grain": null,
    "definition_id": "campaign.attributed_conversions",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Fractional conversions credited under the active attribution model.",
    "display_name": "Attributed Conversions",
    "domain": "campaign",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "fractional_count",
    "owner": "growth-analytics",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/computation/test_campaign_definitions.py"
    ],
    "timezone_policy": "context",
    "unit": "count",
    "valid_range_high": null,
    "valid_range_low": null,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "sum",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "observed_fact",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "financial",
    "default_grain": null,
    "definition_id": "campaign.attributed_gross_revenue",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Gross revenue credited to the campaign.",
    "display_name": "Attributed Gross Revenue",
    "domain": "campaign",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "money",
    "owner": "growth-analytics",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/computation/test_campaign_definitions.py"
    ],
    "timezone_policy": "context",
    "unit": "currency",
    "valid_range_high": null,
    "valid_range_low": null,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "sum",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "observed_fact",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "financial",
    "default_grain": null,
    "definition_id": "campaign.attributed_net_revenue",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Net revenue credited to the campaign.",
    "display_name": "Attributed Net Revenue",
    "domain": "campaign",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "money",
    "owner": "growth-analytics",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/computation/test_campaign_definitions.py"
    ],
    "timezone_policy": "context",
    "unit": "currency",
    "valid_range_high": null,
    "valid_range_low": null,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "ratio_of_sums",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "deterministic_metric",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "financial",
    "default_grain": null,
    "definition_id": "campaign.cac",
    "definition_version": "1",
    "dependency_definitions": [
      "campaign.total_cost",
      "campaign.first_party_conversions"
    ],
    "description": "acquisition_cost / distinct_first_time_customers",
    "display_name": "CAC",
    "domain": "campaign",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "rate",
    "owner": "growth-analytics",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/computation/test_campaign_definitions.py"
    ],
    "timezone_policy": "context",
    "unit": "currency",
    "valid_range_high": null,
    "valid_range_low": null,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "sum",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "observed_fact",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "customer_facing",
    "default_grain": null,
    "definition_id": "campaign.clicks",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Ad clicks.",
    "display_name": "Clicks",
    "domain": "campaign",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "integer_count",
    "owner": "growth-analytics",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/computation/test_campaign_definitions.py"
    ],
    "timezone_policy": "context",
    "unit": "count",
    "valid_range_high": null,
    "valid_range_low": null,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "ratio_of_sums",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "deterministic_metric",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "financial",
    "default_grain": null,
    "definition_id": "campaign.contribution_roas",
    "definition_version": "1",
    "dependency_definitions": [
      "campaign.attributed_contribution_revenue",
      "campaign.total_cost"
    ],
    "description": "attributed_contribution_revenue / total_cost",
    "display_name": "Contribution ROAS",
    "domain": "campaign",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "rate",
    "owner": "growth-analytics",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/computation/test_campaign_definitions.py"
    ],
    "timezone_policy": "context",
    "unit": "ratio",
    "valid_range_high": null,
    "valid_range_low": null,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "ratio_of_sums",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "deterministic_metric",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "customer_facing",
    "default_grain": null,
    "definition_id": "campaign.conversion_rate",
    "definition_version": "1",
    "dependency_definitions": [
      "campaign.attributed_conversions",
      "campaign.clicks"
    ],
    "description": "attributed_conversions / eligible_clicks",
    "display_name": "Conversion Rate",
    "domain": "campaign",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 30,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "rate",
    "owner": "growth-analytics",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/computation/test_campaign_definitions.py"
    ],
    "timezone_policy": "context",
    "unit": "ratio",
    "valid_range_high": 1.0,
    "valid_range_low": 0.0,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "ratio_of_sums",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "deterministic_metric",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "financial",
    "default_grain": null,
    "definition_id": "campaign.cpa",
    "definition_version": "1",
    "dependency_definitions": [
      "campaign.total_cost",
      "campaign.attributed_conversions"
    ],
    "description": "eligible_total_cost / attributed_conversions",
    "display_name": "CPA",
    "domain": "campaign",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "rate",
    "owner": "growth-analytics",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/computation/test_campaign_definitions.py"
    ],
    "timezone_policy": "context",
    "unit": "currency",
    "valid_range_high": null,
    "valid_range_low": null,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "ratio_of_sums",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "deterministic_metric",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "financial",
    "default_grain": null,
    "definition_id": "campaign.cpc",
    "definition_version": "1",
    "dependency_definitions": [
      "campaign.media_spend",
      "campaign.clicks"
    ],
    "description": "media_spend / clicks",
    "display_name": "CPC",
    "domain": "campaign",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "rate",
    "owner": "growth-analytics",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/computation/test_campaign_definitions.py"
    ],
    "timezone_policy": "context",
    "unit": "currency",
    "valid_range_high": null,
    "valid_range_low": null,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "ratio_of_sums",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "deterministic_metric",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "financial",
    "default_grain": null,
    "definition_id": "campaign.cpm",
    "definition_version": "1",
    "dependency_definitions": [
      "campaign.media_spend",
      "campaign.impressions"
    ],
    "description": "media_spend / impressions * 1000",
    "display_name": "CPM",
    "domain": "campaign",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "rate",
    "owner": "growth-analytics",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/computation/test_campaign_definitions.py"
    ],
    "timezone_policy": "context",
    "unit": "currency",
    "valid_range_high": null,
    "valid_range_low": null,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "ratio_of_sums",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "deterministic_metric",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "customer_facing",
    "default_grain": null,
    "definition_id": "campaign.ctr",
    "definition_version": "1",
    "dependency_definitions": [
      "campaign.clicks",
      "campaign.impressions"
    ],
    "description": "clicks / impressions",
    "display_name": "CTR",
    "domain": "campaign",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 30,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "rate",
    "owner": "growth-analytics",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/computation/test_campaign_definitions.py"
    ],
    "timezone_policy": "context",
    "unit": "ratio",
    "valid_range_high": 1.0,
    "valid_range_low": 0.0,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "sum",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "observed_fact",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "customer_facing",
    "default_grain": null,
    "definition_id": "campaign.engagements",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Engagement interactions.",
    "display_name": "Engagements",
    "domain": "campaign",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "integer_count",
    "owner": "growth-analytics",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/computation/test_campaign_definitions.py"
    ],
    "timezone_policy": "context",
    "unit": "count",
    "valid_range_high": null,
    "valid_range_low": null,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "sum",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "observed_fact",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "customer_facing",
    "default_grain": null,
    "definition_id": "campaign.first_party_conversions",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Conversions observed first-party by Aether.",
    "display_name": "First-Party Conversions",
    "domain": "campaign",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "integer_count",
    "owner": "growth-analytics",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/computation/test_campaign_definitions.py"
    ],
    "timezone_policy": "context",
    "unit": "count",
    "valid_range_high": null,
    "valid_range_low": null,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "ratio_of_sums",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "deterministic_metric",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "financial",
    "default_grain": null,
    "definition_id": "campaign.gross_roas",
    "definition_version": "1",
    "dependency_definitions": [
      "campaign.attributed_gross_revenue",
      "campaign.media_spend"
    ],
    "description": "attributed_gross_revenue / media_spend",
    "display_name": "Gross ROAS",
    "domain": "campaign",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "rate",
    "owner": "growth-analytics",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/computation/test_campaign_definitions.py"
    ],
    "timezone_policy": "context",
    "unit": "ratio",
    "valid_range_high": null,
    "valid_range_low": null,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "sum",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "observed_fact",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "customer_facing",
    "default_grain": null,
    "definition_id": "campaign.impressions",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Ad impressions served.",
    "display_name": "Impressions",
    "domain": "campaign",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "integer_count",
    "owner": "growth-analytics",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/computation/test_campaign_definitions.py"
    ],
    "timezone_policy": "context",
    "unit": "count",
    "valid_range_high": null,
    "valid_range_low": null,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "sum",
    "allocation_policy": "attribution_credit",
    "code_commit": null,
    "computation_kind": "allocated_value",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "financial",
    "default_grain": null,
    "definition_id": "campaign.journey_allocated_cost",
    "definition_version": "1",
    "dependency_definitions": [
      "campaign.total_cost"
    ],
    "description": "Campaign cost allocated to a journey under an allocation policy. ESTIMATED/allocated \u2014 never observed. Conserves total campaign cost.",
    "display_name": "Journey Allocated Cost",
    "domain": "journey",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "money",
    "owner": "growth-analytics",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/computation/test_campaign_definitions.py",
      "tests/computation/test_allocation.py"
    ],
    "timezone_policy": "context",
    "unit": "currency",
    "valid_range_high": null,
    "valid_range_low": null,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "sum",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "observed_fact",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "financial",
    "default_grain": null,
    "definition_id": "campaign.media_spend",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Provider media spend in native currency.",
    "display_name": "Media Spend",
    "domain": "campaign",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "money",
    "owner": "growth-analytics",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/computation/test_campaign_definitions.py"
    ],
    "timezone_policy": "context",
    "unit": "currency",
    "valid_range_high": null,
    "valid_range_low": null,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "ratio_of_sums",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "deterministic_metric",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "financial",
    "default_grain": null,
    "definition_id": "campaign.net_roas",
    "definition_version": "1",
    "dependency_definitions": [
      "campaign.attributed_net_revenue",
      "campaign.total_cost"
    ],
    "description": "attributed_net_revenue / total_cost",
    "display_name": "Net ROAS",
    "domain": "campaign",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "rate",
    "owner": "growth-analytics",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/computation/test_campaign_definitions.py"
    ],
    "timezone_policy": "context",
    "unit": "ratio",
    "valid_range_high": null,
    "valid_range_low": null,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "sum",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "observed_fact",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "customer_facing",
    "default_grain": null,
    "definition_id": "campaign.provider_conversions",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Conversions as reported by the ad provider.",
    "display_name": "Provider Conversions",
    "domain": "campaign",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "integer_count",
    "owner": "growth-analytics",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/computation/test_campaign_definitions.py"
    ],
    "timezone_policy": "context",
    "unit": "count",
    "valid_range_high": null,
    "valid_range_low": null,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "sum",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "observed_fact",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "financial",
    "default_grain": null,
    "definition_id": "campaign.total_cost",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Media spend plus fees.",
    "display_name": "Total Cost",
    "domain": "campaign",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "money",
    "owner": "growth-analytics",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/computation/test_campaign_definitions.py"
    ],
    "timezone_policy": "context",
    "unit": "currency",
    "valid_range_high": null,
    "valid_range_low": null,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "sum",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "deterministic_metric",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "customer_facing",
    "default_grain": null,
    "definition_id": "cluster.economics",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Decimal rollup of member revenue/spend; absent member economics are unknown, not 0.",
    "display_name": "Cluster Economics (USD)",
    "domain": "cluster",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "money",
    "owner": "cluster@aether",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/computation/"
    ],
    "timezone_policy": "context",
    "unit": "currency",
    "valid_range_high": null,
    "valid_range_low": null,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "non_aggregatable",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "heuristic_score",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "access_control",
    "default_grain": null,
    "definition_id": "fraud.risk",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Rule/detector heuristic risk in [0,100]; evaluation failure fails closed to review. NOT a probability.",
    "display_name": "Fraud Risk (heuristic)",
    "domain": "fraud",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "heuristic_score",
    "owner": "fraud@aether",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/computation/test_fraud_failclosed.py"
    ],
    "timezone_policy": "context",
    "unit": "score",
    "valid_range_high": 100.0,
    "valid_range_low": 0.0,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "sum",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "observed_fact",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "customer_facing",
    "default_grain": null,
    "definition_id": "measurement.attributed_conversions",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Conversions credited under the active attribution model.",
    "display_name": "Attributed Conversions",
    "domain": "measurement",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "integer_count",
    "owner": "measurement-integrity",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/unit/test_measurement_results_repo.py"
    ],
    "timezone_policy": "context",
    "unit": "count",
    "valid_range_high": null,
    "valid_range_low": 0.0,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "sum",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "observed_fact",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "customer_facing",
    "default_grain": null,
    "definition_id": "measurement.campaign_cac",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Customer acquisition cost for a campaign.",
    "display_name": "Campaign Cac",
    "domain": "measurement",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "integer_count",
    "owner": "measurement-integrity",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/unit/test_measurement_results_repo.py"
    ],
    "timezone_policy": "context",
    "unit": "usd",
    "valid_range_high": null,
    "valid_range_low": 0.0,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "sum",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "observed_fact",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "customer_facing",
    "default_grain": null,
    "definition_id": "measurement.campaign_ltv",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Customer lifetime value attributed to a campaign.",
    "display_name": "Campaign Ltv",
    "domain": "measurement",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "integer_count",
    "owner": "measurement-integrity",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/unit/test_measurement_results_repo.py"
    ],
    "timezone_policy": "context",
    "unit": "usd",
    "valid_range_high": null,
    "valid_range_low": 0.0,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "ratio_of_sums",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "deterministic_metric",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "customer_facing",
    "default_grain": null,
    "definition_id": "measurement.campaign_roas",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Return on ad spend for a campaign.",
    "display_name": "Campaign Roas",
    "domain": "measurement",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "rate",
    "owner": "measurement-integrity",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/unit/test_measurement_results_repo.py"
    ],
    "timezone_policy": "context",
    "unit": "ratio",
    "valid_range_high": null,
    "valid_range_low": 0.0,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "sum",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "observed_fact",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "customer_facing",
    "default_grain": null,
    "definition_id": "measurement.campaign_spend",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Media and allocated cost spent on a campaign.",
    "display_name": "Campaign Spend",
    "domain": "measurement",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "integer_count",
    "owner": "measurement-integrity",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/unit/test_measurement_results_repo.py"
    ],
    "timezone_policy": "context",
    "unit": "usd",
    "valid_range_high": null,
    "valid_range_low": 0.0,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "ratio_of_sums",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "deterministic_metric",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "customer_facing",
    "default_grain": null,
    "definition_id": "measurement.conversion_rate",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Share of journeys that reached a conversion.",
    "display_name": "Conversion Rate",
    "domain": "measurement",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 30,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "rate",
    "owner": "measurement-integrity",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/unit/test_measurement_results_repo.py"
    ],
    "timezone_policy": "context",
    "unit": "ratio",
    "valid_range_high": 1.0,
    "valid_range_low": 0.0,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "sum",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "observed_fact",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "customer_facing",
    "default_grain": null,
    "definition_id": "measurement.costs",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Total costs incurred over the measurement window.",
    "display_name": "Costs",
    "domain": "measurement",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "integer_count",
    "owner": "measurement-integrity",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/unit/test_measurement_results_repo.py"
    ],
    "timezone_policy": "context",
    "unit": "usd",
    "valid_range_high": null,
    "valid_range_low": null,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "ratio_of_sums",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "deterministic_metric",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "customer_facing",
    "default_grain": null,
    "definition_id": "measurement.email_click_rate",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Share of delivered campaign messages with a qualified click.",
    "display_name": "Email Click Rate",
    "domain": "measurement",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 30,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "rate",
    "owner": "measurement-integrity",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/unit/test_measurement_results_repo.py"
    ],
    "timezone_policy": "context",
    "unit": "ratio",
    "valid_range_high": 1.0,
    "valid_range_low": 0.0,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "ratio_of_sums",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "deterministic_metric",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "customer_facing",
    "default_grain": null,
    "definition_id": "measurement.email_open_rate",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Share of delivered campaign messages with a qualified open.",
    "display_name": "Email Open Rate",
    "domain": "measurement",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 30,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "rate",
    "owner": "measurement-integrity",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/unit/test_measurement_results_repo.py"
    ],
    "timezone_policy": "context",
    "unit": "ratio",
    "valid_range_high": 1.0,
    "valid_range_low": 0.0,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "ratio_of_sums",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "deterministic_metric",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "customer_facing",
    "default_grain": null,
    "definition_id": "measurement.email_reply_rate",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Share of delivered campaign messages with a human reply.",
    "display_name": "Email Reply Rate",
    "domain": "measurement",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 30,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "rate",
    "owner": "measurement-integrity",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/unit/test_measurement_results_repo.py"
    ],
    "timezone_policy": "context",
    "unit": "ratio",
    "valid_range_high": 1.0,
    "valid_range_low": 0.0,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "sum",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "observed_fact",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "customer_facing",
    "default_grain": null,
    "definition_id": "measurement.exposure",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Observed economic exposure over the measurement window.",
    "display_name": "Exposure",
    "domain": "measurement",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "integer_count",
    "owner": "measurement-integrity",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/unit/test_measurement_results_repo.py"
    ],
    "timezone_policy": "context",
    "unit": "usd",
    "valid_range_high": null,
    "valid_range_low": null,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "sum",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "observed_fact",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "customer_facing",
    "default_grain": null,
    "definition_id": "measurement.gross_value",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Gross economic value observed over the window.",
    "display_name": "Gross Value",
    "domain": "measurement",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "integer_count",
    "owner": "measurement-integrity",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/unit/test_measurement_results_repo.py"
    ],
    "timezone_policy": "context",
    "unit": "usd",
    "valid_range_high": null,
    "valid_range_low": null,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "ratio_of_sums",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "deterministic_metric",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "customer_facing",
    "default_grain": null,
    "definition_id": "measurement.journey_completion_rate",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Share of started journeys that completed.",
    "display_name": "Journey Completion Rate",
    "domain": "measurement",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 20,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "rate",
    "owner": "measurement-integrity",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/unit/test_measurement_results_repo.py"
    ],
    "timezone_policy": "context",
    "unit": "ratio",
    "valid_range_high": 1.0,
    "valid_range_low": 0.0,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "sum",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "observed_fact",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "customer_facing",
    "default_grain": null,
    "definition_id": "measurement.ltv",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Customer lifetime value over the measurement window.",
    "display_name": "Ltv",
    "domain": "measurement",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "integer_count",
    "owner": "measurement-integrity",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/unit/test_measurement_results_repo.py"
    ],
    "timezone_policy": "context",
    "unit": "usd",
    "valid_range_high": null,
    "valid_range_low": null,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "ratio_of_sums",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "deterministic_metric",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "customer_facing",
    "default_grain": null,
    "definition_id": "measurement.machine_event_rate",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Share of campaign communication events classified as machine generated.",
    "display_name": "Machine Event Rate",
    "domain": "measurement",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 30,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "rate",
    "owner": "measurement-integrity",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/unit/test_measurement_results_repo.py"
    ],
    "timezone_policy": "context",
    "unit": "ratio",
    "valid_range_high": 1.0,
    "valid_range_low": 0.0,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "ratio_of_sums",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "deterministic_metric",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "customer_facing",
    "default_grain": null,
    "definition_id": "measurement.margin",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Profit margin ratio over the measurement window.",
    "display_name": "Margin",
    "domain": "measurement",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "rate",
    "owner": "measurement-integrity",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/unit/test_measurement_results_repo.py"
    ],
    "timezone_policy": "context",
    "unit": "ratio",
    "valid_range_high": null,
    "valid_range_low": null,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "sum",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "observed_fact",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "customer_facing",
    "default_grain": null,
    "definition_id": "measurement.net_value",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Net economic value observed over the window.",
    "display_name": "Net Value",
    "domain": "measurement",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "integer_count",
    "owner": "measurement-integrity",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/unit/test_measurement_results_repo.py"
    ],
    "timezone_policy": "context",
    "unit": "usd",
    "valid_range_high": null,
    "valid_range_low": null,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "sum",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "observed_fact",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "customer_facing",
    "default_grain": null,
    "definition_id": "measurement.refunds",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Refunds issued over the measurement window.",
    "display_name": "Refunds",
    "domain": "measurement",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "integer_count",
    "owner": "measurement-integrity",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/unit/test_measurement_results_repo.py"
    ],
    "timezone_policy": "context",
    "unit": "usd",
    "valid_range_high": null,
    "valid_range_low": null,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "sum",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "observed_fact",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "customer_facing",
    "default_grain": null,
    "definition_id": "measurement.revenue",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Attributed revenue over the measurement window.",
    "display_name": "Revenue",
    "domain": "measurement",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "money",
    "owner": "measurement-integrity",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/unit/test_measurement_results_repo.py"
    ],
    "timezone_policy": "context",
    "unit": "currency",
    "valid_range_high": null,
    "valid_range_low": 0.0,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "sum",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "observed_fact",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "customer_facing",
    "default_grain": null,
    "definition_id": "measurement.touchpoints",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Distinct marketing touchpoints observed in the window.",
    "display_name": "Touchpoints",
    "domain": "measurement",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "integer_count",
    "owner": "measurement-integrity",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/unit/test_measurement_results_repo.py"
    ],
    "timezone_policy": "context",
    "unit": "count",
    "valid_range_high": null,
    "valid_range_low": 0.0,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "non_aggregatable",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "statistical_estimate",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "operational",
    "default_grain": null,
    "definition_id": "ml.prediction",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Model probability in [0,1]; cache key binds tenant+feature digest+consent.",
    "display_name": "ML Prediction (probability)",
    "domain": "ml",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "probability",
    "owner": "ml@aether",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/computation/test_ml_cache_key.py"
    ],
    "timezone_policy": "context",
    "unit": "probability",
    "valid_range_high": 1.0,
    "valid_range_low": 0.0,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "non_aggregatable",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "deterministic_metric",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "financial",
    "default_grain": null,
    "definition_id": "pnl.realized",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "FIFO realized P&L with opening lots; missing basis => insufficient_data.",
    "display_name": "Realized P&L (USD)",
    "domain": "financial",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "money",
    "owner": "pnl@aether",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/computation/test_pnl_semantics.py"
    ],
    "timezone_policy": "context",
    "unit": "currency",
    "valid_range_high": null,
    "valid_range_low": null,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "non_aggregatable",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "observed_fact",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "financial",
    "default_grain": null,
    "definition_id": "pnl.tvl_change",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Balance-snapshot delta (deposits+withdrawals+price). NOT P&L; a flow, not performance.",
    "display_name": "TVL Change (USD)",
    "domain": "financial",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "money",
    "owner": "pnl@aether",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/computation/test_pnl_semantics.py"
    ],
    "timezone_policy": "context",
    "unit": "currency",
    "valid_range_high": null,
    "valid_range_low": null,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "non_aggregatable",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "heuristic_score",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "access_control",
    "default_grain": null,
    "definition_id": "trust.agent_delegation",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Vector composite where automation is expected/unpenalized; weights transactional integrity + reliability + evidence freshness for delegating authority. NOT calibrated.",
    "display_name": "Agent Delegation Trust (heuristic)",
    "domain": "trust",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "heuristic_score",
    "owner": "trust@aether",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/computation/test_trust_vector.py"
    ],
    "timezone_policy": "context",
    "unit": "score",
    "valid_range_high": 1.0,
    "valid_range_low": 0.0,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "non_aggregatable",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "heuristic_score",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "access_control",
    "default_grain": null,
    "definition_id": "trust.composite",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Weighted heuristic composite in [0,1]; absent risk evidence => low prior + coverage. NOT calibrated.",
    "display_name": "Trust Composite (heuristic)",
    "domain": "trust",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "heuristic_score",
    "owner": "trust@aether",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/computation/test_trust_evidence.py"
    ],
    "timezone_policy": "context",
    "unit": "score",
    "valid_range_high": 1.0,
    "valid_range_low": 0.0,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "non_aggregatable",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "heuristic_score",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "financial",
    "default_grain": null,
    "definition_id": "trust.reward_eligibility",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Vector composite that penalizes automation and requires identity assurance; gates payouts. NOT calibrated.",
    "display_name": "Reward Eligibility Trust (heuristic)",
    "domain": "trust",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "heuristic_score",
    "owner": "trust@aether",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/computation/test_trust_vector.py"
    ],
    "timezone_policy": "context",
    "unit": "score",
    "valid_range_high": 1.0,
    "valid_range_low": 0.0,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "non_aggregatable",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "heuristic_score",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "access_control",
    "default_grain": null,
    "definition_id": "trust.vector",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "Six governed heuristic dimensions (identity_assurance, transaction_integrity, behavioral_reliability, automation_likelihood [trust-INVERTED], source_coverage, evidence_recency); each carries value+coverage. Absence => neutral/low prior, never 0.",
    "display_name": "Governed Trust Vector (heuristic)",
    "domain": "trust",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "heuristic_score",
    "owner": "trust@aether",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/computation/test_trust_vector.py"
    ],
    "timezone_policy": "context",
    "unit": "score",
    "valid_range_high": 1.0,
    "valid_range_low": 0.0,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "non_aggregatable",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "deterministic_metric",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "financial",
    "default_grain": null,
    "definition_id": "value.net_ltv",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "gross_ltv - cost; unknown cost => unknown (null), never gross.",
    "display_name": "Net LTV (USD)",
    "domain": "financial",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "money",
    "owner": "value@aether",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/value/test_tvl_ltv_portfolio_account.py"
    ],
    "timezone_policy": "context",
    "unit": "currency",
    "valid_range_high": null,
    "valid_range_low": null,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "non_aggregatable",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "deterministic_metric",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "financial",
    "default_grain": null,
    "definition_id": "value.net_tvl",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "gross_tvl - borrowed; unpriced debt => partial, never inflated.",
    "display_name": "Net TVL (USD)",
    "domain": "financial",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "money",
    "owner": "value@aether",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/value/test_tvl_ltv_portfolio_account.py"
    ],
    "timezone_policy": "context",
    "unit": "currency",
    "valid_range_high": null,
    "valid_range_low": null,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  },
  {
    "aggregation_type": "non_aggregatable",
    "allocation_policy": null,
    "code_commit": null,
    "computation_kind": "deterministic_metric",
    "consent_purposes": [],
    "correction_policy": "supersede",
    "data_classification": null,
    "decision_impact_class": "financial",
    "default_grain": null,
    "definition_id": "value.net_worth",
    "definition_version": "1",
    "dependency_definitions": [],
    "description": "total_portfolio_usd - liabilities_usd; unpriced liabilities => partial, never inflated.",
    "display_name": "Net Worth (USD)",
    "domain": "financial",
    "event_time_field": null,
    "executor_reference": null,
    "executor_type": "python",
    "feature_contract_reference": null,
    "late_data_policy": "restate_window",
    "lifecycle_state": "active",
    "minimum_coverage": null,
    "minimum_sample_size": 1,
    "model_reference": null,
    "null_policy": "null_not_zero",
    "optional_inputs": [],
    "output_type": "money",
    "owner": "value@aether",
    "permitted_consumers": [],
    "precision": null,
    "reconciliation_policy": null,
    "required_inputs": [],
    "rounding_policy": "half_up",
    "scale": null,
    "scope_dimensions": [],
    "sql_digest": null,
    "supported_grains": [],
    "tests": [
      "tests/value/test_tvl_ltv_portfolio_account.py"
    ],
    "timezone_policy": "context",
    "unit": "currency",
    "valid_range_high": null,
    "valid_range_low": null,
    "window_semantics": null,
    "zero_policy": "evidence_backed"
  }
]
"""

GENERATED_DEFINITIONS = json.loads(_DEFINITIONS_JSON)


def definition_ids() -> list[str]:
    return [d["definition_id"] for d in GENERATED_DEFINITIONS]


__all__ = ["REGISTRY_DIGEST", "GENERATED_DEFINITIONS", "definition_ids"]
