# DO NOT EDIT — generated from packages/shared/contracts/rights-authority-registry.json
# Run: python scripts/generate_contracts.py
# Contract version: 1.0.0

RIGHTS_AUTHORITY_CONTRACT_VERSION = '1.0.0'
RIGHTS_CLASSES: frozenset[str] = frozenset(['tenant_contributed_data', 'tenant_confidential_intelligence', 'aether_computational_artifact', 'olympus_sourced_data', 'olympus_generalized_intelligence', 'platform_operational_data', 'retained_compliance_record'])
RIGHTS_ACTIONS: frozenset[str] = frozenset(['ingest', 'store', 'read', 'graph_mutate', 'derive', 'train', 'evaluate', 'aggregate', 'disclose', 'export', 'retain', 'delete', 'operate_kyber'])
RIGHTS_DECISION_OUTCOMES: frozenset[str] = frozenset(['allow', 'deny', 'allow_with_obligations', 'pending_review', 'unavailable'])
RIGHTS_PROFILES: frozenset[str] = frozenset(['legacy_restricted', 'secure_tenant', 'collaborative_learning', 'strategic_data_exchange'])
RIGHTS_TRANSFORMS: frozenset[str] = frozenset(['feature_extraction', 'embedding', 'model_evaluation', 'model_training', 'aggregation', 'deidentification', 'promote_to_olympus_generalized_graph', 'export', 'recomputation', 'deletion'])
RIGHTS_ACTIVATION_STATES: frozenset[str] = frozenset(['rights_pending', 'rights_review', 'rights_active', 'rights_restricted', 'rights_revoked'])

RIGHTS_ACTION_DEFINITIONS: dict[str, dict] = {'ingest': {'id': 'ingest', 'label': 'Ingest', 'requiresEnvelope': False, 'requiresSourceGrant': True}, 'store': {'id': 'store', 'label': 'Store', 'requiresEnvelope': True, 'requiresSourceGrant': True}, 'read': {'id': 'read', 'label': 'Read', 'requiresEnvelope': True, 'requiresSourceGrant': False}, 'graph_mutate': {'id': 'graph_mutate', 'label': 'Mutate graph', 'requiresEnvelope': True, 'requiresSourceGrant': False}, 'derive': {'id': 'derive', 'label': 'Derive', 'requiresEnvelope': True, 'requiresSourceGrant': False}, 'train': {'id': 'train', 'label': 'Train', 'requiresEnvelope': True, 'requiresSourceGrant': True}, 'evaluate': {'id': 'evaluate', 'label': 'Evaluate', 'requiresEnvelope': True, 'requiresSourceGrant': True}, 'aggregate': {'id': 'aggregate', 'label': 'Aggregate', 'requiresEnvelope': True, 'requiresSourceGrant': True}, 'disclose': {'id': 'disclose', 'label': 'Disclose', 'requiresEnvelope': True, 'requiresSourceGrant': False}, 'export': {'id': 'export', 'label': 'Export', 'requiresEnvelope': True, 'requiresSourceGrant': False}, 'retain': {'id': 'retain', 'label': 'Retain', 'requiresEnvelope': True, 'requiresSourceGrant': False}, 'delete': {'id': 'delete', 'label': 'Delete', 'requiresEnvelope': True, 'requiresSourceGrant': False}, 'operate_kyber': {'id': 'operate_kyber', 'label': 'Operate Kyber', 'requiresEnvelope': True, 'requiresSourceGrant': False}}
RIGHTS_PROFILE_DEFINITIONS: dict[str, dict] = {'legacy_restricted': {'id': 'legacy_restricted', 'allowedActions': ['read', 'delete', 'retain'], 'reusable': False}, 'secure_tenant': {'id': 'secure_tenant', 'allowedActions': ['ingest', 'store', 'read', 'graph_mutate', 'derive', 'evaluate', 'export', 'retain', 'delete'], 'reusable': False}, 'collaborative_learning': {'id': 'collaborative_learning', 'allowedActions': ['ingest', 'store', 'read', 'graph_mutate', 'derive', 'train', 'evaluate', 'aggregate', 'export', 'retain', 'delete'], 'reusable': True}, 'strategic_data_exchange': {'id': 'strategic_data_exchange', 'allowedActions': ['ingest', 'store', 'read', 'graph_mutate', 'derive', 'train', 'evaluate', 'aggregate', 'disclose', 'export', 'retain', 'delete', 'operate_kyber'], 'reusable': True}}
RIGHTS_TRANSFORM_DEFINITIONS: dict[str, dict] = {'feature_extraction': {'id': 'feature_extraction', 'inputClasses': ['tenant_contributed_data', 'tenant_confidential_intelligence'], 'outputClass': 'aether_computational_artifact', 'requiresApproval': False, 'requiresEvidence': ['lineage']}, 'embedding': {'id': 'embedding', 'inputClasses': ['tenant_contributed_data', 'tenant_confidential_intelligence'], 'outputClass': 'aether_computational_artifact', 'requiresApproval': False, 'requiresEvidence': ['lineage', 'retention']}, 'model_evaluation': {'id': 'model_evaluation', 'inputClasses': ['tenant_contributed_data', 'tenant_confidential_intelligence', 'aether_computational_artifact'], 'outputClass': 'aether_computational_artifact', 'requiresApproval': True, 'requiresEvidence': ['lineage', 'training_rights']}, 'model_training': {'id': 'model_training', 'inputClasses': ['tenant_contributed_data', 'tenant_confidential_intelligence', 'aether_computational_artifact'], 'outputClass': 'aether_computational_artifact', 'requiresApproval': True, 'requiresEvidence': ['lineage', 'training_rights', 'revocation_strategy']}, 'aggregation': {'id': 'aggregation', 'inputClasses': ['tenant_contributed_data', 'tenant_confidential_intelligence'], 'outputClass': 'tenant_confidential_intelligence', 'requiresApproval': False, 'requiresEvidence': ['lineage', 'aggregate_threshold']}, 'deidentification': {'id': 'deidentification', 'inputClasses': ['tenant_contributed_data', 'tenant_confidential_intelligence'], 'outputClass': 'olympus_generalized_intelligence', 'requiresApproval': True, 'requiresEvidence': ['lineage', 'privacy_test', 'reidentification_test', 'aggregate_threshold']}, 'promote_to_olympus_generalized_graph': {'id': 'promote_to_olympus_generalized_graph', 'inputClasses': ['tenant_confidential_intelligence', 'aether_computational_artifact'], 'outputClass': 'olympus_generalized_intelligence', 'requiresApproval': True, 'requiresEvidence': ['lineage', 'privacy_test', 'reidentification_test', 'aggregate_threshold', 'release_proof']}, 'export': {'id': 'export', 'inputClasses': ['tenant_contributed_data', 'tenant_confidential_intelligence', 'aether_computational_artifact'], 'outputClass': 'tenant_confidential_intelligence', 'requiresApproval': False, 'requiresEvidence': ['lineage', 'recipient']}, 'recomputation': {'id': 'recomputation', 'inputClasses': ['tenant_contributed_data', 'tenant_confidential_intelligence', 'aether_computational_artifact'], 'outputClass': 'aether_computational_artifact', 'requiresApproval': False, 'requiresEvidence': ['lineage', 'revocation_strategy']}, 'deletion': {'id': 'deletion', 'inputClasses': ['tenant_contributed_data', 'tenant_confidential_intelligence', 'aether_computational_artifact', 'olympus_generalized_intelligence'], 'outputClass': 'retained_compliance_record', 'requiresApproval': False, 'requiresEvidence': ['lineage', 'deletion_receipt']}}
