// =============================================================================
// Aether SDK — EVENT QUEUE (BATCH, FLUSH, RETRY, OFFLINE PERSISTENCE)
// Updated for multi-VM Web3 event types
// =============================================================================

import type { AetherEvent, RetryConfig, ConsentState, BatchHealth } from '../types';
import { storage } from '../utils';
import { EVENT_CONSENT_PURPOSE } from './generated-consent-map';

export type { BatchHealth } from '../types';

const QUEUE_STORAGE_KEY = 'event_queue';
const MAX_STORED_EVENTS = 1000;
const SDK_VERSION = '8.12.0'; // synchronized by scripts/bump-sdk-version.sh and scripts/validate_sdk_release_alignment.py

/**
 * A non-retryable ingestion failure (a non-429 4xx): the batch is malformed or
 * rejected and will never succeed on retry, so it is dropped (with onError)
 * instead of being returned to the queue head where it would block every later
 * event behind it forever.
 */
class TerminalIngestError extends Error {
  constructor(public readonly status: number, message: string) {
    super(message);
    this.name = 'TerminalIngestError';
  }
}

interface QueueConfig {
  endpoint: string;
  apiKey: string;
  batchSize: number;
  flushInterval: number;
  maxQueueSize: number;
  retry: Required<RetryConfig>;
  headers: Record<string, string>;
  onError?: (error: Error, events: AetherEvent[]) => void;
  /** Called after each batch send attempt with round-trip latency and success. */
  onAttempt?: (latencyMs: number, success: boolean) => void;
  /**
   * Called after each processed batch with per-batch health counters
   * (accepted / duplicate / rejected / dropped_by_consent / queue_depth).
   */
  onBatchResult?: (health: BatchHealth) => void;
}

const DEFAULT_RETRY: Required<RetryConfig> = {
  maxRetries: 3,
  baseDelay: 1000,
  maxDelay: 30000,
  backoffMultiplier: 2,
};

/** Counters parsed directly from the /v1/batch response body. */
interface IngestCounters {
  accepted: number;
  duplicate: number;
  rejected: number;
}

/**
 * Sensitive property keys scrubbed locally before an event leaves the client.
 * The event->consent-purpose map is registry-derived and imported from
 * ./generated-consent-map (generated by scripts/generate_contracts.py from
 * packages/shared/contracts/event-registry.json) — never hand-maintained here.
 */
const SENSITIVE_KEYS = new Set([
  'privatekey', 'private_key', 'seedphrase', 'seed_phrase', 'mnemonic',
  'secret', 'secretkey', 'secret_key', 'password', 'pin',
  'cardnumber', 'card_number', 'pan', 'cvv', 'cvc', 'cvv2',
  'paymenttoken', 'payment_token', 'authcode', 'auth_code',
]);


/**
 * Depth cap for the recursive scrubber. Real analytics payloads are shallow; a
 * cap keeps a pathologically deep (or adversarial) object from exhausting the
 * call stack. Cycles are handled separately by the ancestor-path guard.
 */
const MAX_SCRUB_DEPTH = 32;

/**
 * Recursively redact sensitive values at EVERY depth. A sensitive key buried in
 * `properties.wallet.recovery.mnemonic` or inside an array element is redacted
 * just like a top-level `mnemonic` — top-level-only scrubbing leaked nested
 * secrets. The scrub is non-mutating (returns fresh objects/arrays); the
 * ancestor `path` set replaces cycle back-references with a `[CYCLE]` marker and
 * `depth` truncates pathological nesting, so the scrubbed tree is always finite,
 * acyclic, and JSON-serializable (a surviving cycle would make the batch send's
 * `JSON.stringify` throw and silently drop every event in it).
 */
function scrubValue(value: unknown, depth: number, path: WeakSet<object>): unknown {
  if (value === null || typeof value !== 'object') return value;
  if (depth >= MAX_SCRUB_DEPTH) return '[TRUNCATED]';
  if (path.has(value as object)) return '[CYCLE]'; // back-reference to an ancestor
  path.add(value as object);
  try {
    if (Array.isArray(value)) {
      return value.map((item) => scrubValue(item, depth + 1, path));
    }
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
      out[k] = SENSITIVE_KEYS.has(k.toLowerCase())
        ? '[REDACTED]'
        : scrubValue(v, depth + 1, path);
    }
    return out;
  } finally {
    path.delete(value as object);
  }
}

function scrubSensitiveFields(props: Record<string, unknown>): Record<string, unknown> {
  return scrubValue(props, 0, new WeakSet<object>()) as Record<string, unknown>;
}

export class EventQueue {
  private queue: AetherEvent[] = [];
  private config: QueueConfig;
  private flushTimer: ReturnType<typeof setInterval> | null = null;
  private isFlushing = false;
  private isDestroyed = false;
  private consent: ConsentState | null = null;

  constructor(config: Omit<Partial<QueueConfig>, 'retry'> & Pick<QueueConfig, 'endpoint' | 'apiKey'> & { retry?: RetryConfig }) {
    this.config = {
      batchSize: config.batchSize ?? 10,
      flushInterval: config.flushInterval ?? 5000,
      maxQueueSize: config.maxQueueSize ?? 100,
      retry: { ...DEFAULT_RETRY, ...config.retry },
      headers: config.headers ?? {},
      endpoint: config.endpoint,
      apiKey: config.apiKey,
      onError: config.onError,
      onAttempt: config.onAttempt,
      onBatchResult: config.onBatchResult,
    };
    this.restoreQueue();
    this.startFlushTimer();
    this.setupLifecycleHandlers();
  }

  setConsent(consent: ConsentState): void {
    this.consent = consent;
  }

  enqueue(event: AetherEvent): void {
    if (this.isDestroyed) return;
    const safe: AetherEvent = event.properties
      ? ({ ...event, properties: scrubSensitiveFields(event.properties) } as AetherEvent)
      : event;
    this.queue.push(safe);
    if (this.queue.length >= this.config.batchSize) this.flush();
    if (this.queue.length >= this.config.maxQueueSize) this.flush();
  }

  async flush(): Promise<void> {
    if (this.isFlushing || this.queue.length === 0 || this.isDestroyed) return;

    this.isFlushing = true;
    const batch = this.queue.splice(0, this.config.batchSize);
    const allowedEvents = this.filterByConsent(batch);
    const droppedByConsent = batch.length - allowedEvents.length;

    // Consent filtering is intentional, not an ingestion failure — it is surfaced
    // as its own `dropped_by_consent` health counter, never as a send failure.
    if (allowedEvents.length === 0) {
      this.config.onBatchResult?.({
        accepted: 0,
        duplicate: 0,
        rejected: 0,
        dropped_by_consent: droppedByConsent,
        queue_depth: this.queue.length,
      });
      this.isFlushing = false;
      return;
    }

    const start = Date.now();
    try {
      const counters = await this.sendBatch(allowedEvents);
      this.config.onAttempt?.(Date.now() - start, true);
      this.config.onBatchResult?.({
        accepted: counters.accepted,
        duplicate: counters.duplicate,
        rejected: counters.rejected,
        dropped_by_consent: droppedByConsent,
        queue_depth: this.queue.length,
      });
      this.persistQueue();
    } catch (error) {
      this.config.onAttempt?.(Date.now() - start, false);
      if (error instanceof TerminalIngestError) {
        // Poison batch: drop it (surfaced via onError) rather than unshifting to
        // the head, so one permanently-rejected batch can't block the queue.
        this.persistQueue();
        this.config.onError?.(error, allowedEvents);
      } else {
        // Transient failure (5xx exhausted, rate-limit, network): return the
        // batch to the head so the next flush retries it.
        this.queue.unshift(...allowedEvents);
        this.persistQueue();
        this.config.onError?.(error as Error, allowedEvents);
      }
    } finally {
      this.isFlushing = false;
      if (this.queue.length >= this.config.batchSize) this.flush();
    }
  }

  get size(): number {
    return this.queue.length;
  }

  destroy(): void {
    this.isDestroyed = true;
    if (this.flushTimer) { clearInterval(this.flushTimer); this.flushTimer = null; }
    if (this.queue.length > 0) {
      // Persist BEFORE the beacon: sendBeacon is fire-and-forget and cannot
      // confirm delivery, so a failed keepalive send must remain recoverable
      // via restoreQueue() on the next load rather than being lost. Events
      // carry a stable id, so a re-send after a beacon that actually succeeded
      // is deduped at the backend (at-least-once beats at-most-once here).
      this.persistQueue();
      this.sendBeacon(this.queue);
    }
    this.queue = [];
  }

  // ===========================================================================
  // PRIVATE
  // ===========================================================================

  private filterByConsent(events: AetherEvent[]): AetherEvent[] {
    if (!this.consent) return events;
    const consent = this.consent;

    return events.filter((event) => {
      if ((event.type as string) === 'consent') return true;
      const purpose = EVENT_CONSENT_PURPOSE[event.type];
      if (!purpose) return false;
      return (consent as unknown as Record<string, boolean>)[purpose] === true;
    });
  }

  private async sendBatch(events: AetherEvent[], retryCount = 0): Promise<IngestCounters> {
    const payload = JSON.stringify({
      batch: events,
      sentAt: new Date().toISOString(),
      context: { library: { name: '@aether/sdk', version: SDK_VERSION } },
    });

    const response = await fetch(`${this.config.endpoint}/v1/batch`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${this.config.apiKey}`,
        'X-Aether-SDK': 'web',
        ...this.config.headers,
      },
      body: payload,
      keepalive: true,
    });

    if (!response.ok) {
      if (response.status >= 500 && retryCount < this.config.retry.maxRetries) {
        const delay = Math.min(
          this.config.retry.baseDelay * Math.pow(this.config.retry.backoffMultiplier, retryCount),
          this.config.retry.maxDelay
        );
        await this.sleep(delay);
        return this.sendBatch(events, retryCount + 1);
      }

      if (response.status === 429) {
        if (retryCount >= this.config.retry.maxRetries) {
          throw new Error('Rate limited: max retries exceeded');
        }
        const retryAfter = parseInt(response.headers.get('Retry-After') || '5', 10);
        await this.sleep(retryAfter * 1000);
        return this.sendBatch(events, retryCount + 1);
      }

      if (response.status >= 400 && response.status < 500) {
        // Non-429 4xx is a terminal rejection (malformed/poison batch): retrying
        // it forever would block the queue head. Mark it terminal so flush drops it.
        throw new TerminalIngestError(
          response.status,
          `Aether API error: ${response.status} ${response.statusText}`,
        );
      }

      throw new Error(`Aether API error: ${response.status} ${response.statusText}`);
    }

    return this.parseIngestCounters(events.length, response);
  }

  /**
   * Parse per-batch acceptance counters from the /v1/batch response body.
   * The backend BatchResponse uses `accepted` / `duplicates` / `rejected`
   * (packages/shared/ingestion-contract.ts). Falls back to treating the whole
   * batch as accepted if the body is absent or unparseable, so health reporting
   * never blocks a successful (2xx) delivery.
   */
  private async parseIngestCounters(sent: number, response: Response): Promise<IngestCounters> {
    try {
      const body = (await response.json()) as Record<string, unknown>;
      const num = (v: unknown): number | undefined =>
        typeof v === 'number' && Number.isFinite(v) ? v : undefined;
      const accepted = num(body['accepted']);
      const duplicate = num(body['duplicate']) ?? num(body['duplicates']);
      const rejected = num(body['rejected']);
      if (accepted !== undefined || duplicate !== undefined || rejected !== undefined) {
        return {
          accepted: accepted ?? 0,
          duplicate: duplicate ?? 0,
          rejected: rejected ?? 0,
        };
      }
    } catch {
      // Body missing / non-JSON — fall through to optimistic default.
    }
    return { accepted: sent, duplicate: 0, rejected: 0 };
  }

  private sendBeacon(events: AetherEvent[]): boolean {
    // Use fetch with keepalive:true instead of sendBeacon.
    // sendBeacon does not support Authorization headers, which would force
    // the API key into the URL query string — visible in proxy logs and referrer
    // headers. fetch+keepalive is supported in all modern browsers and behaves
    // identically for page-unload scenarios.
    const allowed = this.filterByConsent(events);
    if (allowed.length === 0) return true;
    const payload = JSON.stringify({
      batch: allowed,
      sentAt: new Date().toISOString(),
      context: { library: { name: '@aether/sdk', version: SDK_VERSION } },
    });
    try {
      fetch(`${this.config.endpoint}/v1/batch`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${this.config.apiKey}`,
          'X-Aether-SDK': 'web',
          ...this.config.headers,
        },
        body: payload,
        keepalive: true,
      }).catch(() => {
        // Unload flush is best-effort; silently drop if fetch fails.
        // The queue was already cleared by the caller — retries happen
        // via the persistent queue on next page load.
      });
      return true;
    } catch {
      return false;
    }
  }

  private startFlushTimer(): void {
    this.flushTimer = setInterval(() => {
      if (this.queue.length > 0) this.flush();
    }, this.config.flushInterval);
  }

  private setupLifecycleHandlers(): void {
    if (typeof window === 'undefined') return;
    window.addEventListener('visibilitychange', () => {
      if (document.visibilityState === 'hidden' && this.queue.length > 0) {
        // Persist first: the keepalive beacon is fire-and-forget, so if it fails
        // (network down, or the queue exceeds the browser's ~64KB keepalive cap)
        // the events survive for restoreQueue() on the next page load.
        this.persistQueue();
        const sent = this.sendBeacon(this.queue);
        if (sent) this.queue = [];
        // If beacon rejected, leave queue intact — periodic flush will retry
      }
    });
    window.addEventListener('pagehide', () => {
      if (this.queue.length > 0) {
        this.persistQueue();
        const sent = this.sendBeacon(this.queue);
        if (sent) this.queue = [];
      }
    });
    window.addEventListener('online', () => {
      if (this.queue.length > 0) this.flush();
    });
  }

  private persistQueue(): void {
    storage.set(QUEUE_STORAGE_KEY, this.queue.slice(0, MAX_STORED_EVENTS));
  }

  private restoreQueue(): void {
    const stored = storage.get<AetherEvent[]>(QUEUE_STORAGE_KEY);
    if (stored && Array.isArray(stored)) {
      this.queue = [...stored, ...this.queue];
      storage.remove(QUEUE_STORAGE_KEY);
    }
  }

  private sleep(ms: number): Promise<void> {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }
}
