#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# Aether Platform — Staging Bootstrap
#
# One-command staging deployment. Run on any machine with Docker installed.
#
# Usage:
#   cd deploy/staging
#   ./bootstrap.sh
#
# Prerequisites:
#   - Docker and Docker Compose installed
#   - Port 8000, 8080, 5432, 6379, 9092 available
#
# What this does:
#   1. Generates production secrets (if not already set)
#   2. Starts all infrastructure (PostgreSQL, Redis, Kafka)
#   3. Starts backend API and ML serving
#   4. Validates health of all services
#   5. Creates the first admin API key
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

echo "=========================================="
echo "  Aether Staging Bootstrap"
echo "=========================================="
echo ""

# ── Step 1: Generate secrets if not set ────────────────────────────
echo "Step 1: Checking secrets..."

if [ -z "${JWT_SECRET:-}" ]; then
    export JWT_SECRET=$(python3 -c "import secrets; print(secrets.token_urlsafe(64))")
    echo "  Generated JWT_SECRET"
fi

if [ -z "${BYOK_ENCRYPTION_KEY:-}" ]; then
    export BYOK_ENCRYPTION_KEY=$(python3 -c "
try:
    from cryptography.fernet import Fernet
    print(Fernet.generate_key().decode())
except ImportError:
    import base64, os
    print(base64.urlsafe_b64encode(os.urandom(32)).decode())
")
    echo "  Generated BYOK_ENCRYPTION_KEY"
fi

export POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-aether_staging_$(python3 -c "import secrets; print(secrets.token_hex(8))")}"
export REDIS_PASSWORD="${REDIS_PASSWORD:-aether_staging_$(python3 -c "import secrets; print(secrets.token_hex(8))")}"

if [ -z "${WATERMARK_SECRET_KEY:-}" ]; then
    export WATERMARK_SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
    echo "  Generated WATERMARK_SECRET_KEY"
fi

if [ -z "${CANARY_SECRET_SEED:-}" ]; then
    export CANARY_SECRET_SEED=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
    echo "  Generated CANARY_SECRET_SEED"
fi

echo "  ✓ All secrets ready"
echo ""

# ── Step 2: Start infrastructure ──────────────────────────────────
echo "Step 2: Starting infrastructure..."
cd "$SCRIPT_DIR"
docker compose -f docker-compose.staging.yml up -d postgres redis zookeeper kafka

echo "  Waiting for PostgreSQL..."
until docker compose -f docker-compose.staging.yml exec -T postgres pg_isready -U aether -d aether_staging 2>/dev/null; do
    sleep 2
done
echo "  ✓ PostgreSQL ready"

echo "  Waiting for Redis..."
until docker compose -f docker-compose.staging.yml exec -T redis redis-cli -a "$REDIS_PASSWORD" ping 2>/dev/null | grep -q PONG; do
    sleep 2
done
echo "  ✓ Redis ready"

echo "  Waiting for Kafka..."
sleep 10  # Kafka needs time to elect leaders
echo "  ✓ Kafka ready"
echo ""

# ── Step 3: Start application services ────────────────────────────
echo "Step 3: Starting application services..."
docker compose -f docker-compose.staging.yml up -d backend ml-serving prometheus

echo "  Waiting for backend health..."
for i in $(seq 1 30); do
    if curl -sf http://localhost:8000/v1/health >/dev/null 2>&1; then
        echo "  ✓ Backend healthy"
        break
    fi
    if [ "$i" -eq 30 ]; then
        echo "  ✗ Backend failed to start"
        docker compose -f docker-compose.staging.yml logs backend --tail 20
        exit 1
    fi
    sleep 2
done
echo ""

# ── Step 4: Validate health ──────────────────────────────────────
echo "Step 4: Validating service health..."
HEALTH=$(curl -sf http://localhost:8000/v1/health)
echo "  Health response: $HEALTH"

DB_STATUS=$(echo "$HEALTH" | python3 -c "import sys,json; print(json.load(sys.stdin).get('dependencies',{}).get('database',{}).get('status','unknown'))" 2>/dev/null || echo "unknown")
CACHE_STATUS=$(echo "$HEALTH" | python3 -c "import sys,json; print(json.load(sys.stdin).get('dependencies',{}).get('cache',{}).get('status','unknown'))" 2>/dev/null || echo "unknown")

echo "  Database: $DB_STATUS"
echo "  Cache: $CACHE_STATUS"

if [ "$DB_STATUS" != "ok" ] || [ "$CACHE_STATUS" != "ok" ]; then
    echo "  ⚠ Some dependencies are not healthy. Check docker compose logs."
fi
echo ""

# ── Step 5: Create first API key ──────────────────────────────────
echo "Step 5: Creating first admin API key..."
# In local mode, use the stub key to create a real key
RESPONSE=$(curl -sf -X POST \
    -H "X-API-Key: ak_test_123" \
    -H "Content-Type: application/json" \
    -d '{"name":"staging-admin","tier":"enterprise","permissions":["read","write","admin","analytics","agent:manage","campaign:manage","consent:manage","billing","x402:read","x402:write"]}' \
    http://localhost:8000/v1/admin/tenants/tenant_001/api-keys 2>/dev/null || echo '{"error":"failed"}')

API_KEY=$(echo "$RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin).get('data',{}).get('api_key','FAILED'))" 2>/dev/null || echo "FAILED")

if [ "$API_KEY" != "FAILED" ]; then
    echo "  ✓ API key created: $API_KEY"
    echo "  ⚠ SAVE THIS KEY — it will not be shown again"
else
    echo "  ✗ API key creation failed. Response: $RESPONSE"
fi
echo ""

# ── Step 6: Validate endpoints ────────────────────────────────────
echo "Step 6: Smoke testing endpoints..."

echo -n "  GET /v1/metrics: "
curl -sf http://localhost:8000/v1/metrics | head -1
echo ""

echo -n "  GET /: "
curl -sf http://localhost:8000/ | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('name','?'), d.get('version','?'))" 2>/dev/null
echo ""

# ── Done ──────────────────────────────────────────────────────────
echo "=========================================="
echo "  Staging deployment complete!"
echo "=========================================="
echo ""
echo "Services:"
echo "  Backend API:    http://localhost:8000"
echo "  ML Serving:     http://localhost:8080"
echo "  Prometheus:     http://localhost:9090"
echo "  PostgreSQL:     localhost:5432"
echo "  Redis:          localhost:6379"
echo "  Kafka:          localhost:9092"
echo ""
echo "Health:           curl http://localhost:8000/v1/health"
echo "Metrics:          curl http://localhost:8000/v1/metrics"
echo "API docs:         http://localhost:8000/docs"
echo ""
echo "To stop:          docker compose -f docker-compose.staging.yml down"
echo "To view logs:     docker compose -f docker-compose.staging.yml logs -f"
