from config.compliance_config import (
    DataRole, GDPR_RIGHTS, DATA_PROTECTION_CONTROLS,
    CONSENT_CONFIG, ConsentPurpose, GDPR_DATA_STORES,
    SOC2_TRUST_CRITERIA, AUDIT_TRAILS, BREACH_CONFIG,
    PROCESSING_ACTIVITIES, CROSS_BORDER_TRANSFERS,
)
