from config.compliance_config import (
    AUDIT_TRAILS,
    BREACH_CONFIG,
    CONSENT_CONFIG,
    CROSS_BORDER_TRANSFERS,
    DATA_PROTECTION_CONTROLS,
    GDPR_DATA_STORES,
    GDPR_RIGHTS,
    PROCESSING_ACTIVITIES,
    SOC2_TRUST_CRITERIA,
    ConsentPurpose,
    DataRole,
)
