#!/usr/bin/env python3
"""Generate the TypeScript provider/category mirror — packages/shared/connector-taxonomy.ts.

Sources (read-only — canonical single source of truth, never edited here):
  Backend Architecture/aether-backend/shared/integration_contracts/catalog.py
      ALL_MANIFESTS four-group union — connectors (21) / ad-platforms (7) /
      payment-rails (5) / deferred-credit-bureaus (3). Each ProviderManifest is
      honesty-validated at import (validate_manifest), so everything projected
      here is already honest.
  Backend Architecture/aether-backend/shared/integration_contracts/experience.py
      EXPERIENCE_CATEGORIES + experience_category_for (customer-facing grouping,
      ADR-0010). The FE must never re-derive membership, so the derived
      experience→families grouping is emitted as data.

Generated output:
  packages/shared/connector-taxonomy.ts

The file also carries the connector *descriptor* taxonomy (ConnectorClass,
ConnectorRole, DataFlowDirection, LakeWritePolicy, GraphWritePolicy,
ModelTrainingEligibility, ImplementationStatus, PriorityPhase, RiskTier,
IntelligenceSourceMode/Coverage) which mirrors the connector-descriptor enums in
``services/integrations/connectors/base.py``. Those members are a stable
compatibility surface consumed via the @aether/shared barrel (e.g.
capability-state.ts), so the generator reproduces that section verbatim from a
versioned template rather than deriving it — do not hand-edit the output.

Usage:
  python scripts/generate_connector_taxonomy.py            # write the file in place
  python scripts/generate_connector_taxonomy.py --check    # exit 1 if output differs (CI gate)

Guarantees:
  - Idempotent: running twice produces identical output.
  - Deterministic: group order follows catalog.py (CONNECTOR_MANIFESTS,
    AD_MANIFESTS, PAYMENT_RAIL_MANIFESTS, DEFERRED_CREDIT_BUREAU_MANIFESTS,
    ALL_MANIFESTS); families keep catalog order; category lists are sorted.
  - Never reads the generated file as an input (except --check diffing).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BACKEND = ROOT / "Backend Architecture" / "aether-backend"
OUT_TS = ROOT / "packages" / "shared" / "connector-taxonomy.ts"

# The generator imports the real Python catalog from the backend tree.
if str(BACKEND) not in sys.path:
    sys.path.insert(0, str(BACKEND))


# ---------------------------------------------------------------------------
# Descriptor-taxonomy template (carried verbatim into the output).
#
# This block mirrors the connector-descriptor enums in
#   Backend Architecture/aether-backend/services/integrations/connectors/base.py
# plus the intelligence-source-coverage shape from services/provider_catalog.
# It predates the unified catalog and is a stable public surface on
# @aether/shared (frontend/shared/src/status/capability-state.ts imports
# ImplementationStatus through it), so the generator reproduces it unchanged.
# The catalog-derived provider/category mirror is appended below the marker.
# ---------------------------------------------------------------------------

_DESCRIPTOR_TAXONOMY_TEMPLATE = '''/**
 * Aether — Connector Taxonomy (TypeScript)
 *
 * Two sections, two sources:
 *
 *   1. DESCRIPTOR TAXONOMY (below the header) — a stable compatibility mirror
 *      of the connector-descriptor enums in
 *        Backend Architecture/aether-backend/services/integrations/connectors/base.py
 *      (ConnectorClass, ConnectorRole, ImplementationStatus, ...) plus the
 *      provider-corpus intelligence-source coverage shape. Consumed via the
 *      @aether/shared barrel; reproduced verbatim by the generator.
 *
 *   2. PROVIDER / CATEGORY MIRROR (generated) — a pure TypeScript mirror of the
 *      unified integration catalog derived from
 *        Backend Architecture/aether-backend/shared/integration_contracts/catalog.py
 *      (ALL_MANIFESTS four-group union: connectors / ad-platforms /
 *      payment-rails / deferred-credit-bureaus) and
 *        Backend Architecture/aether-backend/shared/integration_contracts/experience.py
 *      (customer-facing experience categories). Keep it in step by running the
 *      generator — never by hand-editing this file.
 *
 * DO NOT EDIT — generated by python scripts/generate_connector_taxonomy.py
 * Regenerate from the repository root (shared environment):
 *   python scripts/generate_connector_taxonomy.py
 */

// ── Connector class ────────────────────────────────────────────────────────────

export type ConnectorClass =
  | "olympus_provider"
  | "tenant_byod_data"
  | "byok_gateway"
  | "action_notifier"
  | "dual_role";

export const ConnectorClass = {
  OLYMPUS_PROVIDER: "olympus_provider" as const,
  TENANT_BYOD_DATA: "tenant_byod_data" as const,
  BYOK_GATEWAY: "byok_gateway" as const,
  ACTION_NOTIFIER: "action_notifier" as const,
  DUAL_ROLE: "dual_role" as const,
} satisfies Record<string, ConnectorClass>;

// ── Connector role ─────────────────────────────────────────────────────────────

export type ConnectorRole =
  | "data_ingestion"
  | "action_delivery"
  | "credential_gateway"
  | "enrichment_provider"
  | "webhook_receiver"
  | "sync_source"
  | "realtime_stream"
  | "batch_backfill"
  | "query_execution"
  | "warehouse_datashare"
  | "dual_role";

export const ConnectorRole = {
  DATA_INGESTION: "data_ingestion" as const,
  ACTION_DELIVERY: "action_delivery" as const,
  CREDENTIAL_GATEWAY: "credential_gateway" as const,
  ENRICHMENT_PROVIDER: "enrichment_provider" as const,
  WEBHOOK_RECEIVER: "webhook_receiver" as const,
  SYNC_SOURCE: "sync_source" as const,
  REALTIME_STREAM: "realtime_stream" as const,
  BATCH_BACKFILL: "batch_backfill" as const,
  QUERY_EXECUTION: "query_execution" as const,
  WAREHOUSE_DATASHARE: "warehouse_datashare" as const,
  DUAL_ROLE: "dual_role" as const,
} satisfies Record<string, ConnectorRole>;

// ── Data flow direction ────────────────────────────────────────────────────────

export type DataFlowDirection = "inbound" | "outbound" | "bidirectional" | "none";

export const DataFlowDirection = {
  INBOUND: "inbound" as const,
  OUTBOUND: "outbound" as const,
  BIDIRECTIONAL: "bidirectional" as const,
  NONE: "none" as const,
} satisfies Record<string, DataFlowDirection>;

// ── Lake write policy ──────────────────────────────────────────────────────────

export type LakeWritePolicy =
  | "never"
  | "tenant_only"
  | "olympus_baseline_eligible"
  | "olympus_baseline_allowed"
  | "quarantine_only";

export const LakeWritePolicy = {
  NEVER: "never" as const,
  TENANT_ONLY: "tenant_only" as const,
  OLYMPUS_BASELINE_ELIGIBLE: "olympus_baseline_eligible" as const,
  OLYMPUS_BASELINE_ALLOWED: "olympus_baseline_allowed" as const,
  QUARANTINE_ONLY: "quarantine_only" as const,
} satisfies Record<string, LakeWritePolicy>;

// ── Graph write policy ─────────────────────────────────────────────────────────

export type GraphWritePolicy =
  | "none"
  | "tenant_graph_only"
  | "tenant_graph_and_aggregate_eligible"
  | "olympus_graph_allowed"
  | "quarantine_only";

export const GraphWritePolicy = {
  NONE: "none" as const,
  TENANT_GRAPH_ONLY: "tenant_graph_only" as const,
  TENANT_GRAPH_AND_AGGREGATE_ELIGIBLE: "tenant_graph_and_aggregate_eligible" as const,
  OLYMPUS_GRAPH_ALLOWED: "olympus_graph_allowed" as const,
  QUARANTINE_ONLY: "quarantine_only" as const,
} satisfies Record<string, GraphWritePolicy>;

// ── Model training eligibility ─────────────────────────────────────────────────

export type ModelTrainingEligibility =
  | "never"
  | "tenant_only"
  | "aggregate_only"
  | "olympus_allowed"
  | "compliance_review_required";

export const ModelTrainingEligibility = {
  NEVER: "never" as const,
  TENANT_ONLY: "tenant_only" as const,
  AGGREGATE_ONLY: "aggregate_only" as const,
  OLYMPUS_ALLOWED: "olympus_allowed" as const,
  COMPLIANCE_REVIEW_REQUIRED: "compliance_review_required" as const,
} satisfies Record<string, ModelTrainingEligibility>;

// ── Implementation status ──────────────────────────────────────────────────────

export type ImplementationStatus =
  | "mocked_local"
  | "scaffolded"
  | "production_shaped"
  | "credential_gated"
  | "provider_live"
  | "warehouse_datashare_ready"
  | "staging_validation_required"
  | "disabled_compliance_review"
  | "deprecated";

export const ImplementationStatus = {
  MOCKED_LOCAL: "mocked_local" as const,
  SCAFFOLDED: "scaffolded" as const,
  PRODUCTION_SHAPED: "production_shaped" as const,
  CREDENTIAL_GATED: "credential_gated" as const,
  PROVIDER_LIVE: "provider_live" as const,
  WAREHOUSE_DATASHARE_READY: "warehouse_datashare_ready" as const,
  STAGING_VALIDATION_REQUIRED: "staging_validation_required" as const,
  DISABLED_COMPLIANCE_REVIEW: "disabled_compliance_review" as const,
  DEPRECATED: "deprecated" as const,
} satisfies Record<string, ImplementationStatus>;

// ── Priority phase ─────────────────────────────────────────────────────────────

export type PriorityPhase =
  | "phase_1_foundation"
  | "phase_2_enrichment"
  | "phase_3_depth"
  | "not_scheduled";

export const PriorityPhase = {
  PHASE_1_FOUNDATION: "phase_1_foundation" as const,
  PHASE_2_ENRICHMENT: "phase_2_enrichment" as const,
  PHASE_3_DEPTH: "phase_3_depth" as const,
  NOT_SCHEDULED: "not_scheduled" as const,
} satisfies Record<string, PriorityPhase>;

// ── Risk tier ──────────────────────────────────────────────────────────────────

export type RiskTier = "low" | "medium" | "high" | "restricted";

export const RiskTier = {
  LOW: "low" as const,
  MEDIUM: "medium" as const,
  HIGH: "high" as const,
  RESTRICTED: "restricted" as const,
} satisfies Record<string, RiskTier>;

// ── Intelligence source coverage ───────────────────────────────────────────────

export type IntelligenceSourceMode =
  | "baseline_only"
  | "baseline_plus_tenant_connector"
  | "baseline_plus_sdk_live"
  | "baseline_plus_tenant_connector_plus_sdk_live";

export interface IntelligenceSourceCoverage {
  source_mode: IntelligenceSourceMode;
  baseline_coverage: number;
  connector_coverage: number;
  sdk_live_coverage: number;
  identity_confidence: number;
  data_freshness_score: number;
  model_confidence: number;
  last_refreshed_at: string | null;
}
'''

# ---------------------------------------------------------------------------
# Catalog payload collection (pure projection of the Python modules)
# ---------------------------------------------------------------------------


def _load_catalog():
    from shared.certification.readiness import readiness_rank
    from shared.integration_contracts.catalog import (
        AD_MANIFESTS,
        ALL_MANIFESTS,
        CONNECTOR_MANIFESTS,
        DEFERRED_CREDIT_BUREAU_MANIFESTS,
        PAYMENT_RAIL_MANIFESTS,
    )
    from shared.integration_contracts.experience import (
        EXPERIENCE_CATEGORIES,
        experience_category_for,
    )

    return {
        "groups": [
            ("connectors", "ingestion", "connector", CONNECTOR_MANIFESTS),
            ("ad_platforms", "ads", "metrics", AD_MANIFESTS),
            ("payment_rails", "payment_rails", "observe", PAYMENT_RAIL_MANIFESTS),
            (
                "deferred_credit_bureaus",
                "credit",
                "report",
                DEFERRED_CREDIT_BUREAU_MANIFESTS,
            ),
        ],
        "all_manifests": ALL_MANIFESTS,
        "readiness_rank": readiness_rank,
        "experience_categories": EXPERIENCE_CATEGORIES,
        "experience_category_for": experience_category_for,
    }


def _ts_str(value: str) -> str:
    """A valid single-quoted TypeScript string literal for ``value``.

    ``repr()`` of a Python ``str`` is a single-quoted literal whose escapes
    (backslash, single-quote, control characters) are also valid TypeScript.
    """
    return repr(str(value))


def _entry_row(manifest, experience_category_for) -> str:
    """One TypeScript object literal row for a catalog entry."""
    experience = experience_category_for(manifest)
    envs = manifest.availability.environments
    enabled = [
        name
        for name, flag in (
            ("local", envs.local),
            ("integration", envs.integration),
            ("staging", envs.staging),
            ("production", envs.production),
        )
        if flag
    ]
    fields = [
        f"    key: {_ts_str(manifest.identity_key)},",
        f"    family: {_ts_str(manifest.provider_family)},",
        f"    product: {_ts_str(manifest.product_id)},",
        f"    capability: {_ts_str(manifest.capability_id)},",
        f"    display_name: {_ts_str(manifest.display_name)},",
        f"    category: {_ts_str(manifest.category)},",
        f"    experience_category: {_ts_str(experience.value) if experience is not None else 'null'},",
        f"    readiness_state: {_ts_str(manifest.readiness.state.value)},",
        f"    readiness_level: {manifest.readiness.level},",
        f"    tenant_self_service: {str(manifest.availability.tenant_self_service).lower()},",
        f"    environments: {repr(enabled)},",
        f"    authentication: {_ts_str(manifest.authentication.type)},",
        f"    accounts_discovery: {str(manifest.accounts.discovery_supported).lower()},",
        f"    accounts_selection_required: {str(manifest.accounts.selection_required).lower()},",
        f"    webhooks_supported: {str(manifest.webhooks.supported).lower()},",
        f"    sync_incremental: {str(manifest.sync.incremental).lower()},",
        f"    sync_initial_backfill: {str(manifest.sync.initial_backfill).lower()},",
    ]
    return "  {\n" + "\n".join(fields) + "\n  },"


def _build() -> str:
    c = _load_catalog()

    lines: list[str] = []
    lines.append(_DESCRIPTOR_TAXONOMY_TEMPLATE.rstrip() + "\n")

    # ── generated mirror header
    lines.append("\n// ════════════════════════════════════════════════════════════════════")
    lines.append("// Provider / category mirror — GENERATED from the Python catalog")
    lines.append("// Source of truth: shared/integration_contracts/catalog.py (ALL_MANIFESTS")
    lines.append("// four-group union) + shared/integration_contracts/experience.py.")
    lines.append("// Regenerate: python scripts/generate_connector_taxonomy.py")
    lines.append("// ════════════════════════════════════════════════════════════════════\n")

    # catalog group id union + order
    group_ids = [g[0] for g in c["groups"]]
    group_id_union = " | ".join(_ts_str(g) for g in group_ids)
    lines.append("export type CatalogGroupId =")
    lines.append(f"  | {group_id_union};")
    lines.append("")
    lines.append("export const CATALOG_GROUP_ORDER = [")
    for g in group_ids:
        lines.append(f"  {_ts_str(g)},")
    lines.append("] as const;")
    lines.append("")

    # per-group family const arrays + derived union types
    group_meta: list[str] = []
    for group_id, product, capability, manifests in c["groups"]:
        families = [m.provider_family for m in manifests]
        categories = sorted({m.category for m in manifests})

        const_name = {
            "connectors": "CONNECTOR_FAMILIES",
            "ad_platforms": "AD_PLATFORM_FAMILIES",
            "payment_rails": "PAYMENT_RAIL_FAMILIES",
            "deferred_credit_bureaus": "DEFERRED_CREDIT_BUREAU_FAMILIES",
        }[group_id]
        type_name = {
            "connectors": "ConnectorFamily",
            "ad_platforms": "AdPlatformFamily",
            "payment_rails": "PaymentRailFamily",
            "deferred_credit_bureaus": "DeferredCreditBureauFamily",
        }[group_id]

        lines.append(f"// Families in the {group_id} group (catalog order, {len(families)}).")
        lines.append(f"export const {const_name} = [")
        for fam in families:
            lines.append(f"  {_ts_str(fam)} as const,")
        lines.append("] as const;")
        lines.append("")
        lines.append(f"export type {type_name} = (typeof {const_name})[number];")
        lines.append("")
        lines.append(f"export const {const_name}_COUNT = {len(families)} as const;")
        lines.append("")

        group_meta.append(
            {
                "id": group_id,
                "const": const_name,
                "product": product,
                "capability": capability,
                "families": families,
                "categories": categories,
                "count": len(families),
            }
        )

    # flattened family list
    lines.append("export const ALL_CATALOG_FAMILIES = [")
    for meta in group_meta:
        for fam in meta["families"]:
            lines.append(f"  {_ts_str(fam)} as const,")
    lines.append("] as const;")
    lines.append("")
    lines.append(
        "export const ALL_CATALOG_FAMILIES_COUNT = "
        f"{sum(m['count'] for m in group_meta)} as const;"
    )
    lines.append("")

    # group metadata const
    lines.append("export const CATALOG_GROUPS = [")
    for meta in group_meta:
        fam_lits = ", ".join(_ts_str(f) for f in meta["families"])
        cat_lits = ", ".join(_ts_str(x) for x in meta["categories"])
        lines.append("  {")
        lines.append(f"    id: {_ts_str(meta['id'])},")
        lines.append(f"    product: {_ts_str(meta['product'])},")
        lines.append(f"    capability: {_ts_str(meta['capability'])},")
        lines.append(f"    familyConst: {_ts_str(meta['const'])},")
        lines.append(f"    count: {meta['count']},")
        lines.append(f"    families: [{fam_lits}],")
        lines.append(f"    categories: [{cat_lits}],")
        lines.append("  },")
    lines.append("] as const;")
    lines.append("")

    # type aliases over the unions
    fam_unions = []
    cat_values: set[str] = set()
    for meta in group_meta:
        fam_unions.append(f"(typeof {meta['const']})[number]")
        cat_values.update(meta["categories"])
    lines.append(
        "export type CatalogProviderFamily = "
        + " | ".join(fam_unions)
        + ";"
    )
    lines.append("")
    lines.append("export const CATALOG_CATEGORIES = [")
    for cat in sorted(cat_values):
        lines.append(f"  {_ts_str(cat)},")
    lines.append("] as const;")
    lines.append("")
    lines.append("export type CatalogCategory = (typeof CATALOG_CATEGORIES)[number];")
    lines.append("")

    # readiness states present across the catalog
    states_present = sorted({m.readiness.state.value for m in c["all_manifests"]})
    lines.append(
        "// CredentialReadiness ladder states actually present across ALL_MANIFESTS "
        "(honest mirror, never a parallel ladder)."
    )
    lines.append("export const CATALOG_READINESS_STATES_PRESENT = [")
    for s in states_present:
        lines.append(f"  {_ts_str(s)} as const,")
    lines.append("] as const;")
    lines.append("")

    # full catalog entry list (ALL_MANIFESTS order, already collision-checked)
    lines.append("export const CATALOG_ENTRIES = [")
    for manifest in c["all_manifests"]:
        lines.append(_entry_row(manifest, c["experience_category_for"]))
    lines.append("] as const;")
    lines.append("")
    lines.append(f"export const CATALOG_ENTRIES_COUNT = {len(c['all_manifests'])} as const;")
    lines.append("")

    # experience category order + derived grouping
    lines.append("// Customer-facing experience categories (ADR-0010), presentation order.")
    lines.append("export const EXPERIENCE_CATEGORY_ORDER = [")
    for cat in c["experience_categories"]:
        lines.append(f"  {_ts_str(cat.value)} as const,")
    lines.append("] as const;")
    lines.append("")
    lines.append("export type ExperienceCategory = (typeof EXPERIENCE_CATEGORY_ORDER)[number];")
    lines.append("")

    # experience → families derived grouping (single source of truth server-side;
    # the FE groups from this emitted map, never re-derives membership).
    experience_families: dict[str, list[str]] = {}
    for group_id, _product, _cap, manifests in c["groups"]:
        for m in manifests:
            exp = c["experience_category_for"](m)
            bucket = exp.value if exp is not None else None
            experience_families.setdefault(str(bucket), []).append(m.provider_family)
    lines.append(
        "// Derived experience → provider-family grouping over ALL_MANIFESTS. The "
        "'None' bucket holds families that derive to no customer-facing experience."
    )
    lines.append("export const EXPERIENCE_CATEGORY_FAMILIES = {")
    for bucket in sorted(experience_families, key=lambda k: (k == "None", k or "")):
        fams = experience_families[bucket]
        fam_lits = ", ".join(_ts_str(f) for f in fams)
        key_lit = "null" if bucket == "None" else _ts_str(bucket)
        lines.append(f"  {key_lit}: [{fam_lits}],")
    lines.append("} as const;")
    lines.append("")

    # Interfaces describing the emitted shapes (for ergonomic consumers).
    lines.append("export interface CatalogEntryRow {")
    lines.append("  key: string;")
    lines.append("  family: string;")
    lines.append("  product: string;")
    lines.append("  capability: string;")
    lines.append("  display_name: string;")
    lines.append("  category: string;")
    lines.append("  experience_category: string | null;")
    lines.append("  readiness_state: string;")
    lines.append("  readiness_level: number;")
    lines.append("  tenant_self_service: boolean;")
    lines.append("  environments: readonly string[];")
    lines.append("  authentication: string;")
    lines.append("  accounts_discovery: boolean;")
    lines.append("  accounts_selection_required: boolean;")
    lines.append("  webhooks_supported: boolean;")
    lines.append("  sync_incremental: boolean;")
    lines.append("  sync_initial_backfill: boolean;")
    lines.append("}")
    lines.append("")
    lines.append("export interface CatalogGroupMeta {")
    lines.append("  id: CatalogGroupId;")
    lines.append("  product: string;")
    lines.append("  capability: string;")
    lines.append("  familyConst: string;")
    lines.append("  count: number;")
    lines.append("  families: readonly string[];")
    lines.append("  categories: readonly string[];")
    lines.append("}")
    lines.append("")

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the committed connector-taxonomy.ts differs from generated output",
    )
    args = parser.parse_args()

    generated = _build()

    if args.check:
        if OUT_TS.exists() and OUT_TS.read_text(encoding="utf-8") == generated:
            print("connector-taxonomy.ts is in step with catalog.py")
            return 0
        print(
            "ERROR: packages/shared/connector-taxonomy.ts is out of step with "
            "shared/integration_contracts/catalog.py.",
            file=sys.stderr,
        )
        print(
            "Run: python scripts/generate_connector_taxonomy.py",
            file=sys.stderr,
        )
        return 1

    OUT_TS.write_text(generated, encoding="utf-8")
    print(f"wrote {OUT_TS.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
