#!/usr/bin/env python3
"""
Aether Platform — Production Secret Generator

Generates all required production secrets and outputs them in .env format.
Run once during initial deployment setup.

Usage:
    python scripts/generate_secrets.py > .env.secrets
    # Then merge into your deployment secret manager (AWS SSM, Vault, etc.)

Secrets generated:
    JWT_SECRET              — 64-byte random token for JWT signing
    BYOK_ENCRYPTION_KEY     — Fernet key for BYOK API key encryption
    WATERMARK_SECRET_KEY    — 32-byte key for ML extraction defense watermarking
    CANARY_SECRET_SEED      — 32-byte seed for canary input generation
    ORACLE_SIGNER_PRIVATE_KEY — secp256k1 private key for oracle proof signing
"""

from __future__ import annotations

import secrets
import sys


def generate_fernet_key() -> str:
    """Generate a valid Fernet key (URL-safe base64, 32 bytes)."""
    try:
        from cryptography.fernet import Fernet
        return Fernet.generate_key().decode()
    except ImportError:
        # Fallback: manual generation
        import base64
        return base64.urlsafe_b64encode(secrets.token_bytes(32)).decode()


def generate_eth_private_key() -> str:
    """Generate a secp256k1 private key and derive the address."""
    try:
        from eth_account import Account
        acct = Account.create()
        return acct.key.hex(), acct.address
    except ImportError:
        key = secrets.token_hex(32)
        return f"0x{key}", "(eth_account not installed — address unknown)"


def main() -> None:
    print("# =============================================================================")
    print("# Aether Platform — Generated Production Secrets")
    print("# Generated by: python scripts/generate_secrets.py")
    print("# STORE THESE SECURELY. DO NOT COMMIT TO VERSION CONTROL.")
    print("# =============================================================================")
    print()

    jwt_secret = secrets.token_urlsafe(64)
    print(f"JWT_SECRET={jwt_secret}")

    fernet_key = generate_fernet_key()
    print(f"BYOK_ENCRYPTION_KEY={fernet_key}")

    watermark_key = secrets.token_urlsafe(32)
    print(f"WATERMARK_SECRET_KEY={watermark_key}")

    canary_seed = secrets.token_urlsafe(32)
    print(f"CANARY_SECRET_SEED={canary_seed}")

    oracle_key, oracle_address = generate_eth_private_key()
    print(f"ORACLE_SIGNER_PRIVATE_KEY={oracle_key}")
    print(f"# Oracle signer address: {oracle_address}")

    print()
    print("# Copy these values into your secret management system.")
    print("# See docs/SECRET-ROTATION.md for rotation procedures.")


if __name__ == "__main__":
    main()
