#!/usr/bin/env python3
"""
Aether Platform — Production Secret Generator & Validator

Generate all required production secrets and output them in .env format,
or validate an existing .env file for weak/default values.

Usage:
    # Generate all secrets (pipe into your secret manager)
    python scripts/generate_secrets.py > .env.secrets

    # Validate an existing .env for default/weak secrets
    python scripts/generate_secrets.py --validate .env

    # Dry-run: show what would be generated without printing values
    python scripts/generate_secrets.py --dry-run

Secrets generated:
    JWT_SECRET                  — 64-byte URL-safe token for JWT signing
    PROVIDER_GATEWAY_ENCRYPTION_KEY — Fernet key for BYOK vault encryption
    WATERMARK_SECRET_KEY        — 32-byte key for ML extraction watermarking
    CANARY_SECRET_SEED          — 32-byte seed for canary input generation
    EXTRACTION_CANARY_SEED      — 32-byte seed for extraction mesh canary layer
    ORACLE_SIGNER_PRIVATE_KEY   — secp256k1 private key for oracle proof signing
    GRAFANA_ADMIN_PASSWORD      — Random secure password for Grafana admin
    STRIPE_WEBHOOK_SECRET       — Placeholder (obtain from Stripe Dashboard)
"""

from __future__ import annotations

import argparse
import os
import secrets
import sys
from pathlib import Path

# ──────────────────────────────────────────────────────────────────────────────
# Known insecure default values that must never appear in production.
# ──────────────────────────────────────────────────────────────────────────────
_INSECURE_DEFAULTS: set[str] = {
    "change-me-in-production",
    "aether-wm-default-change-me",
    "aether-canary-seed-change-me",
    "aether-mesh-canary-seed",
    "admin",
    "",
}

# Minimum token entropy thresholds (characters).
_MIN_SECRET_LENGTH = 32


def _generate_fernet_key() -> str:
    """Generate a valid Fernet key (URL-safe base64, 32 bytes)."""
    try:
        from cryptography.fernet import Fernet
        return Fernet.generate_key().decode()
    except ImportError:
        import base64
        return base64.urlsafe_b64encode(secrets.token_bytes(32)).decode()


def _generate_eth_private_key() -> tuple[str, str]:
    """Generate a secp256k1 private key and derive the checksum address."""
    try:
        from eth_account import Account
        acct = Account.create()
        return acct.key.hex(), acct.address
    except ImportError:
        key = secrets.token_hex(32)
        return f"0x{key}", "(eth_account not installed — address unknown)"


def _generate_all() -> dict[str, str]:
    """Return a dict of secret_name -> generated_value."""
    oracle_key, _ = _generate_eth_private_key()
    return {
        "JWT_SECRET": secrets.token_urlsafe(64),
        "PROVIDER_GATEWAY_ENCRYPTION_KEY": _generate_fernet_key(),
        "WATERMARK_SECRET_KEY": secrets.token_urlsafe(32),
        "CANARY_SECRET_SEED": secrets.token_urlsafe(32),
        "EXTRACTION_CANARY_SEED": secrets.token_urlsafe(32),
        "ORACLE_SIGNER_PRIVATE_KEY": oracle_key,
        "GRAFANA_ADMIN_PASSWORD": secrets.token_urlsafe(24),
    }


def _print_generated(dry_run: bool = False) -> None:
    print("# =============================================================================")
    print("# Aether Platform — Generated Production Secrets")
    print("# Generated by: python scripts/generate_secrets.py")
    print("# STORE THESE SECURELY. DO NOT COMMIT TO VERSION CONTROL.")
    print("# =============================================================================")
    print()

    if dry_run:
        for name in _generate_all():
            print(f"{name}=<generated — run without --dry-run to see values>")
        print()
        print("# Stripe webhook secret must be obtained from the Stripe Dashboard after")
        print("# creating a webhook endpoint pointing to: POST /v1/admin/billing/stripe/webhook")
        print("# STRIPE_WEBHOOK_SECRET=whsec_<from_stripe_dashboard>")
        return

    generated = _generate_all()
    oracle_key, oracle_address = _generate_eth_private_key()
    generated["ORACLE_SIGNER_PRIVATE_KEY"] = oracle_key

    for name, value in generated.items():
        print(f"{name}={value}")

    if oracle_address != "(eth_account not installed — address unknown)":
        print(f"# Oracle signer address: {oracle_address}")

    print()
    print("# ---------------------------------------------------------------------------")
    print("# Stripe Billing (obtain from the Stripe Dashboard)")
    print("# ---------------------------------------------------------------------------")
    print("# 1. Create a webhook endpoint in Stripe pointing to:")
    print("#      POST https://<your-domain>/v1/admin/billing/stripe/webhook")
    print("# 2. Select events: customer.subscription.*, invoice.*, checkout.session.*")
    print("# 3. Copy the signing secret shown after creation:")
    print("# STRIPE_WEBHOOK_SECRET=whsec_<from_stripe_dashboard>")
    print("#")
    print("# 4. Create Products + Prices in Stripe for P1-P4 plans, then set:")
    print("# STRIPE_PRICE_P1=price_<hobbyist_price_id>")
    print("# STRIPE_PRICE_P2=price_<professional_price_id>")
    print("# STRIPE_PRICE_P3=price_<growth_intelligence_price_id>")
    print("# STRIPE_PRICE_P4=price_<protocol_master_price_id>")
    print("#")
    print("# 5. Set your live secret key:")
    print("# STRIPE_SECRET_KEY=sk_live_<your_stripe_secret_key>")
    print()
    print("# Copy generated values into your secret management system.")
    print("# See docs/SECRET-ROTATION.md for rotation procedures.")


def _validate(env_path: str) -> bool:
    """Parse an .env file and check all required secrets for weak defaults."""
    path = Path(env_path)
    if not path.exists():
        print(f"ERROR: File not found: {env_path}", file=sys.stderr)
        return False

    env_vars: dict[str, str] = {}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, val = line.partition("=")
            # Strip inline comments
            val = val.split(" #")[0].strip()
            env_vars[key.strip()] = val

    required_in_production = [
        "JWT_SECRET",
        "PROVIDER_GATEWAY_ENCRYPTION_KEY",
        "WATERMARK_SECRET_KEY",
        "CANARY_SECRET_SEED",
        "EXTRACTION_CANARY_SEED",
        "ORACLE_SIGNER_PRIVATE_KEY",
        "GRAFANA_ADMIN_PASSWORD",
        "DATABASE_URL",
    ]

    stripe_required = [
        "STRIPE_SECRET_KEY",
        "STRIPE_WEBHOOK_SECRET",
        "STRIPE_PRICE_P1",
        "STRIPE_PRICE_P2",
        "STRIPE_PRICE_P3",
        "STRIPE_PRICE_P4",
    ]

    issues: list[str] = []

    for key in required_in_production:
        val = env_vars.get(key, "")
        if not val:
            issues.append(f"  MISSING  {key}")
        elif val in _INSECURE_DEFAULTS:
            issues.append(f"  DEFAULT  {key}  (value is a known insecure default)")
        elif len(val) < _MIN_SECRET_LENGTH and key not in ("DATABASE_URL",):
            issues.append(f"  WEAK     {key}  (length {len(val)} < minimum {_MIN_SECRET_LENGTH})")

    stripe_enabled = env_vars.get("STRIPE_BILLING_ENABLED", "false").lower() in ("true", "1", "yes")
    if stripe_enabled:
        for key in stripe_required:
            val = env_vars.get(key, "")
            if not val:
                issues.append(f"  MISSING  {key}  (required when STRIPE_BILLING_ENABLED=true)")

    if issues:
        print("Secret validation FAILED. Issues found:")
        for issue in issues:
            print(issue)
        print()
        print("Run: python scripts/generate_secrets.py")
        print("Then merge the output into your secret management system.")
        return False

    print(f"Secret validation PASSED for {env_path} ({len(required_in_production)} keys checked).")
    return True


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate or validate Aether production secrets.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--validate",
        metavar="ENV_FILE",
        help="Validate an existing .env file for weak or missing secrets.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print secret names without revealing generated values.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> None:
    args = _parse_args(argv)

    if args.validate:
        ok = _validate(args.validate)
        sys.exit(0 if ok else 1)

    _print_generated(dry_run=args.dry_run)


if __name__ == "__main__":
    main()
