#!/usr/bin/env python3
"""Generate lightweight repository documentation artifacts from the current tree.

This script gives the repo a deterministic, machine-generated documentation
surface that can be checked in CI. It is intentionally conservative: it does
not attempt to rewrite authored architecture docs, but it does keep a living
index of important areas and the automation that protects them.

Uses `git ls-files` to count only tracked files, ensuring deterministic output
regardless of build artifacts, caches, or virtual environments.
"""

from __future__ import annotations

import subprocess
from collections import defaultdict
from pathlib import Path, PurePosixPath

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
INDEX_PATH = DOCS / "REPO-INDEX.md"
AUTOMATION_PATH = DOCS / "AUTOMATION.md"

TOP_LEVEL_DOC_FOCUS = {
    "security",
    "scripts",
    "docs",
    "tests",
    "cicd",
    "ML Models",
    "Agent Layer",
    "Aether Mobile SDK",
    "Data Ingestion Layer",
    "Smart Contracts",
    "AWS Deployment",
    "GDPR & SOC2",
}


def _git_tracked_files() -> list[str]:
    """Return all git-tracked file paths relative to ROOT."""
    result = subprocess.run(
        ["git", "ls-files"],
        capture_output=True,
        text=True,
        cwd=ROOT,
    )
    return [line for line in result.stdout.splitlines() if line]


def collect_counts(area: str, tracked: list[str]) -> tuple[int, int]:
    """Count directories and files under a top-level area using git-tracked files."""
    prefix = area + "/"
    files = 0
    dirs: set[str] = set()
    for fpath in tracked:
        if not fpath.startswith(prefix):
            continue
        files += 1
        parent = str(PurePosixPath(fpath).parent)
        if parent != area:
            dirs.add(parent)
            # Add intermediate directories
            parts = PurePosixPath(fpath).parts
            for i in range(2, len(parts)):
                dirs.add(str(PurePosixPath(*parts[:i])))
    return len(dirs), files


def top_level_summary(tracked: list[str]) -> list[tuple[str, int, int]]:
    rows: list[tuple[str, int, int]] = []
    for area in sorted(TOP_LEVEL_DOC_FOCUS, key=str.lower):
        dirs, files = collect_counts(area, tracked)
        if files > 0:
            rows.append((area, dirs, files))
    return rows


def authored_docs() -> dict[str, list[str]]:
    groups: dict[str, list[str]] = defaultdict(list)
    for path in sorted(DOCS.glob("*.md")):
        if path.name in {INDEX_PATH.name, AUTOMATION_PATH.name, "CHANGELOG.md"}:
            continue
        stem = path.stem
        if stem.startswith("SDK-"):
            groups["SDKs"].append(path.name)
        elif stem in {"ARCHITECTURE", "BACKEND-API", "INTELLIGENCE-GRAPH", "AGENT-CONTROLLER"}:
            groups["Platform"].append(path.name)
        else:
            groups["Specialized"].append(path.name)
    return dict(sorted(groups.items()))


def write_index(tracked: list[str]) -> None:
    rows = top_level_summary(tracked)
    lines = [
        "# Repository Index",
        "",
        "_Generated by `python scripts/sync_docs.py`. Do not edit by hand._",
        "",
        "## Top-level subsystem inventory",
        "",
        "| Area | Directories | Files |",
        "| --- | ---: | ---: |",
    ]
    for name, dirs, files in rows:
        lines.append(f"| `{name}` | {dirs} | {files} |")

    lines.extend([
        "",
        "## Authored documentation coverage",
        "",
        "The following authored docs are expected to stay aligned with code changes:",
        "",
    ])
    for group, docs in authored_docs().items():
        lines.append(f"### {group}")
        for doc in docs:
            lines.append(f"- `{doc}`")
        lines.append("")

    lines.extend([
        "## Operational rule",
        "",
        "Any code change that modifies subsystem behavior must update at least one authored doc or explicitly document why no authored doc changed in the pull request.",
        "",
    ])
    INDEX_PATH.write_text("\n".join(lines))


def write_automation() -> None:
    lines = [
        "# Documentation Automation",
        "",
        "_Generated by `python scripts/sync_docs.py`. Update the generator if this policy changes._",
        "",
        "## Why docs were drifting",
        "",
        "- The only existing validation checked versions and changelog entries; it did not verify that repository-facing docs were regenerated.",
        "- CI workflows lived under `cicd/aether-cicd/.github/workflows/`, which GitHub Actions ignores because workflows must exist under the repository root `.github/workflows/`.",
        "- As a result, documentation checks were not enforced for normal pushes and pull requests.",
        "",
        "## Permanent prevention",
        "",
        "1. `scripts/sync_docs.py` regenerates deterministic documentation artifacts from the live repository tree.",
        "2. `.github/workflows/repo-health.yml` runs tests, syntax checks, `sync_docs.py`, and `validate_docs.py` on every push and pull request.",
        "3. The workflow fails if generated documentation changes were not committed, preventing silent drift.",
        "4. On pushes to `main`, the workflow auto-commits regenerated documentation so the branch stays self-healing.",
        "",
        "## Team workflow",
        "",
        "- Before commit: run `python scripts/sync_docs.py && python scripts/validate_docs.py`.",
        "- During review: confirm behavior-changing code also updated authored docs under `docs/` when applicable.",
        "- After merge: rely on `repo-health.yml` to catch or auto-commit generated documentation drift.",
        "",
    ]
    AUTOMATION_PATH.write_text("\n".join(lines))


if __name__ == "__main__":
    DOCS.mkdir(exist_ok=True)
    tracked = _git_tracked_files()
    write_index(tracked)
    write_automation()
    print(f"Updated {INDEX_PATH.relative_to(ROOT)}")
    print(f"Updated {AUTOMATION_PATH.relative_to(ROOT)}")
