#!/usr/bin/env python3
"""Generate lightweight repository documentation artifacts from the current tree.

This script gives the repo a deterministic, machine-generated documentation
surface that can be checked in CI. It is intentionally conservative: it does
not attempt to rewrite authored architecture docs, but it does keep a living
index of important areas and the automation that protects them.
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
INDEX_PATH = DOCS / "REPO-INDEX.md"
AUTOMATION_PATH = DOCS / "AUTOMATION.md"
WORKFLOW_PATH = ROOT / ".github" / "workflows" / "repo-health.yml"

IGNORED_PARTS = {".git", "node_modules", "__pycache__", ".pytest_cache", ".venv", ".gradle"}
TOP_LEVEL_DOC_FOCUS = {
    "security",
    "scripts",
    "docs",
    "tests",
    "cicd",
    "ML Models",
    "Agent Layer",
    "Aether Mobile SDK",
    "Data Ingestion Layer",
    "Smart Contracts",
    "AWS Deployment",
    "GDPR & SOC2",
}


def should_ignore(path: Path) -> bool:
    return any(part in IGNORED_PARTS for part in path.parts)


def collect_counts(base: Path) -> tuple[int, int]:
    files = 0
    dirs: set[Path] = set()
    for path in base.rglob("*"):
        if should_ignore(path):
            continue
        if path.is_dir():
            dirs.add(path)
        elif path.is_file():
            files += 1
            if path.parent != base:
                dirs.add(path.parent)
    return len(dirs), files


def top_level_summary() -> list[tuple[str, int, int]]:
    rows: list[tuple[str, int, int]] = []
    for path in sorted(ROOT.iterdir(), key=lambda p: p.name.lower()):
        if should_ignore(path) or path.name.startswith("."):
            continue
        if path.is_dir() and path.name in TOP_LEVEL_DOC_FOCUS:
            dirs, files = collect_counts(path)
            rows.append((path.name, dirs, files))
    return rows


def authored_docs() -> dict[str, list[str]]:
    groups: dict[str, list[str]] = defaultdict(list)
    for path in sorted(DOCS.glob("*.md")):
        if path.name in {INDEX_PATH.name, AUTOMATION_PATH.name, "CHANGELOG.md"}:
            continue
        stem = path.stem
        if stem.startswith("SDK-"):
            groups["SDKs"].append(path.name)
        elif stem in {"ARCHITECTURE", "BACKEND-API", "INTELLIGENCE-GRAPH", "AGENT-CONTROLLER"}:
            groups["Platform"].append(path.name)
        else:
            groups["Specialized"].append(path.name)
    return dict(sorted(groups.items()))


def write_index() -> None:
    rows = top_level_summary()
    lines = [
        "# Repository Index",
        "",
        "_Generated by `python scripts/sync_docs.py`. Do not edit by hand._",
        "",
        "## Top-level subsystem inventory",
        "",
        "| Area | Directories | Files |",
        "| --- | ---: | ---: |",
    ]
    for name, dirs, files in rows:
        lines.append(f"| `{name}` | {dirs} | {files} |")

    lines.extend([
        "",
        "## Authored documentation coverage",
        "",
        "The following authored docs are expected to stay aligned with code changes:",
        "",
    ])
    for group, docs in authored_docs().items():
        lines.append(f"### {group}")
        for doc in docs:
            lines.append(f"- `{doc}`")
        lines.append("")

    lines.extend([
        "## Operational rule",
        "",
        "Any code change that modifies subsystem behavior must update at least one authored doc or explicitly document why no authored doc changed in the pull request.",
        "",
    ])
    INDEX_PATH.write_text("\n".join(lines))


def write_automation() -> None:
    lines = [
        "# Documentation Automation",
        "",
        "_Generated by `python scripts/sync_docs.py`. Update the generator if this policy changes._",
        "",
        "## Why docs were drifting",
        "",
        "- The only existing validation checked versions and changelog entries; it did not verify that repository-facing docs were regenerated.",
        "- CI workflows lived under `cicd/aether-cicd/.github/workflows/`, which GitHub Actions ignores because workflows must exist under the repository root `.github/workflows/`.",
        "- As a result, documentation checks were not enforced for normal pushes and pull requests.",
        "",
        "## Permanent prevention",
        "",
        "1. `scripts/sync_docs.py` regenerates deterministic documentation artifacts from the live repository tree.",
        "2. `.github/workflows/repo-health.yml` runs the root test suite, the ML test suite, syntax checks, `sync_docs.py`, and `validate_docs.py` on every push and pull request.",
        "3. The workflow fails if generated documentation changes were not committed, preventing silent drift.",
        "4. On pushes to `main`, the workflow auto-commits regenerated documentation so the branch stays self-healing.",
        "5. GitHub branch protection must require the `Repo Health / validate` status check on `main`; otherwise failing checks can still be bypassed by direct pushes or unreviewed merges.",
        "6. `.github/workflows/repo-health.yml` and `docs/AUTOMATION.md` are both generated from this script, so when they conflict during a merge you should resolve `scripts/sync_docs.py` first and regenerate the derived files instead of hand-merging them.",
        "",
        "## Branch protection setup",
        "",
        "To remove GitHub's `Your main branch isn't protected` warning and make the automation enforceable:",
        "",
        "1. Open **Settings → Branches → Add branch protection rule** (or **Rules → Rulesets** on newer GitHub UI).",
        "2. Target the `main` branch.",
        "3. Enable **Require a pull request before merging**.",
        "4. Enable **Require status checks to pass before merging** and select `Repo Health / validate`.",
        "5. Enable **Require branches to be up to date before merging** so the required check runs on the exact commit being merged.",
        "6. Enable **Block force pushes** and **Block deletions** for `main`.",
        "7. Optional but recommended: enable **Require conversation resolution before merging** and restrict who can bypass the rule.",
        "",
        "## Merge-conflict recovery",
        "",
        "If a pull request reports conflicts in `.github/workflows/repo-health.yml` and `docs/AUTOMATION.md`:",
        "",
        "1. Update your branch with the latest base branch changes.",
        "2. Resolve conflicts in `scripts/sync_docs.py` first, because it is the source of truth for both generated files.",
        "3. Run `python scripts/sync_docs.py` to regenerate `.github/workflows/repo-health.yml` and `docs/AUTOMATION.md`.",
        "4. Run `python scripts/validate_docs.py`, `pytest`, and `pytest 'ML Models/aether-ml/tests' -q` before committing the merge resolution.",
        "",
        "## Team workflow",
        "",
        "- Before commit: run `python scripts/sync_docs.py && python scripts/validate_docs.py`, plus the relevant root/ML pytest suites for touched code.",
        "- During review: confirm behavior-changing code also updated authored docs under `docs/` when applicable.",
        "- After merge: rely on `repo-health.yml` to catch or auto-commit generated documentation drift.",
        "",
    ]
    AUTOMATION_PATH.write_text("\n".join(lines))


def write_repo_health_workflow() -> None:
    workflow = "\n".join([
        "# Generated by `python scripts/sync_docs.py`. Update the generator if this policy changes.",
        "name: Repo Health",
        "",
        "on:",
        "  pull_request:",
        "  push:",
        "    branches:",
        "      - '**'",
        "",
        "permissions:",
        "  contents: write",
        "",
        "concurrency:",
        "  group: repo-health-${{ github.ref }}",
        "  cancel-in-progress: true",
        "",
        "jobs:",
        "  validate:",
        "    runs-on: ubuntu-latest",
        "    steps:",
        "      - name: Checkout repository",
        "        uses: actions/checkout@v4",
        "        with:",
        "          fetch-depth: 0",
        "",
        "      - name: Set up Python",
        "        uses: actions/setup-python@v5",
        "        with:",
        "          python-version: '3.10'",
        "",
        "      - name: Install test dependencies",
        "        run: |",
        "          python -m pip install --upgrade pip",
        "          pip install \\",
        "            pytest \\",
        "            numpy \\",
        "            pandas \\",
        "            scikit-learn \\",
        "            xgboost \\",
        "            pyarrow \\",
        "            fastapi \\",
        "            httpx \\",
        "            pydantic \\",
        "            requests \\",
        "            joblib",
        "",
        "      - name: Regenerate generated docs",
        "        run: python scripts/sync_docs.py",
        "",
        "      - name: Validate documentation",
        "        run: python scripts/validate_docs.py",
        "",
        "      - name: Run root Python tests",
        "        run: pytest",
        "",
        "      - name: Run ML Python tests",
        "        run: pytest 'ML Models/aether-ml/tests' -q",
        "",
        "      - name: Verify Python syntax",
        "        run: python -m compileall security 'Agent Layer' 'ML Models/aether-ml' 'cicd/aether-cicd'",
        "",
        "      - name: Detect uncommitted generated-doc drift",
        "        id: drift",
        "        run: |",
        "          if [ -n \"$(git status --porcelain .github/workflows/repo-health.yml docs/REPO-INDEX.md docs/AUTOMATION.md)\" ]; then",
        "            echo \"drift=true\" >> \"$GITHUB_OUTPUT\"",
        "            git diff -- .github/workflows/repo-health.yml docs/REPO-INDEX.md docs/AUTOMATION.md",
        "          else",
        "            echo \"drift=false\" >> \"$GITHUB_OUTPUT\"",
        "          fi",
        "",
        "      - name: Auto-commit generated docs on main",
        "        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.drift.outputs.drift == 'true'",
        "        run: |",
        "          git config user.name 'github-actions[bot]'",
        "          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'",
        "          git add .github/workflows/repo-health.yml docs/REPO-INDEX.md docs/AUTOMATION.md",
        "          git commit -m 'docs: synchronize generated repository documentation'",
        "          git push",
        "",
        "      - name: Fail PRs and non-main pushes on drift",
        "        if: ${{ steps.drift.outputs.drift == 'true' && (github.event_name != 'push' || github.ref != 'refs/heads/main') }}",
        "        run: |",
        "          echo 'Generated repository automation files are out of date. Run: python scripts/sync_docs.py'",
        "          exit 1",
        "",
    ])
    WORKFLOW_PATH.write_text(workflow)


if __name__ == "__main__":
    DOCS.mkdir(exist_ok=True)
    write_index()
    write_automation()
    WORKFLOW_PATH.parent.mkdir(parents=True, exist_ok=True)
    write_repo_health_workflow()
    print(f"Updated {INDEX_PATH.relative_to(ROOT)}")
    print(f"Updated {AUTOMATION_PATH.relative_to(ROOT)}")
    print(f"Updated {WORKFLOW_PATH.relative_to(ROOT)}")
