"""
Aether Backend — Automated Analytics Pipeline

Real-time analytics automation that:
1. Aggregates events into campaign performance metrics
2. Detects reward-eligible events and triggers the reward pipeline
3. Generates automated insights (anomaly detection, trend analysis)
4. Produces cross-platform analytics (Web2 + Web3 unified view)

This is the "brain" that connects analytics to automated rewards.
"""

from __future__ import annotations

import logging
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from typing import Any, Optional
from uuid import uuid4

logger = logging.getLogger("aether.analytics_automation")


# =============================================================================
# DATA MODELS
# =============================================================================


@dataclass
class MetricWindow:
    """A time-bounded aggregation window for campaign metrics."""

    window_start: datetime
    window_end: datetime
    event_count: int = 0
    unique_users: set[str] = field(default_factory=set)
    conversion_count: int = 0
    reward_count: int = 0
    total_reward_value_wei: int = 0
    fraud_blocked_count: int = 0

    def to_dict(self) -> dict[str, Any]:
        return {
            "window_start": self.window_start.isoformat(),
            "window_end": self.window_end.isoformat(),
            "event_count": self.event_count,
            "unique_users": len(self.unique_users),
            "conversion_count": self.conversion_count,
            "reward_count": self.reward_count,
            "total_reward_value_wei": str(self.total_reward_value_wei),
            "fraud_blocked_count": self.fraud_blocked_count,
        }


@dataclass
class CampaignMetrics:
    """Aggregated metrics for a single campaign across multiple time windows."""

    campaign_id: str
    windows: list[MetricWindow] = field(default_factory=list)
    total_events: int = 0
    total_rewards: int = 0
    total_fraud_blocked: int = 0
    top_channels: dict[str, int] = field(default_factory=dict)
    conversion_rate: float = 0.0

    def to_dict(self) -> dict[str, Any]:
        return {
            "campaign_id": self.campaign_id,
            "windows": [w.to_dict() for w in self.windows],
            "total_events": self.total_events,
            "total_rewards": self.total_rewards,
            "total_fraud_blocked": self.total_fraud_blocked,
            "top_channels": dict(
                sorted(self.top_channels.items(), key=lambda x: x[1], reverse=True)[:10]
            ),
            "conversion_rate": round(self.conversion_rate, 4),
        }


@dataclass
class AutomatedInsight:
    """An automated insight generated by the analytics pipeline."""

    type: str          # anomaly | trend | milestone | alert
    severity: str      # info | warning | critical
    message: str
    data: dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def to_dict(self) -> dict[str, Any]:
        return {
            "type": self.type,
            "severity": self.severity,
            "message": self.message,
            "data": self.data,
            "timestamp": self.timestamp.isoformat(),
        }


# =============================================================================
# EVENT CLASSIFIER (STATIC UTILITY)
# =============================================================================


class EventClassifier:
    """Stateless utility for classifying incoming events."""

    # Web3-specific event types
    _WEB3_ACTIONS: set[str] = {
        "wallet_connect", "wallet_disconnect", "transaction", "swap",
        "bridge", "stake", "unstake", "claim", "mint", "burn", "approve",
        "liquidity_add", "liquidity_remove", "nft_purchase", "nft_sale",
        "governance_vote", "delegation", "borrow", "repay", "flash_loan",
    }

    # Conversion signals
    _CONVERSION_ACTIONS: set[str] = {
        "purchase", "swap", "subscription", "deposit", "nft_purchase",
        "checkout_complete", "signup_complete", "upgrade",
    }

    # Engagement signals
    _ENGAGEMENT_ACTIONS: set[str] = {
        "page_view", "scroll", "click", "search", "share", "comment",
        "like", "bookmark", "video_play", "form_start",
    }

    # Retention signals
    _RETENTION_ACTIONS: set[str] = {
        "login", "session_resume", "notification_open", "feature_use",
        "settings_update", "profile_update",
    }

    @staticmethod
    def classify_platform(event: dict[str, Any]) -> str:
        """Classify whether an event is Web2 or Web3."""
        action = event.get("action_type", event.get("type", "")).lower()

        if action in EventClassifier._WEB3_ACTIONS:
            return "web3"

        # Check for blockchain-specific properties
        props = event.get("properties", {})
        if any(
            key in props
            for key in ("tx_hash", "chain_id", "wallet_address", "contract_address", "token_id")
        ):
            return "web3"

        return "web2"

    @staticmethod
    def classify_intent(event: dict[str, Any]) -> str:
        """Classify the user intent category of an event."""
        action = event.get("action_type", event.get("type", "")).lower()

        if action in EventClassifier._CONVERSION_ACTIONS:
            return "conversion"
        if action in EventClassifier._ENGAGEMENT_ACTIONS:
            return "engagement"
        if action in EventClassifier._RETENTION_ACTIONS:
            return "retention"

        # Default to acquisition for first-touch or unknown events
        props = event.get("properties", {})
        if props.get("is_new_user") or action in ("first_visit", "referral", "install"):
            return "acquisition"

        return "engagement"

    @staticmethod
    def is_reward_eligible(event: dict[str, Any]) -> bool:
        """Quick pre-check whether an event could qualify for a reward.

        This is a lightweight filter before the full eligibility engine runs.
        It filters out obviously ineligible events (e.g. page views, scrolls).
        """
        action = event.get("action_type", event.get("type", "")).lower()

        # Page views and passive engagement never trigger rewards directly
        non_eligible = {"page_view", "scroll", "hover", "impression", "heartbeat"}
        if action in non_eligible:
            return False

        # Must have a user identifier
        user = event.get("user") or event.get("user_id") or event.get("wallet_address")
        if not user:
            return False

        # Web3 actions and conversions are always candidates
        if action in EventClassifier._WEB3_ACTIONS | EventClassifier._CONVERSION_ACTIONS:
            return True

        # Custom events with explicit reward flag
        props = event.get("properties", {})
        if props.get("reward_eligible"):
            return True

        return False


# =============================================================================
# ANALYTICS PIPELINE
# =============================================================================


class AnalyticsPipeline:
    """Core pipeline that ingests events, updates metrics, and triggers rewards."""

    def __init__(self, window_size_seconds: int = 3600) -> None:
        self._window_size = timedelta(seconds=window_size_seconds)

        # campaign_id -> list[MetricWindow]
        self._campaign_windows: dict[str, list[MetricWindow]] = defaultdict(list)
        # campaign_id -> channel -> count
        self._campaign_channels: dict[str, dict[str, int]] = defaultdict(lambda: defaultdict(int))
        # campaign_id -> running totals
        self._campaign_totals: dict[str, dict[str, int]] = {}

        # Global counters for anomaly detection baselines
        self._global_event_counts: list[tuple[datetime, int]] = []
        self._global_fraud_counts: list[tuple[datetime, int]] = []
        self._global_conversion_counts: list[tuple[datetime, int]] = []

        # Reward budget tracking: campaign_id -> (spent_wei, budget_wei)
        self._reward_budgets: dict[str, tuple[int, int]] = {}

        # Insights buffer
        self._insights: list[AutomatedInsight] = []

        logger.info(
            "AnalyticsPipeline initialised (window_size=%ds)", window_size_seconds
        )

    # =========================================================================
    # EVENT INGESTION
    # =========================================================================

    async def ingest_event(self, event: dict[str, Any]) -> dict[str, Any]:
        """Process a single event through the automation pipeline.

        Steps:
            1. Classify the event (platform, intent)
            2. Record in campaign metrics
            3. Check reward eligibility and trigger pipeline if qualified
            4. Generate insights if thresholds are crossed

        Returns:
            A result dict describing the actions taken.
        """
        event_id = event.get("id", str(uuid4()))
        campaign_id = event.get("campaign_id", "default")
        action_type = event.get("action_type", event.get("type", "unknown"))
        user = event.get("user") or event.get("user_id") or event.get("wallet_address", "")
        timestamp = self._parse_timestamp(event.get("timestamp"))

        # Classify
        platform = EventClassifier.classify_platform(event)
        intent = EventClassifier.classify_intent(event)

        # Get or create the current metric window
        window = self._get_current_window(campaign_id, timestamp)
        window.event_count += 1
        if user:
            window.unique_users.add(str(user))

        # Track channel
        channel = event.get("properties", {}).get("channel", platform)
        self._campaign_channels[campaign_id][channel] += 1

        # Ensure campaign totals exist
        if campaign_id not in self._campaign_totals:
            self._campaign_totals[campaign_id] = {
                "events": 0, "conversions": 0, "rewards": 0, "fraud_blocked": 0,
            }
        self._campaign_totals[campaign_id]["events"] += 1

        # Track conversions
        is_conversion = intent == "conversion"
        if is_conversion:
            window.conversion_count += 1
            self._campaign_totals[campaign_id]["conversions"] += 1

        # Update global counters for anomaly baseline
        self._global_event_counts.append((timestamp, 1))
        if is_conversion:
            self._global_conversion_counts.append((timestamp, 1))

        # Build result
        result: dict[str, Any] = {
            "event_id": event_id,
            "campaign_id": campaign_id,
            "platform": platform,
            "intent": intent,
            "reward_triggered": False,
            "fraud_blocked": False,
            "insights_generated": 0,
        }

        # Reward eligibility quick-check
        if EventClassifier.is_reward_eligible(event):
            reward_result = await self._evaluate_reward(event, campaign_id, window)
            result["reward_triggered"] = reward_result.get("triggered", False)
            result["fraud_blocked"] = reward_result.get("fraud_blocked", False)
            result["reward_id"] = reward_result.get("reward_id")

        # Generate insights on threshold crossings
        new_insights = await self._check_insight_triggers(campaign_id, window)
        result["insights_generated"] = len(new_insights)

        logger.debug(
            "Event ingested: id=%s campaign=%s platform=%s intent=%s reward=%s",
            event_id, campaign_id, platform, intent, result["reward_triggered"],
        )

        return result

    # =========================================================================
    # METRICS RETRIEVAL
    # =========================================================================

    async def get_campaign_metrics(
        self, campaign_id: str, hours: int = 24
    ) -> CampaignMetrics:
        """Return aggregated metrics for a campaign over the specified time range."""
        cutoff = datetime.now(timezone.utc) - timedelta(hours=hours)
        windows = [
            w
            for w in self._campaign_windows.get(campaign_id, [])
            if w.window_end >= cutoff
        ]

        totals = self._campaign_totals.get(campaign_id, {})
        total_events = totals.get("events", 0)
        total_conversions = totals.get("conversions", 0)

        return CampaignMetrics(
            campaign_id=campaign_id,
            windows=windows,
            total_events=total_events,
            total_rewards=totals.get("rewards", 0),
            total_fraud_blocked=totals.get("fraud_blocked", 0),
            top_channels=dict(self._campaign_channels.get(campaign_id, {})),
            conversion_rate=(
                total_conversions / max(total_events, 1)
            ),
        )

    async def get_platform_overview(self, hours: int = 24) -> dict[str, Any]:
        """Generate a cross-platform summary of all campaign activity."""
        cutoff = datetime.now(timezone.utc) - timedelta(hours=hours)

        total_events = 0
        web2_events = 0
        web3_events = 0
        total_rewards = 0
        total_fraud_blocked = 0
        total_conversions = 0
        campaign_count = 0

        for cid, windows in self._campaign_windows.items():
            active_windows = [w for w in windows if w.window_end >= cutoff]
            if not active_windows:
                continue
            campaign_count += 1
            for w in active_windows:
                total_events += w.event_count
                total_conversions += w.conversion_count
                total_rewards += w.reward_count
                total_fraud_blocked += w.fraud_blocked_count

        # Estimate web2/web3 split from channel data
        for channels in self._campaign_channels.values():
            for channel, count in channels.items():
                if channel == "web3":
                    web3_events += count
                else:
                    web2_events += count

        return {
            "period_hours": hours,
            "total_events": total_events,
            "web2_events": web2_events,
            "web3_events": web3_events,
            "total_conversions": total_conversions,
            "conversion_rate": round(
                total_conversions / max(total_events, 1), 4
            ),
            "total_rewards_issued": total_rewards,
            "total_fraud_blocked": total_fraud_blocked,
            "active_campaigns": campaign_count,
        }

    # =========================================================================
    # ANOMALY DETECTION
    # =========================================================================

    async def detect_anomalies(self) -> list[AutomatedInsight]:
        """Scan for anomalous patterns across all campaigns.

        Detected anomalies:
          - Event volume spike (>3x rolling average)
          - Fraud rate spike (>2x rolling average)
          - Conversion rate drop (>50% decline from baseline)
          - Reward budget depletion warning (>80% spent)
        """
        insights: list[AutomatedInsight] = []
        now_utc = datetime.now(timezone.utc)
        one_hour_ago = now_utc - timedelta(hours=1)
        six_hours_ago = now_utc - timedelta(hours=6)

        # --- Event volume spike ---
        recent_events = sum(
            c for ts, c in self._global_event_counts if ts >= one_hour_ago
        )
        baseline_events = sum(
            c for ts, c in self._global_event_counts if six_hours_ago <= ts < one_hour_ago
        )
        avg_hourly_baseline = baseline_events / max(5, 1)  # 5-hour baseline

        if avg_hourly_baseline > 0 and recent_events > avg_hourly_baseline * 3:
            insight = AutomatedInsight(
                type="anomaly",
                severity="warning",
                message=f"Event volume spike detected: {recent_events} events in the last hour "
                        f"(baseline: ~{int(avg_hourly_baseline)}/hr)",
                data={
                    "recent_count": recent_events,
                    "baseline_hourly": int(avg_hourly_baseline),
                    "multiplier": round(recent_events / avg_hourly_baseline, 1),
                },
            )
            insights.append(insight)

        # --- Fraud rate spike ---
        recent_fraud = sum(
            c for ts, c in self._global_fraud_counts if ts >= one_hour_ago
        )
        baseline_fraud = sum(
            c for ts, c in self._global_fraud_counts if six_hours_ago <= ts < one_hour_ago
        )
        avg_fraud_baseline = baseline_fraud / max(5, 1)

        if avg_fraud_baseline > 0 and recent_fraud > avg_fraud_baseline * 2:
            insight = AutomatedInsight(
                type="anomaly",
                severity="critical",
                message=f"Fraud rate spike: {recent_fraud} blocked in the last hour "
                        f"(baseline: ~{int(avg_fraud_baseline)}/hr)",
                data={
                    "recent_fraud": recent_fraud,
                    "baseline_hourly": int(avg_fraud_baseline),
                },
            )
            insights.append(insight)

        # --- Conversion rate drop ---
        recent_conversions = sum(
            c for ts, c in self._global_conversion_counts if ts >= one_hour_ago
        )
        baseline_conversions = sum(
            c for ts, c in self._global_conversion_counts if six_hours_ago <= ts < one_hour_ago
        )
        avg_conv_baseline = baseline_conversions / max(5, 1)

        if avg_conv_baseline > 2 and recent_conversions < avg_conv_baseline * 0.5:
            insight = AutomatedInsight(
                type="anomaly",
                severity="warning",
                message=f"Conversion rate drop: {recent_conversions} conversions in the last hour "
                        f"(baseline: ~{int(avg_conv_baseline)}/hr, -"
                        f"{int((1 - recent_conversions / avg_conv_baseline) * 100)}%)",
                data={
                    "recent_conversions": recent_conversions,
                    "baseline_hourly": int(avg_conv_baseline),
                },
            )
            insights.append(insight)

        # --- Reward budget depletion ---
        for cid, (spent, budget) in self._reward_budgets.items():
            if budget > 0 and spent > budget * 0.8:
                pct = round(spent / budget * 100, 1)
                insight = AutomatedInsight(
                    type="alert",
                    severity="critical" if pct >= 95 else "warning",
                    message=f"Reward budget for campaign '{cid}' is {pct}% depleted "
                            f"({spent}/{budget} wei spent)",
                    data={
                        "campaign_id": cid,
                        "spent_wei": str(spent),
                        "budget_wei": str(budget),
                        "percent_used": pct,
                    },
                )
                insights.append(insight)

        self._insights.extend(insights)
        return insights

    # =========================================================================
    # REPORT GENERATION
    # =========================================================================

    async def generate_report(self, campaign_id: str) -> dict[str, Any]:
        """Generate a comprehensive performance report for a campaign."""
        metrics = await self.get_campaign_metrics(campaign_id, hours=168)  # 7 days

        totals = self._campaign_totals.get(campaign_id, {})
        total_events = totals.get("events", 0)
        total_conversions = totals.get("conversions", 0)
        total_rewards = totals.get("rewards", 0)
        total_fraud = totals.get("fraud_blocked", 0)

        # ROI calculation (simplified: conversions / rewards issued)
        roi = (
            total_conversions / max(total_rewards, 1)
            if total_rewards > 0
            else 0.0
        )

        # Channel breakdown
        channels = self._campaign_channels.get(campaign_id, {})
        channel_breakdown = []
        for channel, count in sorted(channels.items(), key=lambda x: x[1], reverse=True):
            channel_breakdown.append({
                "channel": channel,
                "event_count": count,
                "share_pct": round(count / max(total_events, 1) * 100, 1),
            })

        # Fraud analysis
        fraud_rate = round(
            total_fraud / max(total_events, 1) * 100, 2
        )

        # Recent insights for this campaign
        campaign_insights = [
            i.to_dict()
            for i in self._insights
            if i.data.get("campaign_id") == campaign_id
        ][-20:]  # Last 20

        return {
            "campaign_id": campaign_id,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "period": "7d",
            "summary": {
                "total_events": total_events,
                "total_conversions": total_conversions,
                "conversion_rate": round(total_conversions / max(total_events, 1) * 100, 2),
                "total_rewards_issued": total_rewards,
                "roi_conversions_per_reward": round(roi, 3),
                "total_fraud_blocked": total_fraud,
                "fraud_rate_pct": fraud_rate,
            },
            "channel_breakdown": channel_breakdown,
            "fraud_analysis": {
                "total_blocked": total_fraud,
                "fraud_rate_pct": fraud_rate,
                "risk_level": (
                    "high" if fraud_rate > 10
                    else "medium" if fraud_rate > 5
                    else "low"
                ),
            },
            "recent_insights": campaign_insights,
            "metrics": metrics.to_dict(),
        }

    # =========================================================================
    # INTERNAL
    # =========================================================================

    def _get_current_window(
        self, campaign_id: str, timestamp: datetime
    ) -> MetricWindow:
        """Get or create the metric window that covers the given timestamp."""
        windows = self._campaign_windows[campaign_id]

        # Check if the latest window covers this timestamp
        if windows:
            latest = windows[-1]
            if latest.window_start <= timestamp < latest.window_end:
                return latest

        # Create a new window aligned to the window size
        window_start = timestamp.replace(minute=0, second=0, microsecond=0)
        window = MetricWindow(
            window_start=window_start,
            window_end=window_start + self._window_size,
        )
        windows.append(window)

        # Prune old windows (keep last 168 = 7 days of hourly windows)
        if len(windows) > 168:
            self._campaign_windows[campaign_id] = windows[-168:]

        return window

    async def _evaluate_reward(
        self,
        event: dict[str, Any],
        campaign_id: str,
        window: MetricWindow,
    ) -> dict[str, Any]:
        """Evaluate whether an event should trigger a reward.

        In production this would call the fraud detection service, attribution
        engine, and eligibility engine. Here we simulate the pipeline stages.
        """
        result: dict[str, Any] = {
            "triggered": False,
            "fraud_blocked": False,
            "reward_id": None,
        }

        # Stage 1: Fraud pre-check (simplified)
        props = event.get("properties", {})
        fraud_score = props.get("fraud_score", 0.0)
        if fraud_score > 0.8:
            window.fraud_blocked_count += 1
            self._campaign_totals[campaign_id]["fraud_blocked"] += 1
            self._global_fraud_counts.append((datetime.now(timezone.utc), 1))
            result["fraud_blocked"] = True
            logger.warning(
                "Reward blocked by fraud check: campaign=%s score=%.2f",
                campaign_id, fraud_score,
            )
            return result

        # Stage 2: Attribution check — user must be attributed to the campaign
        user = event.get("user") or event.get("user_id") or event.get("wallet_address")
        if not user:
            return result

        # Stage 3: Eligibility (simplified — production calls EligibilityEngine)
        action_type = event.get("action_type", event.get("type", ""))
        reward_amount_wei = props.get("reward_amount_wei", 0)

        if reward_amount_wei <= 0:
            # No explicit reward amount — use campaign defaults
            reward_amount_wei = props.get("default_reward_wei", 0)

        if reward_amount_wei > 0:
            reward_id = f"rwd_{uuid4().hex[:16]}"
            window.reward_count += 1
            window.total_reward_value_wei += int(reward_amount_wei)
            self._campaign_totals[campaign_id]["rewards"] += 1

            # Track budget usage
            if campaign_id in self._reward_budgets:
                spent, budget = self._reward_budgets[campaign_id]
                self._reward_budgets[campaign_id] = (
                    spent + int(reward_amount_wei),
                    budget,
                )

            result["triggered"] = True
            result["reward_id"] = reward_id

            logger.info(
                "Reward triggered: id=%s campaign=%s user=%s amount=%s wei",
                reward_id, campaign_id, user, reward_amount_wei,
            )

        return result

    async def _check_insight_triggers(
        self, campaign_id: str, window: MetricWindow
    ) -> list[AutomatedInsight]:
        """Check if any insight thresholds have been crossed."""
        insights: list[AutomatedInsight] = []

        # Milestone: campaign reaches 1000, 10000, 100000 events
        totals = self._campaign_totals.get(campaign_id, {})
        total_events = totals.get("events", 0)
        for milestone in (1_000, 10_000, 100_000, 1_000_000):
            if total_events == milestone:
                insight = AutomatedInsight(
                    type="milestone",
                    severity="info",
                    message=f"Campaign '{campaign_id}' reached {milestone:,} total events",
                    data={"campaign_id": campaign_id, "milestone": milestone},
                )
                insights.append(insight)

        # Trend: window has unusually high unique users
        if len(window.unique_users) > 100:
            insight = AutomatedInsight(
                type="trend",
                severity="info",
                message=f"High user activity in campaign '{campaign_id}': "
                        f"{len(window.unique_users)} unique users this window",
                data={
                    "campaign_id": campaign_id,
                    "unique_users": len(window.unique_users),
                },
            )
            insights.append(insight)

        self._insights.extend(insights)
        return insights

    @staticmethod
    def _parse_timestamp(value: Any) -> datetime:
        """Parse a timestamp from various formats into a timezone-aware datetime."""
        if isinstance(value, datetime):
            if value.tzinfo is None:
                return value.replace(tzinfo=timezone.utc)
            return value

        if isinstance(value, str) and value:
            try:
                dt = datetime.fromisoformat(value.replace("Z", "+00:00"))
                if dt.tzinfo is None:
                    dt = dt.replace(tzinfo=timezone.utc)
                return dt
            except (ValueError, TypeError):
                pass

        if isinstance(value, (int, float)):
            return datetime.fromtimestamp(value, tz=timezone.utc)

        return datetime.now(timezone.utc)
