import { ProofResult } from "@aether/proof-runner";

/**
 * MarkdownReportGenerator — generates a Markdown report from a ProofResult.
 */
export class MarkdownReportGenerator {
  generate(result: ProofResult): string {
    const lines: string[] = [];

    lines.push(`# Proof Report: ${result.proofId}`);
    lines.push("");
    lines.push(`**Status:** \`${result.status}\``);
    lines.push("");
    lines.push(`**Started:** ${result.startedAt}`);
    lines.push(`**Completed:** ${result.completedAt}`);
    if (result.totalDurationMs) {
      lines.push(`**Duration:** ${result.totalDurationMs}ms`);
    }
    lines.push("");

    if (result.summary) {
      lines.push(`## Summary`);
      lines.push("");
      lines.push(result.summary);
      lines.push("");
    }

    lines.push("## Steps");
    lines.push("");
    lines.push("| Result | Step | Status | Duration | Reason |");
    lines.push("|--------|------|--------|----------|--------|");

    for (const step of result.steps) {
      const statusIcon =
        step.status === "passed"
          ? "✅"
          : step.status === "failed"
          ? "❌"
          : step.status === "skipped"
          ? "⏭️"
          : "⚠️";
      const escapeCell = (value: string): string =>
        value.replace(/\|/g, "\\|").replace(/\r?\n/g, " ");

      lines.push(
        `| ${statusIcon} | \`${escapeCell(step.stepId)}\` | ${step.status} | ${step.durationMs ?? "—"}ms | ${escapeCell(step.reason ?? "—")} |`
      );
    }

    lines.push("");
    lines.push("---");
    lines.push("");
    lines.push("_Generated by @aether/proof-reporting._");

    return lines.join("\n");
  }
}
