# DO NOT EDIT — generated from packages/shared/contracts/event-registry.json
# Run: python scripts/generate_contracts.py
# Contract version: 8.12.0

CANONICAL_EVENT_TYPES: frozenset[str] = frozenset({
    "track",
    "page",
    "screen",
    "heartbeat",
    "error",
    "performance",
    "experiment",
    "journey_started",
    "journey_paused",
    "journey_resumed",
    "journey_continued",
    "journey_completed",
    "journey_abandoned",
    "journey_checkpoint",
    "navigation_intent",
    "navigation_arrival",
    "deep_link_opened",
    "app_install_attributed",
    "deferred_attribution_resolved",
    "qr_code_scanned",
    "nfc_tag_read",
    "app_clip_invoked",
    "identify",
    "consent",
    "conversion",
    "payment_initiated",
    "payment_completed",
    "payment_failed",
    "approval_requested",
    "approval_resolved",
    "entitlement_granted",
    "entitlement_revoked",
    "access_granted",
    "access_denied",
    "wallet",
    "transaction",
    "contract_action",
    "agent_task",
    "agent_decision",
    "a2h_interaction",
    "agent_registered",
    "agent_updated",
    "agent_authorized",
    "agent_deauthorized",
    "agent_capability_granted",
    "agent_capability_revoked",
    "agent_task_created",
    "agent_task_decomposed",
    "agent_task_started",
    "agent_task_completed",
    "agent_task_failed",
    "agent_tool_called",
    "agent_resource_requested",
    "agent_delegated_task",
    "agent_subagent_spawned",
    "agent_policy_evaluated",
    "agent_handoff",
    "agent_escalated_to_human",
    "agent_outcome_recorded",
    "reward_action_queued",
    "reward_proof_generated",
    "reward_delivered",
    "reward_claim_submitted",
    "x402_payment",
    "x402_resource_requested",
    "x402_payment_required",
    "x402_quote_received",
    "x402_authorization_requested",
    "x402_authorization_resolved",
    "x402_payment_intent_created",
    "x402_payment_submitted",
    "x402_payment_settled",
    "x402_payment_failed",
    "x402_payment_timeout",
    "x402_receipt_verified",
    "x402_access_granted",
    "x402_access_denied",
    "x402_refund_or_reversal",
    "agentic_account_observed",
    "agentic_account_connected_observed",
    "agentic_account_disconnected_observed",
    "agent_budget_observed",
    "agent_budget_changed_observed",
    "agent_permission_observed",
    "agent_mcp_connection_observed",
    "agent_tool_observed",
    "agent_tool_invocation_observed",
    "agent_activity_observed",
    "agent_risk_signal_observed",
    "agent_notification_observed",
    "agent_strategy_observed",
    "agent_trade_intent_observed",
    "agent_trade_order_observed",
    "agent_trade_fill_observed",
    "agent_trade_rejection_observed",
    "agent_position_observed",
    "agent_portfolio_snapshot_observed",
    "agent_performance_snapshot_observed",
    "agent_disconnect_observed",
    "agent_inbox_observed",
    "agent_email_address_observed",
    "agent_thread_observed",
    "agent_message_received_observed",
    "agent_message_sent_observed",
    "agent_reply_observed",
    "agent_attachment_observed",
    "agent_attachment_parsed_observed",
    "agent_otp_detected_observed",
    "agent_invoice_detected_observed",
    "agent_receipt_detected_observed",
    "agent_calendar_intent_observed",
    "agent_support_route_observed",
    "agent_semantic_search_observed",
    "agent_data_extraction_observed",
    "x402_resource_request_observed",
    "x402_challenge_observed",
    "x402_payment_requirement_observed",
    "x402_signature_observed",
    "x402_verification_observed",
    "x402_settlement_observed",
    "x402_resource_access_observed",
    "x402_resource_access_denied_observed",
    "x402_failure_observed",
    "x402_replay_risk_observed",
    "x402_provider_observed",
    "content_impression",
    "recommendation_exposed",
    "offer_exposed",
    "feature_exposed",
    "search_result_exposed",
    "ad_exposed",
    "notification_presented",
    "decision_observed",
    "outcome_observed",
    "goal_achieved",
    "goal_failed",
    "recommendation_accepted",
    "recommendation_rejected",
    "feedback_submitted",
    "retention_observed",
    "churn_observed",
    "human_override_observed",
    "organization_observed",
    "workspace_created",
    "workspace_updated",
    "member_invited",
    "member_joined",
    "member_removed",
    "role_changed",
    "seat_assigned",
    "seat_released",
    "integration_connected",
    "integration_disconnected",
    "service_account_created",
    "service_account_revoked",
    "api_key_created",
    "api_key_revoked",
    "project_created",
    "project_archived",
    "workflow_started",
    "workflow_completed",
    "workflow_failed",
    "product_viewed",
    "cart_item_added",
    "cart_item_removed",
    "cart_updated",
    "coupon_applied",
    "checkout_started",
    "checkout_step_completed",
    "order_completed",
    "order_cancelled",
    "order_refunded",
    "chargeback_observed",
    "subscription_started",
    "trial_started",
    "trial_converted",
    "subscription_renewed",
    "subscription_upgrade_observed",
    "subscription_downgrade_observed",
    "subscription_cancelled",
    "invoice_issued",
    "invoice_paid",
    "invoice_failed",
    "dunning_started",
    "dunning_resolved",
    "dead_click_observed",
    "rage_click_observed",
    "scroll_depth_observed",
    "form_started",
    "form_field_interaction",
    "form_validation_failed",
    "form_submitted",
    "form_abandoned",
    "search_reformulated",
    "retry_observed",
    "journey_stalled",
    "backtrack_observed",
    "surface_entered",
    "surface_exited",
    "interaction_observed",
    "ui_interaction_observed",
    "feature_started",
    "feature_completed",
    "feature_abandoned",
    "action_attempted",
    "action_succeeded",
    "action_failed",
    "action_cancelled",
    "active_interval_observed",
    "api_request_observed",
    "webhook_delivery_observed",
    "connector_sync_started",
    "connector_sync_completed",
    "connector_sync_failed",
    "job_started",
    "job_completed",
    "job_failed",
    "rate_limit_observed",
    "dependency_failure_observed",
    "export_completed",
    "signup_started",
    "signup_completed",
    "login_succeeded",
    "login_failed",
    "logout_observed",
    "sso_observed",
    "mfa_challenge_observed",
    "identity_verified",
    "alias_link_requested",
    "alias_link_confirmed",
    "alias_revoked",
    "account_recovery_started",
    "account_recovery_completed",
    "device_registered",
    "device_revoked",
    "agent_evaluation_observed",
    "agent_cost_observed",
    "ai_invocation_observed",
    "agent_grounding_observed",
    "agent_guardrail_observed",
    "agent_human_override_observed",
    "transaction_pending_observed",
    "transaction_confirmed_observed",
    "transaction_reverted_observed",
    "transaction_reorged_observed",
    "token_approval_observed",
    "allowance_changed_observed",
    "bridge_transfer_observed",
    "settlement_finality_observed",
    "notification_delivered",
    "notification_opened",
    "notification_clicked",
    "email_delivered",
    "email_opened",
    "email_clicked",
    "email_bounced",
    "email_queued",
    "email_processed",
    "email_sent",
    "email_deferred",
    "email_dropped",
    "email_replied",
    "email_spam_complaint",
    "email_suppressed",
    "message_received_observed",
    "message_sent_observed",
    "message_replied_observed",
    "unsubscribe_observed",
    "support_case_created",
    "support_case_resolved",
    "support_case_escalated",
    "support_sla_breached",
    "credit_signal_observed",
    "credit_account_observed",
    "credit_decision_observed",
    "location_observed",
    "geofence_transition_observed",
    "trading_account_connected",
    "trading_account_disconnected",
    "trading_account_authorized",
    "trading_account_deauthorized",
    "trading_agent_enabled",
    "trading_agent_disabled",
    "trade_intent_created",
    "trade_approval_requested",
    "trade_approval_resolved",
    "risk_policy_updated",
    "human_trade_override_recorded",
    "stablecoin_transfer_observed",
    "stablecoin_payment_observed",
    "stablecoin_mint_observed",
    "stablecoin_burn_observed",
    "stablecoin_bridge_outbound_observed",
    "stablecoin_bridge_inbound_observed",
    "stablecoin_swap_observed",
    "stablecoin_x402_settlement_observed",
    "stablecoin_treasury_movement_observed",
    "stablecoin_payout_observed",
    "stablecoin_venue_deposit_observed",
    "stablecoin_venue_withdrawal_observed",
    "stablecoin_balance_snapshot_observed",
    "stablecoin_supply_snapshot_observed",
    "stablecoin_holder_concentration_observed",
    "stablecoin_valuation_observed",
    "stablecoin_depeg_detected",
    "stablecoin_depeg_resolved",
    "stablecoin_finality_confirmed",
    "stablecoin_reorg_detected",
    "stablecoin_observation_corrected",
    "stablecoin_reconciliation_run_completed",
    "stablecoin_reconciliation_variance_detected",
    "stablecoin_reconciliation_variance_resolved",
    "stablecoin_asset_registered",
    "stablecoin_deployment_registered",
    "stablecoin_support_asserted",
    "stablecoin_support_revoked",
    "stablecoin_flow_aggregate_materialized",
    "stablecoin_checkpoint_advanced",
    "derivatives_venue_registered",
    "derivatives_venue_deployment_registered",
    "derivatives_instrument_registered",
    "derivatives_market_registered",
    "derivatives_strategy_registered",
    "derivatives_strategy_version_registered",
    "derivatives_risk_policy_registered",
    "derivatives_account_linked",
    "derivatives_account_link_revoked",
    "derivatives_balance_snapshot_observed",
    "derivatives_collateral_change_observed",
    "derivatives_margin_snapshot_observed",
    "derivatives_order_observed",
    "derivatives_order_updated_observed",
    "derivatives_order_cancelled_observed",
    "derivatives_order_rejected_observed",
    "derivatives_order_expired_observed",
    "derivatives_fill_observed",
    "derivatives_fill_corrected",
    "derivatives_position_opened_observed",
    "derivatives_position_increased_observed",
    "derivatives_position_reduced_observed",
    "derivatives_position_closed_observed",
    "derivatives_position_liquidated_observed",
    "derivatives_position_adl_observed",
    "derivatives_position_settled_observed",
    "derivatives_position_corrected",
    "derivatives_funding_payment_observed",
    "derivatives_fee_observed",
    "derivatives_pnl_snapshot_materialized",
    "derivatives_exposure_snapshot_materialized",
    "derivatives_price_observation_recorded",
    "derivatives_market_status_changed",
    "derivatives_stream_gap_detected",
    "derivatives_stream_gap_recovered",
    "derivatives_stream_checkpoint_advanced",
    "derivatives_adapter_conformance_run",
    "derivatives_reconciliation_run_completed",
    "derivatives_reconciliation_variance_detected",
    "derivatives_reconciliation_variance_resolved",
    "derivatives_risk_threshold_breached",
    "interop_provider_registered",
    "interop_gateway_registered",
    "interop_path_registered",
    "interop_application_registered",
    "interop_verification_actor_registered",
    "interop_message_discovered",
    "interop_message_sent_observed",
    "interop_message_source_confirmed",
    "interop_message_verification_observed",
    "interop_message_verified",
    "interop_message_delivery_attempt_observed",
    "interop_message_delivered",
    "interop_message_executed_observed",
    "interop_message_settled",
    "interop_message_failed",
    "interop_message_timeout",
    "interop_message_expired",
    "interop_message_cancelled",
    "interop_message_refunded_observed",
    "interop_message_recovered",
    "interop_message_reorged",
    "interop_message_corrected",
    "interop_message_correlated",
    "interop_intent_observed",
    "interop_intent_fulfilled_observed",
    "interop_asset_leg_locked_observed",
    "interop_asset_leg_burned_observed",
    "interop_asset_leg_minted_observed",
    "interop_asset_leg_released_observed",
    "interop_fee_observed",
    "interop_security_policy_snapshot_recorded",
    "interop_security_policy_changed",
    "interop_verification_quorum_observed",
    "interop_provider_checkpoint_advanced",
    "interop_stream_gap_detected",
    "interop_stream_gap_recovered",
    "interop_reconciliation_run_completed",
    "interop_reconciliation_variance_detected",
    "interop_reconciliation_variance_resolved",
})

# Canonical consent purposes — generated from consent-registry.json.
CONSENT_PURPOSES: frozenset[str] = frozenset({
    "agent",
    "analytics",
    "commerce",
    "credit",
    "cross_chain_observability",
    "economic_observability",
    "financial_activity",
    "location",
    "marketing",
    "personalization",
    "web3",
})

# Primary required consent purpose per event type.
# Events with no required purposes (e.g. 'consent') map to 'analytics'.
EVENT_CONSENT_PURPOSE: dict[str, str] = {
    "track": "analytics",
    "page": "analytics",
    "screen": "analytics",
    "heartbeat": "analytics",
    "error": "analytics",
    "performance": "analytics",
    "experiment": "marketing",
    "journey_started": "analytics",
    "journey_paused": "analytics",
    "journey_resumed": "analytics",
    "journey_continued": "analytics",
    "journey_completed": "analytics",
    "journey_abandoned": "analytics",
    "journey_checkpoint": "analytics",
    "navigation_intent": "analytics",
    "navigation_arrival": "analytics",
    "deep_link_opened": "analytics",
    "app_install_attributed": "analytics",
    "deferred_attribution_resolved": "analytics",
    "qr_code_scanned": "analytics",
    "nfc_tag_read": "analytics",
    "app_clip_invoked": "analytics",
    "identify": "analytics",
    "consent": "analytics",
    "conversion": "marketing",
    "payment_initiated": "commerce",
    "payment_completed": "commerce",
    "payment_failed": "commerce",
    "approval_requested": "commerce",
    "approval_resolved": "commerce",
    "entitlement_granted": "commerce",
    "entitlement_revoked": "commerce",
    "access_granted": "commerce",
    "access_denied": "commerce",
    "wallet": "web3",
    "transaction": "web3",
    "contract_action": "web3",
    "agent_task": "agent",
    "agent_decision": "agent",
    "a2h_interaction": "agent",
    "agent_registered": "agent",
    "agent_updated": "agent",
    "agent_authorized": "agent",
    "agent_deauthorized": "agent",
    "agent_capability_granted": "agent",
    "agent_capability_revoked": "agent",
    "agent_task_created": "agent",
    "agent_task_decomposed": "agent",
    "agent_task_started": "agent",
    "agent_task_completed": "agent",
    "agent_task_failed": "agent",
    "agent_tool_called": "agent",
    "agent_resource_requested": "agent",
    "agent_delegated_task": "agent",
    "agent_subagent_spawned": "agent",
    "agent_policy_evaluated": "agent",
    "agent_handoff": "agent",
    "agent_escalated_to_human": "agent",
    "agent_outcome_recorded": "agent",
    "reward_action_queued": "commerce",
    "reward_proof_generated": "commerce",
    "reward_delivered": "commerce",
    "reward_claim_submitted": "commerce",
    "x402_payment": "commerce",
    "x402_resource_requested": "commerce",
    "x402_payment_required": "commerce",
    "x402_quote_received": "commerce",
    "x402_authorization_requested": "commerce",
    "x402_authorization_resolved": "commerce",
    "x402_payment_intent_created": "commerce",
    "x402_payment_submitted": "commerce",
    "x402_payment_settled": "commerce",
    "x402_payment_failed": "commerce",
    "x402_payment_timeout": "commerce",
    "x402_receipt_verified": "commerce",
    "x402_access_granted": "commerce",
    "x402_access_denied": "commerce",
    "x402_refund_or_reversal": "commerce",
    "agentic_account_observed": "agent",
    "agentic_account_connected_observed": "agent",
    "agentic_account_disconnected_observed": "agent",
    "agent_budget_observed": "agent",
    "agent_budget_changed_observed": "agent",
    "agent_permission_observed": "agent",
    "agent_mcp_connection_observed": "agent",
    "agent_tool_observed": "agent",
    "agent_tool_invocation_observed": "agent",
    "agent_activity_observed": "agent",
    "agent_risk_signal_observed": "agent",
    "agent_notification_observed": "agent",
    "agent_strategy_observed": "agent",
    "agent_trade_intent_observed": "agent",
    "agent_trade_order_observed": "financial_activity",
    "agent_trade_fill_observed": "financial_activity",
    "agent_trade_rejection_observed": "agent",
    "agent_position_observed": "financial_activity",
    "agent_portfolio_snapshot_observed": "financial_activity",
    "agent_performance_snapshot_observed": "financial_activity",
    "agent_disconnect_observed": "agent",
    "agent_inbox_observed": "agent",
    "agent_email_address_observed": "agent",
    "agent_thread_observed": "agent",
    "agent_message_received_observed": "agent",
    "agent_message_sent_observed": "agent",
    "agent_reply_observed": "agent",
    "agent_attachment_observed": "agent",
    "agent_attachment_parsed_observed": "agent",
    "agent_otp_detected_observed": "agent",
    "agent_invoice_detected_observed": "agent",
    "agent_receipt_detected_observed": "agent",
    "agent_calendar_intent_observed": "agent",
    "agent_support_route_observed": "agent",
    "agent_semantic_search_observed": "agent",
    "agent_data_extraction_observed": "agent",
    "x402_resource_request_observed": "commerce",
    "x402_challenge_observed": "commerce",
    "x402_payment_requirement_observed": "commerce",
    "x402_signature_observed": "commerce",
    "x402_verification_observed": "commerce",
    "x402_settlement_observed": "commerce",
    "x402_resource_access_observed": "commerce",
    "x402_resource_access_denied_observed": "commerce",
    "x402_failure_observed": "commerce",
    "x402_replay_risk_observed": "commerce",
    "x402_provider_observed": "commerce",
    "content_impression": "analytics",
    "recommendation_exposed": "analytics",
    "offer_exposed": "analytics",
    "feature_exposed": "analytics",
    "search_result_exposed": "analytics",
    "ad_exposed": "marketing",
    "notification_presented": "analytics",
    "decision_observed": "analytics",
    "outcome_observed": "analytics",
    "goal_achieved": "analytics",
    "goal_failed": "analytics",
    "recommendation_accepted": "analytics",
    "recommendation_rejected": "analytics",
    "feedback_submitted": "analytics",
    "retention_observed": "analytics",
    "churn_observed": "analytics",
    "human_override_observed": "analytics",
    "organization_observed": "analytics",
    "workspace_created": "analytics",
    "workspace_updated": "analytics",
    "member_invited": "analytics",
    "member_joined": "analytics",
    "member_removed": "analytics",
    "role_changed": "analytics",
    "seat_assigned": "analytics",
    "seat_released": "analytics",
    "integration_connected": "analytics",
    "integration_disconnected": "analytics",
    "service_account_created": "analytics",
    "service_account_revoked": "analytics",
    "api_key_created": "analytics",
    "api_key_revoked": "analytics",
    "project_created": "analytics",
    "project_archived": "analytics",
    "workflow_started": "analytics",
    "workflow_completed": "analytics",
    "workflow_failed": "analytics",
    "product_viewed": "commerce",
    "cart_item_added": "commerce",
    "cart_item_removed": "commerce",
    "cart_updated": "commerce",
    "coupon_applied": "commerce",
    "checkout_started": "commerce",
    "checkout_step_completed": "commerce",
    "order_completed": "commerce",
    "order_cancelled": "commerce",
    "order_refunded": "commerce",
    "chargeback_observed": "commerce",
    "subscription_started": "commerce",
    "trial_started": "commerce",
    "trial_converted": "commerce",
    "subscription_renewed": "commerce",
    "subscription_upgrade_observed": "commerce",
    "subscription_downgrade_observed": "commerce",
    "subscription_cancelled": "commerce",
    "invoice_issued": "commerce",
    "invoice_paid": "commerce",
    "invoice_failed": "commerce",
    "dunning_started": "commerce",
    "dunning_resolved": "commerce",
    "dead_click_observed": "analytics",
    "rage_click_observed": "analytics",
    "scroll_depth_observed": "analytics",
    "form_started": "analytics",
    "form_field_interaction": "analytics",
    "form_validation_failed": "analytics",
    "form_submitted": "analytics",
    "form_abandoned": "analytics",
    "search_reformulated": "analytics",
    "retry_observed": "analytics",
    "journey_stalled": "analytics",
    "backtrack_observed": "analytics",
    "surface_entered": "analytics",
    "surface_exited": "analytics",
    "interaction_observed": "analytics",
    "ui_interaction_observed": "analytics",
    "feature_started": "analytics",
    "feature_completed": "analytics",
    "feature_abandoned": "analytics",
    "action_attempted": "analytics",
    "action_succeeded": "analytics",
    "action_failed": "analytics",
    "action_cancelled": "analytics",
    "active_interval_observed": "analytics",
    "api_request_observed": "analytics",
    "webhook_delivery_observed": "analytics",
    "connector_sync_started": "analytics",
    "connector_sync_completed": "analytics",
    "connector_sync_failed": "analytics",
    "job_started": "analytics",
    "job_completed": "analytics",
    "job_failed": "analytics",
    "rate_limit_observed": "analytics",
    "dependency_failure_observed": "analytics",
    "export_completed": "analytics",
    "signup_started": "analytics",
    "signup_completed": "analytics",
    "login_succeeded": "analytics",
    "login_failed": "analytics",
    "logout_observed": "analytics",
    "sso_observed": "analytics",
    "mfa_challenge_observed": "analytics",
    "identity_verified": "analytics",
    "alias_link_requested": "analytics",
    "alias_link_confirmed": "analytics",
    "alias_revoked": "analytics",
    "account_recovery_started": "analytics",
    "account_recovery_completed": "analytics",
    "device_registered": "analytics",
    "device_revoked": "analytics",
    "agent_evaluation_observed": "agent",
    "agent_cost_observed": "agent",
    "ai_invocation_observed": "agent",
    "agent_grounding_observed": "agent",
    "agent_guardrail_observed": "agent",
    "agent_human_override_observed": "agent",
    "transaction_pending_observed": "web3",
    "transaction_confirmed_observed": "web3",
    "transaction_reverted_observed": "web3",
    "transaction_reorged_observed": "web3",
    "token_approval_observed": "web3",
    "allowance_changed_observed": "web3",
    "bridge_transfer_observed": "web3",
    "settlement_finality_observed": "web3",
    "notification_delivered": "analytics",
    "notification_opened": "analytics",
    "notification_clicked": "analytics",
    "email_delivered": "marketing",
    "email_opened": "marketing",
    "email_clicked": "marketing",
    "email_bounced": "marketing",
    "email_queued": "marketing",
    "email_processed": "marketing",
    "email_sent": "marketing",
    "email_deferred": "marketing",
    "email_dropped": "marketing",
    "email_replied": "marketing",
    "email_spam_complaint": "marketing",
    "email_suppressed": "marketing",
    "message_received_observed": "analytics",
    "message_sent_observed": "analytics",
    "message_replied_observed": "analytics",
    "unsubscribe_observed": "marketing",
    "support_case_created": "analytics",
    "support_case_resolved": "analytics",
    "support_case_escalated": "analytics",
    "support_sla_breached": "analytics",
    "credit_signal_observed": "credit",
    "credit_account_observed": "credit",
    "credit_decision_observed": "credit",
    "location_observed": "location",
    "geofence_transition_observed": "location",
    "trading_account_connected": "financial_activity",
    "trading_account_disconnected": "financial_activity",
    "trading_account_authorized": "financial_activity",
    "trading_account_deauthorized": "financial_activity",
    "trading_agent_enabled": "financial_activity",
    "trading_agent_disabled": "financial_activity",
    "trade_intent_created": "financial_activity",
    "trade_approval_requested": "financial_activity",
    "trade_approval_resolved": "financial_activity",
    "risk_policy_updated": "financial_activity",
    "human_trade_override_recorded": "financial_activity",
    "stablecoin_transfer_observed": "economic_observability",
    "stablecoin_payment_observed": "economic_observability",
    "stablecoin_mint_observed": "economic_observability",
    "stablecoin_burn_observed": "economic_observability",
    "stablecoin_bridge_outbound_observed": "economic_observability",
    "stablecoin_bridge_inbound_observed": "economic_observability",
    "stablecoin_swap_observed": "economic_observability",
    "stablecoin_x402_settlement_observed": "economic_observability",
    "stablecoin_treasury_movement_observed": "economic_observability",
    "stablecoin_payout_observed": "economic_observability",
    "stablecoin_venue_deposit_observed": "economic_observability",
    "stablecoin_venue_withdrawal_observed": "economic_observability",
    "stablecoin_balance_snapshot_observed": "economic_observability",
    "stablecoin_supply_snapshot_observed": "economic_observability",
    "stablecoin_holder_concentration_observed": "economic_observability",
    "stablecoin_valuation_observed": "economic_observability",
    "stablecoin_depeg_detected": "economic_observability",
    "stablecoin_depeg_resolved": "economic_observability",
    "stablecoin_finality_confirmed": "economic_observability",
    "stablecoin_reorg_detected": "economic_observability",
    "stablecoin_observation_corrected": "economic_observability",
    "stablecoin_reconciliation_run_completed": "economic_observability",
    "stablecoin_reconciliation_variance_detected": "economic_observability",
    "stablecoin_reconciliation_variance_resolved": "economic_observability",
    "stablecoin_asset_registered": "economic_observability",
    "stablecoin_deployment_registered": "economic_observability",
    "stablecoin_support_asserted": "economic_observability",
    "stablecoin_support_revoked": "economic_observability",
    "stablecoin_flow_aggregate_materialized": "economic_observability",
    "stablecoin_checkpoint_advanced": "economic_observability",
    "derivatives_venue_registered": "financial_activity",
    "derivatives_venue_deployment_registered": "financial_activity",
    "derivatives_instrument_registered": "financial_activity",
    "derivatives_market_registered": "financial_activity",
    "derivatives_strategy_registered": "financial_activity",
    "derivatives_strategy_version_registered": "financial_activity",
    "derivatives_risk_policy_registered": "financial_activity",
    "derivatives_account_linked": "financial_activity",
    "derivatives_account_link_revoked": "financial_activity",
    "derivatives_balance_snapshot_observed": "financial_activity",
    "derivatives_collateral_change_observed": "financial_activity",
    "derivatives_margin_snapshot_observed": "financial_activity",
    "derivatives_order_observed": "financial_activity",
    "derivatives_order_updated_observed": "financial_activity",
    "derivatives_order_cancelled_observed": "financial_activity",
    "derivatives_order_rejected_observed": "financial_activity",
    "derivatives_order_expired_observed": "financial_activity",
    "derivatives_fill_observed": "financial_activity",
    "derivatives_fill_corrected": "financial_activity",
    "derivatives_position_opened_observed": "financial_activity",
    "derivatives_position_increased_observed": "financial_activity",
    "derivatives_position_reduced_observed": "financial_activity",
    "derivatives_position_closed_observed": "financial_activity",
    "derivatives_position_liquidated_observed": "financial_activity",
    "derivatives_position_adl_observed": "financial_activity",
    "derivatives_position_settled_observed": "financial_activity",
    "derivatives_position_corrected": "financial_activity",
    "derivatives_funding_payment_observed": "financial_activity",
    "derivatives_fee_observed": "financial_activity",
    "derivatives_pnl_snapshot_materialized": "financial_activity",
    "derivatives_exposure_snapshot_materialized": "financial_activity",
    "derivatives_price_observation_recorded": "financial_activity",
    "derivatives_market_status_changed": "financial_activity",
    "derivatives_stream_gap_detected": "financial_activity",
    "derivatives_stream_gap_recovered": "financial_activity",
    "derivatives_stream_checkpoint_advanced": "financial_activity",
    "derivatives_adapter_conformance_run": "financial_activity",
    "derivatives_reconciliation_run_completed": "financial_activity",
    "derivatives_reconciliation_variance_detected": "financial_activity",
    "derivatives_reconciliation_variance_resolved": "financial_activity",
    "derivatives_risk_threshold_breached": "financial_activity",
    "interop_provider_registered": "cross_chain_observability",
    "interop_gateway_registered": "cross_chain_observability",
    "interop_path_registered": "cross_chain_observability",
    "interop_application_registered": "cross_chain_observability",
    "interop_verification_actor_registered": "cross_chain_observability",
    "interop_message_discovered": "cross_chain_observability",
    "interop_message_sent_observed": "cross_chain_observability",
    "interop_message_source_confirmed": "cross_chain_observability",
    "interop_message_verification_observed": "cross_chain_observability",
    "interop_message_verified": "cross_chain_observability",
    "interop_message_delivery_attempt_observed": "cross_chain_observability",
    "interop_message_delivered": "cross_chain_observability",
    "interop_message_executed_observed": "cross_chain_observability",
    "interop_message_settled": "cross_chain_observability",
    "interop_message_failed": "cross_chain_observability",
    "interop_message_timeout": "cross_chain_observability",
    "interop_message_expired": "cross_chain_observability",
    "interop_message_cancelled": "cross_chain_observability",
    "interop_message_refunded_observed": "cross_chain_observability",
    "interop_message_recovered": "cross_chain_observability",
    "interop_message_reorged": "cross_chain_observability",
    "interop_message_corrected": "cross_chain_observability",
    "interop_message_correlated": "cross_chain_observability",
    "interop_intent_observed": "cross_chain_observability",
    "interop_intent_fulfilled_observed": "cross_chain_observability",
    "interop_asset_leg_locked_observed": "cross_chain_observability",
    "interop_asset_leg_burned_observed": "cross_chain_observability",
    "interop_asset_leg_minted_observed": "cross_chain_observability",
    "interop_asset_leg_released_observed": "cross_chain_observability",
    "interop_fee_observed": "cross_chain_observability",
    "interop_security_policy_snapshot_recorded": "cross_chain_observability",
    "interop_security_policy_changed": "cross_chain_observability",
    "interop_verification_quorum_observed": "cross_chain_observability",
    "interop_provider_checkpoint_advanced": "cross_chain_observability",
    "interop_stream_gap_detected": "cross_chain_observability",
    "interop_stream_gap_recovered": "cross_chain_observability",
    "interop_reconciliation_run_completed": "cross_chain_observability",
    "interop_reconciliation_variance_detected": "cross_chain_observability",
    "interop_reconciliation_variance_resolved": "cross_chain_observability",
}

EVENT_FAMILY: dict[str, str] = {
    "track": "core",
    "page": "core",
    "screen": "core",
    "heartbeat": "core",
    "error": "core",
    "performance": "core",
    "experiment": "core",
    "journey_started": "journey",
    "journey_paused": "journey",
    "journey_resumed": "journey",
    "journey_continued": "journey",
    "journey_completed": "journey",
    "journey_abandoned": "journey",
    "journey_checkpoint": "journey",
    "navigation_intent": "journey",
    "navigation_arrival": "journey",
    "deep_link_opened": "journey",
    "app_install_attributed": "journey",
    "deferred_attribution_resolved": "journey",
    "qr_code_scanned": "journey",
    "nfc_tag_read": "journey",
    "app_clip_invoked": "journey",
    "identify": "identity",
    "consent": "consent",
    "conversion": "commerce",
    "payment_initiated": "commerce",
    "payment_completed": "commerce",
    "payment_failed": "commerce",
    "approval_requested": "commerce",
    "approval_resolved": "commerce",
    "entitlement_granted": "commerce",
    "entitlement_revoked": "commerce",
    "access_granted": "commerce",
    "access_denied": "commerce",
    "wallet": "wallet",
    "transaction": "wallet",
    "contract_action": "wallet",
    "agent_task": "agent",
    "agent_decision": "agent",
    "a2h_interaction": "agent",
    "agent_registered": "agent",
    "agent_updated": "agent",
    "agent_authorized": "agent",
    "agent_deauthorized": "agent",
    "agent_capability_granted": "agent",
    "agent_capability_revoked": "agent",
    "agent_task_created": "agent",
    "agent_task_decomposed": "agent",
    "agent_task_started": "agent",
    "agent_task_completed": "agent",
    "agent_task_failed": "agent",
    "agent_tool_called": "agent",
    "agent_resource_requested": "agent",
    "agent_delegated_task": "agent",
    "agent_subagent_spawned": "agent",
    "agent_policy_evaluated": "agent",
    "agent_handoff": "agent",
    "agent_escalated_to_human": "agent",
    "agent_outcome_recorded": "agent",
    "reward_action_queued": "reward",
    "reward_proof_generated": "reward",
    "reward_delivered": "reward",
    "reward_claim_submitted": "reward",
    "x402_payment": "x402",
    "x402_resource_requested": "x402",
    "x402_payment_required": "x402",
    "x402_quote_received": "x402",
    "x402_authorization_requested": "x402",
    "x402_authorization_resolved": "x402",
    "x402_payment_intent_created": "x402",
    "x402_payment_submitted": "x402",
    "x402_payment_settled": "x402",
    "x402_payment_failed": "x402",
    "x402_payment_timeout": "x402",
    "x402_receipt_verified": "x402",
    "x402_access_granted": "x402",
    "x402_access_denied": "x402",
    "x402_refund_or_reversal": "x402",
    "agentic_account_observed": "agent",
    "agentic_account_connected_observed": "agent",
    "agentic_account_disconnected_observed": "agent",
    "agent_budget_observed": "agent",
    "agent_budget_changed_observed": "agent",
    "agent_permission_observed": "agent",
    "agent_mcp_connection_observed": "agent",
    "agent_tool_observed": "agent",
    "agent_tool_invocation_observed": "agent",
    "agent_activity_observed": "agent",
    "agent_risk_signal_observed": "agent",
    "agent_notification_observed": "agent",
    "agent_strategy_observed": "agent",
    "agent_trade_intent_observed": "agent",
    "agent_trade_order_observed": "agent",
    "agent_trade_fill_observed": "agent",
    "agent_trade_rejection_observed": "agent",
    "agent_position_observed": "agent",
    "agent_portfolio_snapshot_observed": "agent",
    "agent_performance_snapshot_observed": "agent",
    "agent_disconnect_observed": "agent",
    "agent_inbox_observed": "agent",
    "agent_email_address_observed": "agent",
    "agent_thread_observed": "agent",
    "agent_message_received_observed": "agent",
    "agent_message_sent_observed": "agent",
    "agent_reply_observed": "agent",
    "agent_attachment_observed": "agent",
    "agent_attachment_parsed_observed": "agent",
    "agent_otp_detected_observed": "agent",
    "agent_invoice_detected_observed": "agent",
    "agent_receipt_detected_observed": "agent",
    "agent_calendar_intent_observed": "agent",
    "agent_support_route_observed": "agent",
    "agent_semantic_search_observed": "agent",
    "agent_data_extraction_observed": "agent",
    "x402_resource_request_observed": "x402",
    "x402_challenge_observed": "x402",
    "x402_payment_requirement_observed": "x402",
    "x402_signature_observed": "x402",
    "x402_verification_observed": "x402",
    "x402_settlement_observed": "x402",
    "x402_resource_access_observed": "x402",
    "x402_resource_access_denied_observed": "x402",
    "x402_failure_observed": "x402",
    "x402_replay_risk_observed": "x402",
    "x402_provider_observed": "x402",
    "content_impression": "exposure",
    "recommendation_exposed": "exposure",
    "offer_exposed": "exposure",
    "feature_exposed": "exposure",
    "search_result_exposed": "exposure",
    "ad_exposed": "exposure",
    "notification_presented": "exposure",
    "decision_observed": "exposure",
    "outcome_observed": "outcome",
    "goal_achieved": "outcome",
    "goal_failed": "outcome",
    "recommendation_accepted": "outcome",
    "recommendation_rejected": "outcome",
    "feedback_submitted": "outcome",
    "retention_observed": "outcome",
    "churn_observed": "outcome",
    "human_override_observed": "outcome",
    "organization_observed": "b2b",
    "workspace_created": "b2b",
    "workspace_updated": "b2b",
    "member_invited": "b2b",
    "member_joined": "b2b",
    "member_removed": "b2b",
    "role_changed": "b2b",
    "seat_assigned": "b2b",
    "seat_released": "b2b",
    "integration_connected": "b2b",
    "integration_disconnected": "b2b",
    "service_account_created": "b2b",
    "service_account_revoked": "b2b",
    "api_key_created": "b2b",
    "api_key_revoked": "b2b",
    "project_created": "b2b",
    "project_archived": "b2b",
    "workflow_started": "b2b",
    "workflow_completed": "b2b",
    "workflow_failed": "b2b",
    "product_viewed": "ecommerce",
    "cart_item_added": "ecommerce",
    "cart_item_removed": "ecommerce",
    "cart_updated": "ecommerce",
    "coupon_applied": "ecommerce",
    "checkout_started": "ecommerce",
    "checkout_step_completed": "ecommerce",
    "order_completed": "ecommerce",
    "order_cancelled": "ecommerce",
    "order_refunded": "ecommerce",
    "chargeback_observed": "ecommerce",
    "subscription_started": "ecommerce",
    "trial_started": "ecommerce",
    "trial_converted": "ecommerce",
    "subscription_renewed": "ecommerce",
    "subscription_upgrade_observed": "ecommerce",
    "subscription_downgrade_observed": "ecommerce",
    "subscription_cancelled": "ecommerce",
    "invoice_issued": "ecommerce",
    "invoice_paid": "ecommerce",
    "invoice_failed": "ecommerce",
    "dunning_started": "ecommerce",
    "dunning_resolved": "ecommerce",
    "dead_click_observed": "friction",
    "rage_click_observed": "friction",
    "scroll_depth_observed": "friction",
    "form_started": "friction",
    "form_field_interaction": "friction",
    "form_validation_failed": "friction",
    "form_submitted": "friction",
    "form_abandoned": "friction",
    "search_reformulated": "friction",
    "retry_observed": "friction",
    "journey_stalled": "friction",
    "backtrack_observed": "friction",
    "surface_entered": "interaction",
    "surface_exited": "interaction",
    "interaction_observed": "interaction",
    "ui_interaction_observed": "interaction",
    "feature_started": "interaction",
    "feature_completed": "interaction",
    "feature_abandoned": "interaction",
    "action_attempted": "interaction",
    "action_succeeded": "interaction",
    "action_failed": "interaction",
    "action_cancelled": "interaction",
    "active_interval_observed": "interaction",
    "api_request_observed": "server",
    "webhook_delivery_observed": "server",
    "connector_sync_started": "server",
    "connector_sync_completed": "server",
    "connector_sync_failed": "server",
    "job_started": "server",
    "job_completed": "server",
    "job_failed": "server",
    "rate_limit_observed": "server",
    "dependency_failure_observed": "server",
    "export_completed": "server",
    "signup_started": "identity_lc",
    "signup_completed": "identity_lc",
    "login_succeeded": "identity_lc",
    "login_failed": "identity_lc",
    "logout_observed": "identity_lc",
    "sso_observed": "identity_lc",
    "mfa_challenge_observed": "identity_lc",
    "identity_verified": "identity_lc",
    "alias_link_requested": "identity_lc",
    "alias_link_confirmed": "identity_lc",
    "alias_revoked": "identity_lc",
    "account_recovery_started": "identity_lc",
    "account_recovery_completed": "identity_lc",
    "device_registered": "identity_lc",
    "device_revoked": "identity_lc",
    "agent_evaluation_observed": "agent",
    "agent_cost_observed": "agent",
    "ai_invocation_observed": "agent",
    "agent_grounding_observed": "agent",
    "agent_guardrail_observed": "agent",
    "agent_human_override_observed": "agent",
    "transaction_pending_observed": "web3_lc",
    "transaction_confirmed_observed": "web3_lc",
    "transaction_reverted_observed": "web3_lc",
    "transaction_reorged_observed": "web3_lc",
    "token_approval_observed": "web3_lc",
    "allowance_changed_observed": "web3_lc",
    "bridge_transfer_observed": "web3_lc",
    "settlement_finality_observed": "web3_lc",
    "notification_delivered": "comms",
    "notification_opened": "comms",
    "notification_clicked": "comms",
    "email_delivered": "comms",
    "email_opened": "comms",
    "email_clicked": "comms",
    "email_bounced": "comms",
    "email_queued": "comms",
    "email_processed": "comms",
    "email_sent": "comms",
    "email_deferred": "comms",
    "email_dropped": "comms",
    "email_replied": "comms",
    "email_spam_complaint": "comms",
    "email_suppressed": "comms",
    "message_received_observed": "comms",
    "message_sent_observed": "comms",
    "message_replied_observed": "comms",
    "unsubscribe_observed": "comms",
    "support_case_created": "comms",
    "support_case_resolved": "comms",
    "support_case_escalated": "comms",
    "support_sla_breached": "comms",
    "credit_signal_observed": "credit",
    "credit_account_observed": "credit",
    "credit_decision_observed": "credit",
    "location_observed": "location",
    "geofence_transition_observed": "location",
    "trading_account_connected": "derivatives",
    "trading_account_disconnected": "derivatives",
    "trading_account_authorized": "derivatives",
    "trading_account_deauthorized": "derivatives",
    "trading_agent_enabled": "derivatives",
    "trading_agent_disabled": "derivatives",
    "trade_intent_created": "derivatives",
    "trade_approval_requested": "derivatives",
    "trade_approval_resolved": "derivatives",
    "risk_policy_updated": "derivatives",
    "human_trade_override_recorded": "derivatives",
    "stablecoin_transfer_observed": "stablecoin",
    "stablecoin_payment_observed": "stablecoin",
    "stablecoin_mint_observed": "stablecoin",
    "stablecoin_burn_observed": "stablecoin",
    "stablecoin_bridge_outbound_observed": "stablecoin",
    "stablecoin_bridge_inbound_observed": "stablecoin",
    "stablecoin_swap_observed": "stablecoin",
    "stablecoin_x402_settlement_observed": "stablecoin",
    "stablecoin_treasury_movement_observed": "stablecoin",
    "stablecoin_payout_observed": "stablecoin",
    "stablecoin_venue_deposit_observed": "stablecoin",
    "stablecoin_venue_withdrawal_observed": "stablecoin",
    "stablecoin_balance_snapshot_observed": "stablecoin",
    "stablecoin_supply_snapshot_observed": "stablecoin",
    "stablecoin_holder_concentration_observed": "stablecoin",
    "stablecoin_valuation_observed": "stablecoin",
    "stablecoin_depeg_detected": "stablecoin",
    "stablecoin_depeg_resolved": "stablecoin",
    "stablecoin_finality_confirmed": "stablecoin",
    "stablecoin_reorg_detected": "stablecoin",
    "stablecoin_observation_corrected": "stablecoin",
    "stablecoin_reconciliation_run_completed": "stablecoin",
    "stablecoin_reconciliation_variance_detected": "stablecoin",
    "stablecoin_reconciliation_variance_resolved": "stablecoin",
    "stablecoin_asset_registered": "stablecoin",
    "stablecoin_deployment_registered": "stablecoin",
    "stablecoin_support_asserted": "stablecoin",
    "stablecoin_support_revoked": "stablecoin",
    "stablecoin_flow_aggregate_materialized": "stablecoin",
    "stablecoin_checkpoint_advanced": "stablecoin",
    "derivatives_venue_registered": "derivatives",
    "derivatives_venue_deployment_registered": "derivatives",
    "derivatives_instrument_registered": "derivatives",
    "derivatives_market_registered": "derivatives",
    "derivatives_strategy_registered": "derivatives",
    "derivatives_strategy_version_registered": "derivatives",
    "derivatives_risk_policy_registered": "derivatives",
    "derivatives_account_linked": "derivatives",
    "derivatives_account_link_revoked": "derivatives",
    "derivatives_balance_snapshot_observed": "derivatives",
    "derivatives_collateral_change_observed": "derivatives",
    "derivatives_margin_snapshot_observed": "derivatives",
    "derivatives_order_observed": "derivatives",
    "derivatives_order_updated_observed": "derivatives",
    "derivatives_order_cancelled_observed": "derivatives",
    "derivatives_order_rejected_observed": "derivatives",
    "derivatives_order_expired_observed": "derivatives",
    "derivatives_fill_observed": "derivatives",
    "derivatives_fill_corrected": "derivatives",
    "derivatives_position_opened_observed": "derivatives",
    "derivatives_position_increased_observed": "derivatives",
    "derivatives_position_reduced_observed": "derivatives",
    "derivatives_position_closed_observed": "derivatives",
    "derivatives_position_liquidated_observed": "derivatives",
    "derivatives_position_adl_observed": "derivatives",
    "derivatives_position_settled_observed": "derivatives",
    "derivatives_position_corrected": "derivatives",
    "derivatives_funding_payment_observed": "derivatives",
    "derivatives_fee_observed": "derivatives",
    "derivatives_pnl_snapshot_materialized": "derivatives",
    "derivatives_exposure_snapshot_materialized": "derivatives",
    "derivatives_price_observation_recorded": "derivatives",
    "derivatives_market_status_changed": "derivatives",
    "derivatives_stream_gap_detected": "derivatives",
    "derivatives_stream_gap_recovered": "derivatives",
    "derivatives_stream_checkpoint_advanced": "derivatives",
    "derivatives_adapter_conformance_run": "derivatives",
    "derivatives_reconciliation_run_completed": "derivatives",
    "derivatives_reconciliation_variance_detected": "derivatives",
    "derivatives_reconciliation_variance_resolved": "derivatives",
    "derivatives_risk_threshold_breached": "derivatives",
    "interop_provider_registered": "interop",
    "interop_gateway_registered": "interop",
    "interop_path_registered": "interop",
    "interop_application_registered": "interop",
    "interop_verification_actor_registered": "interop",
    "interop_message_discovered": "interop",
    "interop_message_sent_observed": "interop",
    "interop_message_source_confirmed": "interop",
    "interop_message_verification_observed": "interop",
    "interop_message_verified": "interop",
    "interop_message_delivery_attempt_observed": "interop",
    "interop_message_delivered": "interop",
    "interop_message_executed_observed": "interop",
    "interop_message_settled": "interop",
    "interop_message_failed": "interop",
    "interop_message_timeout": "interop",
    "interop_message_expired": "interop",
    "interop_message_cancelled": "interop",
    "interop_message_refunded_observed": "interop",
    "interop_message_recovered": "interop",
    "interop_message_reorged": "interop",
    "interop_message_corrected": "interop",
    "interop_message_correlated": "interop",
    "interop_intent_observed": "interop",
    "interop_intent_fulfilled_observed": "interop",
    "interop_asset_leg_locked_observed": "interop",
    "interop_asset_leg_burned_observed": "interop",
    "interop_asset_leg_minted_observed": "interop",
    "interop_asset_leg_released_observed": "interop",
    "interop_fee_observed": "interop",
    "interop_security_policy_snapshot_recorded": "interop",
    "interop_security_policy_changed": "interop",
    "interop_verification_quorum_observed": "interop",
    "interop_provider_checkpoint_advanced": "interop",
    "interop_stream_gap_detected": "interop",
    "interop_stream_gap_recovered": "interop",
    "interop_reconciliation_run_completed": "interop",
    "interop_reconciliation_variance_detected": "interop",
    "interop_reconciliation_variance_resolved": "interop",
}
