export const CONTROLLER_FUNCTIONAL_NAMES = {
    governance: 'Policy & Governance',
    char: 'Top Orchestrator',
    intake: 'Signal Intake',
    gouf: 'Graph Topology',
    zeong: 'Anomaly Watch',
    triage: 'Priority Triage',
    verification: 'Evidence Verification',
    commit: 'Action Commit',
    recovery: 'Recovery & Rollback',
    chronicle: 'Timeline & Memory',
    trigger: 'Schedule & Triggers',
    relay: 'Notification Relay',
};
export const CONTROLLER_EXPRESSIVE_NAMES = {
    governance: 'The Arbiter',
    char: 'CHAR — The Red Comet',
    intake: 'The Gatekeeper',
    gouf: 'GOUF — The Cartographer',
    zeong: 'ZEONG — The Watcher',
    triage: 'The Surgeon',
    verification: 'The Auditor',
    commit: 'The Executor',
    recovery: 'The Restorer',
    chronicle: 'The Chronicler',
    trigger: 'The Clockmaker',
    relay: 'The Herald',
};
