export {
  fetchTargetingIntents,
  createTargetingIntent,
  fetchTargetingIntent,
  createEligibilitySnapshot,
  fetchEligibilitySnapshots,
  fetchTargetingObservations,
  fetchLeakageFindings,
  fetchTargetingHoldouts,
  fetchJourneyDeltas,
  createTargetingExport,
  fetchTargetingExports,
  fetchCampaignTargetingIntelligence,
  fetchClusterTargetingImpact,
  clusterTargetingRuleSchema,
  targetingIntentSchema,
  eligibilitySnapshotSchema,
  providerMappingQualitySchema,
  targetingObservationSchema,
  leakageFindingSchema,
  targetingHoldoutSchema,
  journeyDeltaSchema,
  clusterTargetingImpactSchema,
  exportPackageSchema,
  campaignTargetingSummarySchema,
  clusterTargetingImpactResponseSchema,
} from './api';
export type {
  ClusterTargetingRuleRecord,
  TargetingIntentRecord,
  TargetingIntentListResult,
  EligibilitySnapshotRecord,
  EligibilitySnapshotListResult,
  ProviderMappingQualityRecord,
  TargetingObservationRecord,
  TargetingObservationListResult,
  LeakageFindingRecord,
  LeakageFindingListResult,
  TargetingHoldoutRecord,
  TargetingHoldoutListResult,
  JourneyDeltaRecord,
  JourneyDeltaListResult,
  ClusterTargetingImpactRecord,
  ExportPackageRecord,
  ExportPackageListResult,
  CreateTargetingExportParams,
  CampaignTargetingSummaryRecord,
  CampaignTargetingSummaryResult,
  ClusterTargetingImpactResponseRecord,
  ClusterTargetingImpactResult,
} from './api';
export {
  useCampaignTargetingIntelligence,
  useClusterTargetingImpact,
  useCampaignJourneyDeltas,
  useTargetingHoldouts,
  useTargetingExports,
  useCreateTargetingExport,
} from './use-targeting-intelligence';
export {
  CAMPAIGN_BOUNDARY_COPY,
  EXPORT_BOUNDARY_COPY,
  EXTERNAL_EXECUTION_REQUIRED_COPY,
  ClusterChip,
  ClusterChipGroup,
  EvidenceChainSummary,
  ExportPackageDetail,
  LeakageSeverityBadge,
} from './components/targeting-shared';
export { CampaignTargetingIntelligenceTab } from './components/CampaignTargetingIntelligenceTab';
export { ClusterTargetingImpactTab } from './components/ClusterTargetingImpactTab';
export { TargetingSuggestionSection, isTargetingSuggestion } from './components/TargetingSuggestionSection';
